### PR TITLE
add Gatsby theme library resource card

### PR DESCRIPTION
**Pull request by laurenmrice**
**New**
- Added the Gatsby theme sketch library resource card link to our design resources.

----

**Testing**
- Navigate to `Designing` -> `Other resources` page -> `Extensions` section
- Make sure the resource card shows up correctly and links out to the library to download

### CODE REVIEW

**Review by janchild — APPROVED** [review]
🥂  @laurenmrice, it would be good to announce this one in the channels too!

**Review by jeanservaas — APPROVED** [review]
boom merge.

**Comment by laurenmrice** [comment]
Hold on merging ‼️. Might need to move library to its own section

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by janchild — CHANGES_REQUESTED** [review]
@laurenmrice as this is going to link from a card on the Home page, I'm going to write some text and give it its own section on this page. More soon...

**Pull request closed without merging**
