### PR TITLE
docs: update slider with range variant

### LINKED ISSUE #3730: [Slider] Two Handles Defining the Range: website docs
@KevinCamelo

### Usage tab
- [x] Update content and images
- [x] Get design review

### Style tab
- [x] Update content and images
- [x] Get design review

### Accessbility tab
- [x] Update content and images
- [x] Get A11y review

### PR DESCRIPTION
**Pull request by laurenmrice**
Closes
#3730
#3788

- Updates the Slider component docs with the new range variant.
- Updates the Slider component docs with Usage and Style template changes.

------

**New**

- Added the range slider variant
- Updated the documentation with the markdown content template for Usage/Style/Accessibility

**Changed**

- Updated content
- Updated images

**Removed**

- Unused images
- Unused videos

### CODE REVIEW

**Comment by laurenmrice** [comment]
I need help from a dev to get the Range slider in react into the Live demos on the Usage and Codes tabs. Thank you!

**Comment by mbgower** [comment]
@laurenmrice I just wanted to check that the discussion we had recently is captured -- in regard to the fact the range slider lacks any persistent decent contrast indicator of an end point _if_ a variant without inputs exists.

The existing slider _always_ indicates how much space exists between the 0 value and the visual point it represents. It lacks a persistent good contrast indicator at the max value end, but one can extrapolate the distance at the other end and infer what it is likely to be. So if the numeric input disappears, it's not that critical.

For the range slider, if neither point starts at an extreme, a user who cannot see well cannot actually infer how much of the slider is selected in the range. Obviously when the big numeric inputs are on each end, even users with fairly poor vision can immediately see the range values, so it is not an issue there, but if the inputs are removed, it's quite difficult -- and arguably more mental effort -- to figure out how much of the slider range is selected.

If you've captured this elsewhere, feel free to delete this comment.

**Comment by laurenmrice** [comment]
@mbgower Yes, we will be tracking this in a separate issue. It needs to go through a design iteration before it goes to development. Once it is in code, then we can update the website documentation and the figma kit with those changes.

**Review by andreancardona — APPROVED** [review]
Made the changes to the live demo and looks good!

**Comment by KevinCamelo** [comment]
Hey @mbgower wanted to point you to where we noted that suggestion down for a future enhancement. 🎉 

Thanks for the work on this everyone! 
https://github.com/carbon-design-system/carbon/issues/14549#issuecomment-1804762148

**Review by kingtraceyj — APPROVED** [review]
💥  looks good to go!

**Pull request merged**
