### PR TITLE
Ecosystem updates

### PR DESCRIPTION
**Pull request by mzuliani-ibm**
Update tiles that link to ecosystem PALs on Ecosystems and Domain guideance page.
~~Update job titles on Partners page related to AI Applications~~

#### Changelog

**New**

- icons for Sustainability Software and Carbon for IBM Products

**Changed**

- Renamed: AI Apps > Sustainability Software
- Merged: Two tiles: Cloud and Cloud & Cognitive to one tile Carbon for IBM Products

**Removed**

- Cloud tile

Preview:

### CODE REVIEW

**Comment by mzuliani-ibm** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by tay1orjones — APPROVED** [review]

**Review by laurenmrice — COMMENTED** [review]
Hi @mzuliani-ibm Would you also be able to update the resource cards on our [Community assets > Domain guidance](https://carbondesignsystem-git-fork-mzulian-6ece73-carbon-design-system.vercel.app/community/domain-guidance/#product) as well so it is consistent?

**Comment by mzuliani-ibm** [comment]
@laurenmrice sure, didn't see that. Will do.

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Will re-approve once the changes to the `Partners` and `Carbon team` pages are removed. 👍

**Comment by mzuliani-ibm** [comment]
Pulled in changes from https://github.com/carbon-design-system/carbon-website/pull/3170 to allow merging.

**Review by laurenmrice — APPROVED** [review]

**Pull request merged**
