### PR TITLE
update carbon charts to v0.41.92

### PR DESCRIPTION
**Pull request by theiliad**

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Flipped through the data viz pages, looks good 👍

**Comment by thyhmdo** [comment]
Complex chart: 
- Divergent scale link is showing 404
Other than that, everything seems good.

**Comment by theiliad** [comment]
> * Divergent scale link is showing 404

That'd be an issue for a different PR. This PR isn't modifying any of that

**Review by thyhmdo — COMMENTED** [review]
Looks good to me then!

**Review by andreancardona — APPROVED** [review]

**Pull request merged**
