### PR TITLE
fix(data-viz): ensure color palette updates on theme change

### PR DESCRIPTION
**Pull request by tw15egan**
https://github.com/carbon-design-system/carbon-website/issues/1936

Fixes an issue where the color palette was not updated when the theme was changed

#### Changelog

**Changed**

- `useEffect` hook to update the color values when the theme is changed, not just when the dropdown is changed

### CODE REVIEW

**Review by jeanservaas — COMMENTED** [review]
thanks for getting on this! Just a couple of things:
That dropdown (for the color groupings) to the right of the tabs should also have a white (not g10 background)


image

The alert palette also changes from light to dark, right now those are only the light values on both of the tabs and green value is wrong for the light:

image

image


**Should be:**
image

**Comment by tw15egan** [comment]
@jeanservaas updated, although I noticed `#198038` (rather than `#78a9ff`) seems like the correct hex for `Green 60`.

**Review by emyarod — APPROVED** [review]
looks good to me pending visual review

**Review by aledavila — APPROVED** [review]

**Review by jeanservaas — APPROVED** [review]
boom

**Pull request merged**
