### PR TITLE
fix(color): fix v10 color page bugs

### LINKED ISSUE #2451: Assorted bugs on the color page
Make sure updates are on the v11 site (can also be updated on v10/current site).

1. Caption under the [theme swatches](https://www.carbondesignsystem.com/guidelines/color/overview/#themes) should use the type size 14px instead of 16px. Code says its caption but its rendering at the wrong size. 

image
image

2. Theme swatches should be take up the full width on mobile.
image

3. Outlines around the swatches in the themes table needs to be darker. Change to Gray 30 `#C6C6C6`

image

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #2451 

3 bugs on the color page. Please see ticket issue: 

- [x] Update `box--caption`to  `font-size: 14px;`
- [x] Update theme cards in mobile
- [x] Update radio button outline to `gray-30`

### CODE REVIEW

**Comment by tw15egan** [comment]
Seems like there is an layout issue with the theme swatches

Screen Shot 2021-07-30 at 9 21 08 AM

**Comment by andreancardona** [comment]
> Seems like there is an layout issue with the theme swatches
> 
> Screen Shot 2021-07-30 at 9 21 08 AM

Ohh shoot at which viewport is this?

**Review by aagonzales — CHANGES_REQUESTED** [review]
The other edit look good but the theme swatches on desktop appear to be broken now.
image

Should look like this:
image

**Comment by andreancardona** [comment]
> The other edit look good but the theme swatches on desktop appear to be broken now.
> image
> 
> Should look like this:
> image

yeah fixing it now :) NOT sure how I didn't see that before

**Comment by andreancardona** [comment]
@tw15egan @aagonzales sorry ya'll don't know what happened there. Should be good with this preview!

**Review by aagonzales — APPROVED** [review]
LGTM!

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by andreancardona** [comment]
@sstrubberg ready whenever you get a chance :)

**Review by sstrubberg — APPROVED** [review]

**Pull request merged**
