### PR TITLE
fix(website): fix FormGroup warnings, color table bugs

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon-website/issues/1831
Closes https://github.com/carbon-design-system/carbon-website/issues/1828

Our `FormGroup` component requires a `legendText` prop, which is used to populate a label for groups like Radio Buttons and Checkboxes. All other form elements supply their own label through the `labelText` property.

Also, fixed an issue with the color table hanging over the table on scroll. 

#### Changelog

**Changed**

- swapped `FormGroup` with generic `div` and added spacing 
- Modified some Layout styles for when the banner is/is not present. 

**Testing** 
- [ ] Ensure `Form` and `TextInput` Usage and Code pages look correct
- [ ] Ensure all sticky headers (Color Table, Typography Table, etc..) render properly with/without the banner

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Changes look good 👍  for the website is this a common enough change where we want a class name instead of the inline styles for the new `<div>`s? Just wasn't sure when looking at the diff 👀

**Comment by tw15egan** [comment]
I can create a class for this. I added some notes in our Prop audit around this convention, and how we need to normalize form spacing 👍 . Seems like we were using`FromGroup` just to get that nice `2rem` of space

**Comment by tw15egan** [comment]
@joshblack actually on second thought, since these are copyable code snippets it may be confusing to add a class that will have no styles associated with it when copied over.

**Review by aledavila — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]
Looks good!

**Pull request merged**
