### PR TITLE
Update website to v11, @carbon/react

### PR DESCRIPTION
**Pull request by tay1orjones**
This PR updates the website to use the newest version of `gatsby`, `gatsby-theme-carbon`, and related carbon dependencies for v11

#### Changelog

**Changed**

- update various dependencies
- update sass token usage to reflect changes made in v11

### CODE REVIEW

**Comment by tay1orjones** [comment]
@sstrubberg @alisonjoseph - @aledavila and I did not encounter the pictogram library and icon library issues you encountered in https://github.com/carbon-design-system/carbon-website/pull/2689 🎉

**Comment by tay1orjones** [comment]
I put a lot of reviewers on here - the more eyes the better! 👀  We've stepped through nearly every page and things seem to look good, but a thorough review is appreciated 🙏

**Comment by alisonjoseph** [comment]
>@sstrubberg @alisonjoseph - @aledavila and I did not encounter the pictogram library and icon library issues you encountered in https://github.com/carbon-design-system/carbon-website/pull/2689 🎉

Awesome! Will take a look through tomorrow 💯

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
Noticed a few things, probably related to the 12 col vs 16 col grid update.

- [x] Homepage design grid alignment is "off", v11 on top vs. www on bottom.
Screen Shot 2022-03-08 at 2 32 31 PM

- [x] Color usage table is off grid
Screen Shot 2022-03-08 at 2 34 30 PM

- [x] Search for icons/pictograms page styles are off, "sticky" is broken
Screen Shot 2022-03-08 at 2 35 26 PM

- [x] Do dont components are off grid across the site
Screen Shot 2022-03-08 at 2 36 33 PM

- [x] Typography page components are incorrect width
Screen Shot 2022-03-08 at 2 36 59 PM

- [ ] Styles on type sets page are wrong
Screen Shot 2022-03-08 at 2 37 39 PM

- [ ] Component overview is incorrect width
Screen Shot 2022-03-08 at 2 38 14 PM

- [ ] Live demo white background is missing
Screen Shot 2022-03-08 at 2 38 48 PM

- [ ] Images are incorrect width across entire website, likely due to the grid

- [ ] Resource cards are incorrect grid size across website
Screen Shot 2022-03-08 at 2 40 35 PM

- [ ] Chart cards are too small
Screen Shot 2022-03-08 at 2 41 03 PM

- [ ] Inline notifications are too short across the site (this might need to get fixed in the theme?)
Screen Shot 2022-03-08 at 2 41 51 PM

- [ ] Same with short page tables across the site
Screen Shot 2022-03-08 at 2 42 58 PM

Not sure if this is a comprehensive list, I didn't click through all pages, just tried to check the ones with custom components. Basically I would check anywhere that is using the grid, it will need to get updated.

**Comment by theiliad** [comment]
@tay1orjones are the modal & overflow menu styles not being applied?

image

**Comment by tay1orjones** [comment]
@alisonjoseph Thanks! Just pushed up a couple commits that should fix all those items.

@theiliad Yeah, it looks like charts is using `bx` prefixed classes. Once charts updates to use the new `cds` prefix it should be fixed. Let me know if I can help!

**Review by alisonjoseph — APPROVED** [review]
Looks good (other than the charts issue Elliad pointed out) 👍

**Comment by tay1orjones** [comment]
Note that the grid demo page is totally borked. I can't fix it until https://github.com/carbon-design-system/carbon/pull/10934 lands and is published (I'll cut a patch release for it ASAP). 

The demo grids have to be scoped with a prefix, which I can't do without having the grid code included twice. Including it twice breaks other things due to it being farther down in the cascade. 

Similar thing with the charts fix - it's reliant on updating an external dep.

Since this is merging into the `v11` branch, I'd like to get the bulk of these changes in and carry these two issues forward. I'll issue follow-up PRs for them individually.

**Comment by tw15egan** [comment]
Screen Shot 2022-03-10 at 1 06 36 PM


I believe we need to port over this fix

**Review by laurenmrice — APPROVED** [review]

**Comment by jnm2377** [comment]
Just some things I noticed:

- [ ] Feedback dialog styles are off. But this may be something we missed in GTC. I'm unsure.

Screen Shot 2022-03-10 at 1 47 47 PM

(how it should be)
Screen Shot 2022-03-10 at 1 48 07 PM


- [ ] In the homepage, the feedback dialog can't be opened at all, and it's opacity is less than 1 for some reason. 

Screen Shot 2022-03-10 at 1 48 39 PM

- [ ] some of the codesnippets that have file structures are no longer aligned. This feels nitpicky, sorry. But they're working correctly in the current site, so just wanna make sure we capture that somewhere to fix either now or later.

Screen Shot 2022-03-10 at 2 40 21 PM

Screen Shot 2022-03-10 at 2 00 09 PM

- [ ] Icon page and Pictogram page search bar is too small, and the dropdown has a dark line at the bottom now. The search bar sizing makes it so that you can see some of the content when you're scrolling.

Screen Shot 2022-03-10 at 2 47 19 PM

(when scrolling)
Screen Shot 2022-03-10 at 2 47 42 PM

(how it should be)
Screen Shot 2022-03-10 at 2 47 29 PM

**Comment by laurenmrice** [comment]
I noticed a couple of things:


**Community assets —> Component index page**
- [ ] The Tags are getting a background color behind them and the tooltips on hover have been enlarged. 
Screen Shot 2022-03-11 at 11 03 53 AM

**Guidelines —> Color page (Usage tab)**
- [ ] A drop shadow has been put underneath the content switcher. A drop shadow shouldn’t appear until the page scrolls and content switcher is on top of the table.
Screen Shot 2022-03-11 at 11 07 16 AM

**Guidelines —> Icons and Pictograms page (Library tab)**
- [ ] Tooltips have disappeared from the hoverable icon buttons to download and copy code. 

Screen Shot 2022-03-11 at 11 09 35 AM

**Comment by jnm2377** [comment]
A few more things:
- [ ] community index tag styles are off (it has a dark bg around it)

Screen Shot 2022-03-11 at 11 17 12 AM

- [ ] this actually seems like it might be an existing issue... when you're on the `Community assets` > `Component index` > `Contribute a component` tab, and you click the `Next` tile at the bottom of the page, it actually takes you to the `previous` as in the next and previous tile are both the same href.

Screen Shot 2022-03-11 at 11 18 08 AM

- [ ] the data viz color palette component no longer has a visible focus state in the content switcher, neither when you click or tab thru

(this PR)
Screen Shot 2022-03-11 at 11 19 46 AM
 
(how it should be)
Screen Shot 2022-03-11 at 11 19 53 AM

**Comment by tay1orjones** [comment]
We're going to continue to address the remaining issues (and any more we find!) in the next sprint. In the meantime I'd like to continue to have other folks work on documentation and migration updates that require the v11 styles be in `next`.

So I'm going to merge this as is so we don't impede the other workstreams happening in parallel. All the follow-up items outlined above to be fixed next sprint have been documented in https://github.com/carbon-design-system/carbon-website/issues/2785

If any new issues are encountered, update that issue. It can be our living list of items to address for now.

**Review by jnm2377 — APPROVED** [review]

**Comment by theiliad** [comment]
@tay1orjones, just cut out v`0.55.0` in charts. Using that should solve the charting issues, hopefully...

**Comment by tay1orjones** [comment]
@theiliad Thank you! That fixes the chart pages 🎉

**Pull request merged**
