### PR TITLE
Fixes inconsistent combobox description

### LINKED ISSUE #2008: Combobox description for filtering is inconsistent
## Summary
Combobox description about how keyboard input and filtering works is inconsistent.

## Relevant information

In the Universal Behaviours > [Interactions](https://www.carbondesignsystem.com/components/dropdown/usage#interactions) > Keyboard section of the Dropdown Usage page it says:

> **Combo box and filtering:**
> - When typing a character: focus stays on the field while an option in the menu is highlighted that best matches the typed character.

That is the behaviour observed when using the Live Demo.

In the [Combobox section](https://www.carbondesignsystem.com/components/dropdown/usage#combo-box) of the page it says:
> **Combo box**
> …
> The menu opens by clicking anywhere in the field and you can start typing to sort through the list of options. The options that start to match your entry remain in the list while other existing options are temporarily removed.

### PR DESCRIPTION
**Pull request by grahamharper**
Fixes #2008

Fixes documented description of combobox filtering behaviour

#### Changelog

**New**

- {{new thing}}

**Changed**

- Combobox usage docs page

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]

**Comment by janchild** [comment]
@laurenmrice I added you as a reviewer here as you worked on this one!

**Review by laurenmrice — APPROVED** [review]
Thanks for updating this! Looks good to me 👍🏻

**Comment by janchild** [comment]
@alisonjoseph would you mind looking at this PR? I'm not seeing the changes on the *Files changed* tab in the preview. Maybe something is amiss with the build? I'm not sure what to do and if the changes would go through correctly if I approved. Thank you!

**Comment by laurenmrice** [comment]
Oh yeah that is true, I am seeing the same thing! Weird.

**Comment by alisonjoseph** [comment]
Weird, I'm not seeing the changes in the preview url either, just triggered a rebuild to see if that fixes it. 🤔

**Comment by janchild** [comment]
> Weird, I'm not seeing the changes in the preview url either, just triggered a rebuild to see if that fixes it. 🤔

I still can't see the changes in the build. Any thoughts on what to do next, @alisonjoseph?

**Comment by tw15egan** [comment]
@janchild I'm guessing it's just a caching issue, the copy will be correct when it is deployed 👍

**Review by janchild — APPROVED** [review]

**Pull request merged**
