### PR TITLE
fix(code-snippet): fix accessbility duplicate header

### LINKED ISSUE #1595: audit-avt1-codesnippet: header id "overflow-content" already in use
## Environment:

> Operating system: Mac
> Browser: Chrome 
> AVT :one:
> Page: [Components - CodeSnippet: usage](https://www.carbondesignsystem.com/components/code-snippet/usage/)

## Detailed Description: 

The <h3> element has the id "overflow-content" that is already in use

Screen Shot 2020-08-20 at 1 51 12 PM

## What to do: 
For each element with an id attribute, provide a unique, non-empty value.

## Why is this important?
The id attribute provides a machine-readable identifier for the elements of the page. A unique value for id allows browsers and assistive technologies to interpret and parse the content accurately.

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #1595 

#### Changelog

adds a unique id for the `Overflow content` heading in the Code Snippet --> usage page

#### Testing 

- [ ] Checkout the Code snippet --> usage page
- [ ] Make sure you no longer see the error documented in the issue

### CODE REVIEW

**Review by tay1orjones — COMMENTED** [review]
No more error 🎉  but the url for this anchor/heading is:

`/components/code-snippet/usage#overflow-contentobject-objectobject-object`

Do we want this to be the case? Maybe we could just change the headings themselves to be "Multi-line overflow content" and "Single-line overflow content"? I know it's repetitive underneath the h2 section but would avoid the issue and be pretty clear.

**Comment by jnm2377** [comment]
@jillianhowarth would content be ok with the new headings Taylor suggested?
`Multi line overflow content` and `Single line overflow content`
Otherwise, I would be ok with this solution as a temp fix and maybe look into adding support for overriding url for headers in the gatsby theme.

**Comment by jillianhowarth** [comment]
Sorry I'm not sure why GitHub didn't tell me I was tagged in the comment 😕
I think `Multi-line overflow content` and `Single-line overflow content` are a good solution so the URLs make sense!

**Comment by jnm2377** [comment]
@tay1orjones @jillianhowarth it's ready for re-review

**Review by jnm2377 — APPROVED** [review]

**Review by jillianhowarth — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
