### PR TITLE
Vue tutorial

### PR DESCRIPTION
**Pull request by lee-chase**
Adds a view version of the carbon developer essentials.

# To do
- [x] Enable netify for https://github.com/carbon-design-system/carbon-tutorial-vue repository
- [x] Insert previews or use React versions of previews
- [x] Have reviewers check through the instructions
- [x] Move https://github.com/lee-chase/working-carbon-tutorial-vue branches over to https://github.com/carbon-design-system/carbon-tutorial-vue as necessary.
- [x] Fix previous and next navigation? May be part of a wider issue with tabs.

# Description
As part of the changes:
- Updates left nav to keep tutorial users on one track
- Moves tutorials from 'react-step-N/react-step-N.mdx' to 'step-N/react.mdx'.
- Moves overview.mdx to react.mdx
- Moves wraping-up.mdx to react.mdx
- Adds vue.mdx to overview, step-1, step-2, step-3, step-4, step-5 and wrapping-up.
- Adds a VUE.JS badge

#### Changelog

- M       src/components/LeftNav/LeftNavItem.js
- R090    src/content/tutorial/overview/overview.mdx      src/content/tutorial/overview/react.mdx
- A       src/content/tutorial/overview/vue.mdx
- R099    src/content/tutorial/react-step-1/react-step-1.mdx      src/content/tutorial/step-1/react.mdx
- A       src/content/tutorial/step-1/vue.mdx
- R100    src/content/tutorial/react-step-2/images/landing-layout.png     src/content/tutorial/step-2/images/landing-layout.png
- R100    src/content/tutorial/react-step-2/images/landing-r1-spacing.png src/content/tutorial/step-2/images/landing-r1-spacing.png
- R100    src/content/tutorial/react-step-2/images/landing-r1-type.png    src/content/tutorial/step-2/images/landing-r1-type.png
- R100    src/content/tutorial/react-step-2/images/landing-r2-spacing.png src/content/tutorial/step-2/images/landing-r2-spacing.png
- R100    src/content/tutorial/react-step-2/images/landing-r3-spacing.png src/content/tutorial/step-2/images/landing-r3-spacing.png
- R098    src/content/tutorial/react-step-2/react-step-2.mdx      src/content/tutorial/step-2/react.mdx
- A       src/content/tutorial/step-2/vue.mdx
- R097    src/content/tutorial/react-step-3/react-step-3.mdx      src/content/tutorial/step-3/react.mdx
- A       src/content/tutorial/step-3/vue.mdx
- R100    src/content/tutorial/react-step-4/images/DAP-violations.png     src/content/tutorial/step-4/images/DAP-violations.png
- R100    src/content/tutorial/react-step-4/images/info-layout.png        src/content/tutorial/step-4/images/info-layout.png
- R100    src/content/tutorial/react-step-4/images/info-spacing.png       src/content/tutorial/step-4/images/info-spacing.png
- R097    src/content/tutorial/react-step-4/react-step-4.mdx      src/content/tutorial/step-4/react.mdx
- A       src/content/tutorial/step-4/vue.mdx
- R095    src/content/tutorial/react-step-5/react-step-5.mdx      src/content/tutorial/step-5/react.mdx
- A       src/content/tutorial/step-5/vue.mdx
- A       src/content/tutorial/wrapping-up/images/carbon-badge-vue.png
- R091    src/content/tutorial/wrapping-up/wrapping-up.mdx        src/content/tutorial/wrapping-up/react.mdx
- A       src/content/tutorial/wrapping-up/vue.mdx
- M       src/data/navigation/navigation.json

### CODE REVIEW

**Comment by mattrosno** [comment]
@lee-chase once `carbon-website` has pulled in our new Gatsby theme, we'll be able to add file names to code snippets instead of using `<h5>`s. If contributing code snippet syntax highlighting fixes I'd reach out to @vpicone to see if that needs fixed in `carbon-website` or the Gatsby theme. https://gatsby-theme-carbon.now.sh/components/code-blocks

I understand the footer previous page and next page navigation isn't ideal, as this takes you from React step 1 to Vue step 1 to React step 2, etc. I spoke with @designertyler and @connor-leech, and the best course of action is to roll with it right now. You're correct that it's part of a wider issue. At some point we'll look into overall information architecture improvements that will address this.

Also, I think there's an opportunity to prevent duplicated tutorial content at the source level to help keep the tutorial's aligned over time.

**Comment by mattrosno** [comment]
@alisonjoseph can you review the left nav changes? How the left nav tutorial `href`'s are dynamic according to the current page's URL? (So if you're viewing a Vue tutorial page and go to the next step in the left nav, it stays on the Vue tutorial.)

I'm curious how a dynamic left nav affects SEO. Or, does Gatsby generate a full sitemap to ensure all tutorial pages are crawled regardless of the left nav's `href`'s.

Also, should this be a more generic enhancement so other pages that have framework page tabs (Getting started > Developers) is affected too.

**Comment by mattrosno** [comment]
@jeanservaas can you review the Vue badge here? https://deploy-preview-1838--carbon-website.netlify.com/tutorial/wrapping-up/vue

If anything needs touched up like the React badge, @kellychurchill probably wants the source for the badge application and @lee-chase would need the modified image with the white background. Thanks!

**Comment by alisonjoseph** [comment]
Hey @mattrosno is it just me or is it really slow switching between pages in the nav? Wondering if it does that locally also or if its just netlify?

**Comment by mattrosno** [comment]
@alisonjoseph, @connor-leech mentioned the same slow tutorial page switching. Maybe this approach doesn't work well with PRPL (pre-cache remaining routes, lazy-load and create remaining routes on demand)? https://www.gatsbyjs.org/docs/prpl-pattern/

**Comment by kellychurchill** [comment]
Looking good to me. 

Recommend that the the forward and back links get dynamically updated so that they route to the /react or the /vue step based on the tab selection. Stepping between each version for each step is overtaxing to the user.

**Comment by lee-chase** [comment]
@mattrosno @joshblack Is there config required to allow netlify to access github https://vue-step-4--carbon-tutorial-vue.netlify.com/#/repos?

Works locally with .env.local and on mybluemix it did until that started giving me a 403.

**Comment by mattrosno** [comment]
@lee-chase good call. I added an ENV variable with the same access token used in `carbon-tutorial`. I triggered a deploy but that might just be master, so next branch commit should use the new ENV variable?

**Comment by mattrosno** [comment]
Variable has name `VUE_APP_GITHUB_PERSONAL_ACCESS_TOKEN`.

**Comment by lee-chase** [comment]
Could we use framework-agnostic tokens where appropriate?

**Comment by lee-chase** [comment]
@alisonjoseph seems quicker to me this morning, not sure why.

**Comment by lee-chase** [comment]
@mattrosno @kellychurchill Do we want to stage the publishing of these? If not we need to sort out badging and probably remove the t-shirt offer.

**Comment by alisonjoseph** [comment]
@lee-chase still seems slow for me 😞

**Comment by kellychurchill** [comment]
@alisonjoseph and @lee-chase 
I can't access the preview - Netlify build failed

**Comment by alisonjoseph** [comment]
I just restarted the build 🙏

**Comment by lee-chase** [comment]
> @alisonjoseph and @lee-chase
> I can't access the preview - Netlify build failed

Timed out, no option to nudge other than adding a commit :-(

**Comment by alisonjoseph** [comment]
Still timing out

**Comment by lee-chase** [comment]
@vpicone @mattrosno Vue files are not supported by prism.

Options are: 
1. Create a WebsiteCodeSnippet group to bundle several code snippets as one block/copy.
2. Use the default, unhighlighted text which at least displays correctly.
3. Other?

I think option 2 is the best short term fix. Unless there are objections I'll do that for now.

**Comment by vpicone** [comment]
Option 2 seems okay, but I can think of a few more. I saw there’s an unofficial prism syntax for vue. Or we can modify the code snippet MDX component to use whatever syntax highlighting solution you want when the language is vue. You could also try some of the other language syntaxs to see if any are remotely better.

**Comment by vpicone** [comment]
Depending on the timeline for this it might be easier to engineer with the new code snippet component in the gatsby theme. I plan on migrating the site in earnest after the webinar today.

**Comment by lee-chase** [comment]
It might be interesting to try the unofficial syntax.

Vue single file components roughly speaking have three top level tags; template, script and style. The template tag contains HTML with angular like directives for loops, conditionals etc. The script tag contains javascript or typescript. The style tag contains SCSS in our case.

In most cases if I could have it render the start and end tag as HTML and the inner contents as per the language specifier it would be adequate.

**Comment by lee-chase** [comment]
@vpicone think I will leave it as is for now, vue update perhaps in future. The only oddity outside of the SCSS is the formatting seems to insist on a HTML tag and it's attributes sitting on one line.

```html
<repo-table
  :headers="headers"
  :rows="rows"
  title="Carbon Repositories"
  helperText="A collection of public Carbon repositories."
/>
```
producing

image

**Comment by kellychurchill** [comment]
Could we add a #3 to the  "To earn this badge" section? 

3. Complete the [badge application] -> link to the application section.

**Comment by lee-chase** [comment]
Added a #3 @kellychurchill but will presumably need a separate survey or switch for Vue.

**Comment by kellychurchill** [comment]
@lee-chase Yes - we will have a separate survey for Vue. I will have it ready today. 

Question - should the badge say "Vue.js" or "Vue"?

**Comment by lee-chase** [comment]
@kellychurchill I would go with "Vue.js" as that is how it tends to be written on the official site

https://vuejs.org/

**Comment by jeanservaas** [comment]
@mattrosno won't comment on the content, I'll defer to you on that, just a few minor visual things:


Both the React and the Vue tabs have this graphic ... can you either remove that all caps "LANDING PAGE" or if it has to be there...

current:
image

more consistent with our style for usage images:

image


can you put a break character after that src/App.vue to get a margin bottom -- so it's consistent with the others?

image

**Comment by jeanservaas** [comment]
Vue badge OK!

**Comment by jeanservaas** [comment]
@mattrosno 

Please use this artwork for the Vue badge in order to match the React badge. Thanks!

Vue_badge_revised

**Comment by lee-chase** [comment]
> @mattrosno won't comment on the content, I'll defer to you on that, just a few minor visual things:
> 
> Both the React and the Vue tabs have this graphic ... can you either remove that all caps "LANDING PAGE" or if it has to be there...
> 
> current:
> image
> 
> more consistent with our style for usage images:
> 
> image
> 
> can you put a break character after that src/App.vue to get a margin bottom -- so it's consistent with the others?
> 
> image

I think the mdx is correct. @mattrosno can you check.

P.S. I'm happy for this to go when others are ready.

**Comment by lee-chase** [comment]
> @mattrosno
> 
> Please use this artwork for the Vue badge in order to match the React badge. Thanks!
> 
> Vue_badge_revised

Done

**Comment by lee-chase** [comment]
@kellychurchill based on the updated ibmcloud deploy instructions I found the following.

1. I think we should be specific about mapping 'United Kington', 'US South', as listed in cloud foundry org spaces, etc to the api end oints.
2. I was unable to use the new endpoints, the response always came back as 'Invalid API Endpoint', instead I had to use the bluemix endpoint.
3. Perhaps as a result of messing about I also ended up setting api, org, and space via an 'ibmcloud target' command.
4. When I deploy (tried US South and United Kingdom) all appears well. Except I get '403 Forbidden' if I try to view the deployed page.

**Comment by lee-chase** [comment]
One last thing. 

The carbon website source prettier changes " for ' in javascript. Which is how I would tend to write my javascript. However, the default prettier/eslint settings for Vue projects tends to leave "". Should I? 

a) turn off prettier everywhere in the tutorial.
b) Update the package.json to use single quotes in script.

**Comment by mattrosno** [comment]
@alisonjoseph @vpicone looks like @lee-chase is ready for this to go live. @kellychurchill has reviewed the content by doing all 5 steps of the vue tutorial. Can you review this PR, specifically looking at changes to the components directory (the dynamic left nav for the tutorial)?

Also, how does the current migration to the Gatsby Theme affect merging this PR?

**Comment by vpicone** [comment]
@mattrosno those components were re-written in the gatsby theme and so the changes here won’t make it through to the migrated site without heavily shadowing. 

This is a big deviation in what tabs mean and how they’re used elsewhere in the site. Not sure it’s the beat decision from an information architecture standpoint. 

My recommendation is to take out the changes to the nav components and let the tabs operate like they do in the other pages with framework tabs. At least until we can figure out a better way to toggle into the preferred framework.

**Comment by vpicone** [comment]
Another thing to keep in mind is any changes to the paths here will result in a change in URL which will break any links we’ve sent out in social media/promos for the tutorial and individual steps.

**Comment by lee-chase** [comment]
> Why is there `carbon-badge-vue.png` in the src directory? Should that live in a tutorial subdirectory?

Moved the correct badge to the correct location.

**Comment by lee-chase** [comment]
> Another thing to keep in mind is any changes to the paths here will result in a change in URL which will break any links we’ve sent out in social media/promos for the tutorial and individual steps.

Existing links still default to the react (first) tab.

**Comment by lee-chase** [comment]
> @mattrosno those components were re-written in the gatsby theme and so the changes here won’t make it through to the migrated site without heavily shadowing.
> 
> This is a big deviation in what tabs mean and how they’re used elsewhere in the site. Not sure it’s the beat decision from an information architecture standpoint.
> 
> My recommendation is to take out the changes to the nav components and let the tabs operate like they do in the other pages with framework tabs. At least until we can figure out a better way to toggle into the preferred framework.

@alisonjoseph has indicated that she will assist with the migration of this content whether it lands before or after the new theme.

@kellychurchill and others have indicated that not being able to follow a path either via the side menu, tabs, prev or next is very jarring to the user.

**Comment by alisonjoseph** [comment]
I didn't realize there was a fundamental change to the way the navigation was handled in this PR. Those changes might have to be migrated over at a later time. 🤔

**Comment by lee-chase** [comment]
While the navigation behaviour does differ, it does behave as a user following a thread would want.

The limited evidence we gathered from users testing the tutorial suggested that not following a thread was very bad.

**Comment by alisonjoseph** [comment]
The navigation is all handled at the theme level now, we can shadow everything at the website level... but, yikes, not sure if we really want to do that. We will miss out on updates upstream possibly this way. 

I think the best option would be to add this functionality at the theme level, @vpicone thoughts on this??

**Comment by vpicone** [comment]
@lee-chase 
> > Another thing to keep in mind is any changes to the paths here will result in a change in URL which will break any links we’ve sent out in social media/promos for the tutorial and individual steps.
> 
> Existing links still default to the react (first) tab.

Are you sure? In your preview when I go to `/tutorial/react-step-1` (the old url) I get a 404.

**Comment by lee-chase** [comment]
> @lee-chase
> 
> > > Another thing to keep in mind is any changes to the paths here will result in a change in URL which will break any links we’ve sent out in social media/promos for the tutorial and individual steps.
> > 
> > 
> > Existing links still default to the react (first) tab.
> 
> Are you sure? In your preview when I go to `/tutorial/react-step-1` (the old url) I get a 404.

Apologies @vpicone you are correct, I forgot that I had renamed the folder.

Added re-directs which works great locally but in the netlify deploy displays the 404 before redirecting.

**Comment by lee-chase** [comment]
Attempted 404 flash fix did not work
https://github.com/carbon-design-system/carbon-website/pull/1838/commits/9215f87b6b4e90f8a3473d363b20b36866bba5e4

See Gatsby issue https://github.com/gatsbyjs/gatsby/issues/5329

**Comment by kellychurchill** [comment]
Not sure what's up with the Netlify preview link showing the build - but here's the direct link to the preview now: https://5d559785c49fb300093d9ca8--carbon-website.netlify.com/tutorial/react/step-1

@alisonjoseph and @vpicone thoughts?

**Comment by alisonjoseph** [comment]
Looks good! Would we prefer just having the numbers for the nav, so they "fit" better?

Screen Shot 2019-08-15 at 2 13 39 PM

**Comment by alisonjoseph** [comment]
Demo here - https://carbondesignsystem-git-fork-alisonjoseph-tutorial-nav.carbon-design-system.now.sh/tutorial/react/2

(this is the "new site w/ the theme)

**Pull request merged**
