### PR TITLE
fix: add white background back to images

### PR DESCRIPTION
**Pull request by alisonjoseph**
Updates token so that there should now be a white background behind usage page images

### Testing

Need to make sure this doesn't add a white background to images where it shouldn't

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
do you have a specific page or image we can check to confirm this is appearing correctly? I'm not sure off the top of my head which images already have backgrounds

**Comment by alisonjoseph** [comment]
Any of the usage pages for components should work.

**Review by aagonzales — APPROVED** [review]
🎉 Looks good!

**Comment by aagonzales** [comment]
Its actually most images on the style tab. Date Picker was the component I spotted it first.

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by johnbister — APPROVED** [review]

**Pull request merged**
