### PR TITLE
chore: update gatsby theme to 1.27.1

### PR DESCRIPTION
**Pull request by alisonjoseph**

### CODE REVIEW

**Comment by joshblack** [comment]
Seems like something is going on with a dependency and expected node version? 🤔

**Comment by vpicone** [comment]
@alisonjoseph it's not letting me push to your PR, can you run `yarn add -D -W node-fetch@next`

**Comment by vpicone** [comment]
@alisonjoseph woo! a different error...I can handle this one momentarily.

**Comment by vpicone** [comment]
@alisonjoseph could you add `icon: 'src/images/favicon.svg'` to the `gatsby-plugin-manfiest` options in the gatsby config file?

**Comment by alisonjoseph** [comment]
Thanks @vpicone!

**Review by vpicone — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Pull request merged**
