### PR TITLE
docs: added requested tooltip guidance/image

### LINKED ISSUE #1640: [Tooltip, website] Update tooltip page with new alignment options doc
Recently merged enhancements for tooltip. Now tooltip supports 3 alignment options: start, center, end (previously only center is available). This should be documented in Usage section: 
https://www.carbondesignsystem.com/components/tooltip/usage

Dev isseu: https://github.com/carbon-design-system/carbon/issues/2678
Design kit issue: https://github.com/carbon-design-system/carbon/issues/2768

### Position and alignment
Tooltip maybe positioned `top` or `bottom`, and aligned to `start`, `center` or `end`. Please connect with @laurenmrice for image assets.

### PR DESCRIPTION
**Pull request by connor-leech**
Closes #1640

This page was/remains pretty rough. I added requested guidance, and will hold off overhauling until we move on our Usage/templatizing project.

#### Changelog

**New**

- Added image from @laurenmrice 
- Added corresponding sentence about placement of tooltips

### CODE REVIEW

**Comment by connor-leech** [comment]
@shixiedesign I added the note about definition tooltip.

We've talked about adding contextual images throughout, so I think this is a good idea. In your experience, is a definition tooltip used more in UX copy like:

**Comment by shixiedesign** [comment]
Checking with other designers, @connor-leech, making you an image...

**Comment by shixiedesign** [comment]
Thanks for getting the definition tooltip image updated! @connor-leech  A few more proposed changes: 

- I just connected with Lauren to create new **Placement** images to better illustrate our guidance:
tooltip-usage-1-bottom
tooltip-usage-1-left-right
tooltip-usage-1-top

- for content under **Interactive tooltip**, how about below: 
> Interactive tooltips may contain rich text and other interactive elements like buttons or links. Please note that in general hiding interactive content in tooltip is discouraged. Approved example usage of interactive tooltip are for on-boarding experiences and product tours. 

- replacement image for **Interactive tooltip**: coming soon...

**Comment by shixiedesign** [comment]
I realize now that Github actually no longer allows anyone other than the author to edit a PR. I will hold off making changes next time and just wait for you to address the comments. This time round, I happen to be awake and did some work, so this PR migrated to:  https://github.com/carbon-design-system/carbon-website/pull/1688

**Pull request closed without merging**
