### PR TITLE
fix: grid alignment on typography page

### LINKED ISSUE #2637: Far right content should be on grid column
https://www.carbondesignsystem.com/guidelines/typography/expressive/

and

https://www.carbondesignsystem.com/guidelines/typography/productive

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #2637

Fixes grid alignment on typography page `/guidelines/typography/productive/` and `guidelines/typography/expressive

Screen Shot 2022-02-21 at 11 18 01 AM
`

### CODE REVIEW

**Review by aagonzales — CHANGES_REQUESTED** [review]
The grid looks good, but the padding is what's causing the right column to not sit right on the column edge. If we reduce the padding from 1.5 to 1rem there it should resolve the problem and everything would fit perfectly then! Or is this a separate issue type of thing?

**As-is**
image

**to be**
image

**Comment by aagonzales** [comment]
Also will these changes appear in the [v11 type page](https://v11.carbondesignsystem.com/guidelines/typography/type-sets) which has been changed some what from the v10 arrangement?

**Comment by alisonjoseph** [comment]
@aagonzales They _should_ 🙏 , after this is updated and merged I can do another sync between branches and make sure.

**Comment by mjabbink** [comment]
Excellent.

**Comment by alisonjoseph** [comment]
Just updated the padding @aagonzales
Screen Shot 2022-02-22 at 11 40 39 AM

**Review by aagonzales — APPROVED** [review]
🔥

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
