### PR TITLE
feat: add card layout to a11y status component

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes https://github.com/carbon-design-system/carbon-website/issues/3847
Closes https://github.com/carbon-design-system/carbon-website/issues/3850

Add Ally status to Usage component pages

#### Changelog

- Refactored and cleaned up some code in AllyStatus component. 
- Added layout prop to display either `card` or `table` view
- Reorder Usage pages to move demo to the top and add the Ally status cards below

### Review
Component Usage pages

https://carbondesignsystem-7uo0s6vpp-carbon-design-system.vercel.app/components/breadcrumb/usage/

Screenshot 2024-02-12 at 12 15 31 PM

Also ensure that all previous a11y status work (on overview page and component a11y pages) is still working correctly.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Just pushed an update for those ResourceCards to use `subTitle` instead of `title` (14px) @thyhmdo
 
Screenshot 2024-02-14 at 8 33 37 AM

**Review by thyhmdo — APPROVED** [review]
Love it!

**Review by guidari — APPROVED** [review]
LGTM!
Pages are working as expected  🚀

**Review by tw15egan — APPROVED** [review]
Awesome!

**Review by tay1orjones — APPROVED** [review]
It looks so good!

**Pull request merged**
