### PR TITLE
404 page

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon-website/issues/663

Adds in custom 404 page.

The repeating background is skipped for now and added an animation on the gradient. 

We still need to figure out why the site will not redirect to the 404 page, works fine locally.

To test, go to `/404`

screen shot 2019-01-31 at 1 29 38 pm

### CODE REVIEW

**Comment by tw15egan** [comment]
Looks like redirect is working, but now the sidebar color change isn't working. Will update and find a way to tell the nav bar if it is on the 404 page

**Comment by shixiedesign** [comment]
Hover of links now have to be `Blue 40` because it's against a dark background. Gotta make sure this local change won't affect the links on regular pages though. 
Current:
image

**Comment by alisonjoseph** [comment]
Can we pull this out in to the website-addons so I can use inn the ibm.com/design site?

**Comment by claycrenshaw** [comment]
Looks good! Could I suggest a tweak to the language?

IBM style says not to use exclamation points for negative messages. . . But we can have some fun with it, and make it a little more conversational. Maybe like. . .

Something's wrong here :(
Sorry, we can't find the page you're looking for. But maybe one of our most-visited pages will suit your fancy?

**Comment by tw15egan** [comment]
@alisonjoseph added!

**Comment by alisonjoseph** [comment]
🎉 thanks! looks good.

**Comment by alisonjoseph** [comment]
@tw15egan I started digging in to why the 404 page wasn't working and got as far as it having something to do with `<Layout>`. If you remove Layout then it works. No idea how to fix it, found a bunch of older gatsby issues related to it, but didn't really dig in to them. (you can test by removing layout, running `yarn build:external` and then `gatsby:serve` and checking a random url. (also confirmed identical behavior on /design site)

Obviously this is not ideal since we want the navigation on our 404 page, however we might have to do this as a temp fix for next week. 😭 

issuess possibly related? 😕 
https://github.com/gatsbyjs/gatsby/issues/2223
https://github.com/gatsbyjs/gatsby/issues/1838

**Comment by alisonjoseph** [comment]
never mind! update Gatsby to `2.0.107` and I think it fixes the issue 🙏

**Comment by alisonjoseph** [comment]
oh, this wasn't ready to merge. (I'll update gatsby in a separate PR though to actually make the 404 page work and publish the package)

**Pull request merged**
