### PR TITLE
video inside of WebsiteTabs padding fix

### LINKED ISSUE #1150: Motion page videos aspect ratio wrong
Motion page videos that are inside <do-dont-examples> and <tab> are displaying at the wrong aspect ratio. Large extra white space in left and right side of video.  
https://next.carbondesignsystem.com/guidelines/motion/basics

### PR DESCRIPTION
**Pull request by lovemecomputer**
Closes #1150 

prevent global video rule from affecting videos inside of `WebsiteTabs`

### CODE REVIEW

**Comment by jeanservaas** [comment]
Hey guys, @shixiedesign is out today so I was looking at this... I just read shixie's issue and don't see the fix:

(also made sure it wasn't a cache issue) Maybe I'm missing something.

image

image

**Comment by tw15egan** [comment]
I'm also still seeing the issue

**Comment by shixiedesign** [comment]
Looks like videos in `<tab>` are fixed! 🎉 Still seeing this issue in videos in `<do-dont-example>` though.

**Comment by marijohannessen** [comment]
I have it fixed in the do-dont-examples: https://github.com/carbon-design-system/carbon-website/pull/1166

**Comment by lovemecomputer** [comment]
@shixiedesign this is fixed now inside example components! will be visible when netlify finishes building

@marijohannessen — i have that fix here too, although we've done some different things with the Sass. in this PR i'm putting these overrides inside of `_page.scss`, alongside the global styles for `.gatsby-resp-iframe-wrapper`. wondering if you would like to follow this pattern, or if it would be better to follow your lead, and put these overrides for `.gatsby-resp-iframe-wrapper` inside of each component's Sass file that needs it.

(trying to think of best pattern for future maintainability as folks add new components—i also put up this issue for later discussion when releasing `website-addons`: https://github.com/carbon-design-system/carbon-website/issues/1167 @alisonjoseph )

**Comment by alisonjoseph** [comment]
@lovemecomputer @marijohannessen I had to create a new `<Video/>` component in my mdx PR, so eventually we can move styles there

**Pull request merged**
