### PR TITLE
update carbon-charts version/add new demos

### PR DESCRIPTION
**Pull request by natashadecoste**
on draft **waiting for content/guidance on using circles packs**

#### Changelog

**New**

- circle pack card on chart-types page
- added circle pack svg 
- circle pack guidance under /complex-charts (waiting for final copy)

### CODE REVIEW

**Review by theiliad — APPROVED** [review]
Other than the copy needed, looks good 👍🏻

**Comment by natashadecoste** [comment]
> I have read the DCO document and I hereby sign the DCO.

**Comment by theiliad** [comment]
recheck

**Comment by natashadecoste** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by jeanservaas — COMMENTED** [review]
For some reason the demo on the site is pulling in dark theme tooltips

image

In the Carbon G100 theme if you're using the $disabled-02 token, the value for is **Gray 70**, not Gray 30. That token is what we should be using here.

Token reference:
https://www.carbondesignsystem.com/guidelines/color/usage

image

**Comment by natashadecoste** [comment]
Here are the different themes with the $disabled-02
Looks a lot better I think... 
image
image
image
image

**Comment by motou** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by grahamharper** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by Arihant25** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by emyarod — APPROVED** [review]
looks good to me pending content and visual review

**Review by tay1orjones — APPROVED** [review]
same. looks good to me pending content and visual review

**Review by jeanservaas — APPROVED** [review]
Let's merge this

**Review by jillianhowarth — APPROVED** [review]

**Pull request merged**
