### PR TITLE
feat(project): enable gatsby feature flags

### PR DESCRIPTION
**Pull request by joshblack**
This PR takes the opportunity to enable some feature flags to also update some dependencies on react, gatsby, and other related packages in the ecosystem.

#### Changelog

**New**

**Changed**

- Update dependencies for the project, namely react and gatsby
- Update `gatsby-config.js` with feature flags to help speed up initial dev server and incremental rebuilds

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
Note for content reviewers: seems like the files got formatted with prettier 👀

**Review by vpicone — APPROVED** [review]
Woo!

**Review by tw15egan — APPROVED** [review]
Works well for me 👍 ✅

**Review by emyarod — APPROVED** [review]

**Comment by andreancardona** [comment]
@joshblack is this still something we need to merge or not anymore?

**Pull request closed without merging**
