### PR TITLE
fix tooltip style override issues in charting demos

### LINKED ISSUE #2302: All charting tooltips are broken - style override
**Demo:**
https://www.carbondesignsystem.com/data-visualization/simple-charts/#bar-(floating)

image

I believe this is because of this override
image

### PR DESCRIPTION
**Pull request by theiliad**
Closes #2302

### CODE REVIEW

**Comment by theiliad** [comment]
@emyarod could you pls review this PR? It overrides a change you pushed last week and I want to make sure that your intended functionality also isn't broken by the change in my PR.

Also, are we able to add `bx` to the rest of your added styling overrides?

**Comment by emyarod** [comment]
off the top of my head I think this should be fine, but I will need to check if any of the other tooltip variants are affected by this

**Comment by theiliad** [comment]
> off the top of my head I think this should be fine, but I will need to check if any of the other tooltip variants are affected by this

ok, lmk pls, and if we can, let's add `bx` to the rest of the styles that you added last week, hopefully in a separate PR

**Comment by emyarod** [comment]
the other styles were following the precedent set in the existing selectors, which AFAIK is to avoid hard coding the prefix. would it be safer to just ignore `--cc--tooltip` instead of targeting `bx--tooltip`?

**Comment by theiliad** [comment]
> the other styles were following the precedent set in the existing selectors, which AFAIK is to avoid hard coding the prefix. would it be safer to just ignore `--cc--tooltip` instead of targeting `bx--tooltip`? (although I don't mind hard coding the prefix for all of the selectors)

Could be, however that doesn't future proof the work, does it? E.g. I see you have modal in there, charts will soon use the Carbon Components' modal component, which could again cause some collisions here. Haven't checked that example yet but just something to keep in mind

**Review by emyarod — APPROVED** [review]

**Comment by emyarod** [comment]
yeah it would be good to know which components you are using/will be using, and I think we can increase the specificity of the selectors as needed. it may not be just adding the prefix across the board since it looks like many of the selectors are matching against suffixes

**Comment by theiliad** [comment]
> yeah it would be good to know which components you are using/will be using, and I think we can increase the specificity of the selectors as needed. it may not be just adding the prefix across the board since it looks like many of the selectors are matching against suffixes

I'm wondering why we'd prefer not to use the Carbon prefix when addressing styles? That'd be the safest path IMO, since Carbon Charts also adds its own prefix to styles (e.g. `bx--cc--tooltip`), that way we'll know for sure that we won't collide

**Comment by emyarod** [comment]
I was looking back at the original commits that started using those kinds of attribute selectors and couldn't exactly tell why (#1111), but I assume it had to do with the uncertainty around keeping the `bx` prefix going forward

**Comment by theiliad** [comment]
> I was looking back at the original commits that started using those kinds of attribute selectors and couldn't exactly tell why (#1111), but I assume it had to do with the uncertainty around keeping the `bx` prefix going forward

we could easily import the prefix from Carbon rather than hardcoding it, that way whatever it changes to, we support that.

Nowhere in the Carbon Charts' styles is bx hardcoded, we just do this:

`@import './vendor/@carbon/type/scss/prefix';`

```scss
svg.#{$prefix}--#{$charts-prefix}--chart-svg {
	overflow: visible;
}
```

**Comment by emyarod** [comment]
yeah I was only referencing the website styles which target some attributes with specific suffixes rather than specifying further, like how this current PR is moving from selecting `--tooltip` suffixed attributes to `bx--tooltip` suffixed attributes

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
