### PR TITLE
chore(tutorial): update tutorial steps based on updated content

### PR DESCRIPTION
**Pull request by tw15egan**
Updates the steps based on changes made in the tutorial updates. Can be merged when the tutorial PR's have been merged

Closes https://github.com/carbon-design-system/carbon-website/issues/2039
Closes https://github.com/carbon-design-system/carbon-website/issues/2040

### CODE REVIEW

**Comment by mattrosno** [comment]
Reviewing now against:

**Comment by mattrosno** [comment]
Reviewing now against:

- [ ] https://github.com/carbon-design-system/carbon-tutorial/pull/6447
- [ ] https://github.com/carbon-design-system/carbon-tutorial/pull/6446
- [ ] https://github.com/carbon-design-system/carbon-tutorial/pull/6448
- [ ] https://github.com/carbon-design-system/carbon-tutorial/pull/6464
- [ ] https://github.com/carbon-design-system/carbon-tutorial/pull/6467

**Comment by mattrosno** [comment]
@tw15egan when doing step 1 with these instructions against #6447 as the starting point, here's my PR: https://github.com/carbon-design-system/carbon-tutorial/pull/6519

I anticipate the number of files changes will be significantly smaller after you merge 6447.

Can you look into my PR's CircleCI errors to see if that's expected or not?

**Comment by tw15egan** [comment]
Stale lockfile, try running `rm -rf .yarn-offline-mirror node_modules && yarn cache clean && yarn install`

**Comment by mattrosno** [comment]
@alisonjoseph @tw15egan here are issues that I opened from doing step 1:

- https://github.com/carbon-design-system/carbon-website/issues/2039
- https://github.com/carbon-design-system/carbon-tutorial/issues/6515
- https://github.com/carbon-design-system/carbon-tutorial/issues/6516
- https://github.com/carbon-design-system/carbon-tutorial/issues/6520

**Comment by mattrosno** [comment]
> Stale lockfile, try running `rm -rf .yarn-offline-mirror node_modules && yarn cache clean && yarn install`

Trying that now.

@tw15egan is this anything that you need to fix in your PR in updating step 1? Or how do we prevent this? In this PR, I started with a fresh fork, and fresh local working directory.

**Comment by tw15egan** [comment]
It's because the one that is on the `react-step-1` branch that you are trying to merge into has a different lockfile and resolutions, since my changes have not been merged yet. This was the main reason I wanted to update the tutorial, but we're going to run into it until we merge my changes

**Comment by mattrosno** [comment]
@tw15egan updating lockfile and pushing to branch fixed the CI error and mergify auto ran again passing the step. https://github.com/carbon-design-system/carbon-tutorial/pull/6519

**Comment by mattrosno** [comment]
Bugs found in doing step 2:

- https://github.com/carbon-design-system/carbon-website/issues/2040

@tw15egan can you look into the Netlify error when me doing step 2? https://github.com/carbon-design-system/carbon-tutorial/pull/6527

image

This is after doing a `rm -rf .yarn-offline-mirror node_modules && yarn cache clean && yarn install` in my step 2 PR just in case.

**Comment by tw15egan** [comment]
@mattrosno can just hit `deploy cache and redeploy` and it should work, guessing this is again due to the cached lockfiles being out of sync

**Comment by mattrosno** [comment]
@tw15egan my step 3 PR has CI and Netlify errors: https://github.com/carbon-design-system/carbon-tutorial/pull/6528

I'm running `rm -rf .yarn-offline-mirror node_modules && yarn cache clean && yarn install` prior to committing.

**Comment by mattrosno** [comment]
@tw15egan I think you'll want to run `yarn format` in your 5 carbon-tutorial PRs that you plan on merging. This is doing step 4. It looks like `src/index.js` can from the starting branch - I didn't edit it during step 4 - yet formatting was off.

```
rosbookibm-8028:carbon-tutorial mattrosno$ yarn ci-check
yarn run v1.15.2
$ yarn format:diff
$ prettier --list-different "**/*.{js,md,scss}"
src/index.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rosbookibm-8028:carbon-tutorial mattrosno$ yarn format
yarn run v1.15.2
$ prettier --write "**/*.{js,md,scss}"
.github/CODE_OF_CONDUCT.md 51ms
.github/CONTRIBUTING.md 45ms
.github/ISSUE_TEMPLATE/bug_report.md 35ms
.github/ISSUE_TEMPLATE/feature_request.md 13ms
.github/ISSUE_TEMPLATE/question.md 11ms
.github/PULL_REQUEST_TEMPLATE.md 9ms
.github/SUPPORT.md 9ms
README.md 29ms
src/App.js 36ms
src/app.scss 42ms
src/App.test.js 14ms
src/components/Info/_info.scss 22ms
src/components/Info/index.js 6ms
src/components/Info/Info.js 17ms
src/components/TutorialHeader/_tutorial-header.scss 7ms
src/components/TutorialHeader/index.js 6ms
src/components/TutorialHeader/TutorialHeader.js 15ms
src/content/LandingPage/_landing-page.scss 15ms
src/content/LandingPage/_mixins.scss 9ms
src/content/LandingPage/_overrides.scss 9ms
src/content/LandingPage/index.js 7ms
src/content/LandingPage/LandingPage.js 24ms
src/content/RepoPage/_repo-page.scss 7ms
src/content/RepoPage/index.js 6ms
src/content/RepoPage/RepoPage.js 41ms
src/content/RepoPage/RepoTable.js 21ms
src/index.js 11ms
src/index.scss 11ms
src/serviceWorker.js 27ms
src/setupTests.js 9ms
✨  Done in 1.50s.
```

**Comment by mattrosno** [comment]
A screenshot so you can see how `src/index.js` needed formatting:

image

image

**Comment by tw15egan** [comment]
@mattrosno looks like the enzyme adapter we use requires react 16, so going to bump that back down. Should pass tests now.

**Comment by mattrosno** [comment]
@tw15egan I got through step 4 just fine. Step 5 maybe that same Netlify error? https://github.com/carbon-design-system/carbon-tutorial/pull/6531

**Review by mattrosno — APPROVED** [review]
I completed steps 1 - 5 yesterday with this deploy preview against @tw15egan's carbon-tutorial PRs that haven't been merged yet. The updates here look good!

https://github.com/carbon-design-system/carbon-tutorial/pulls?q=author%3Amattrosno

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by tw15egan** [comment]
I plan on merging this Friday in sync with the tutorial repo updates

**Review by dakahn — APPROVED** [review]

**Pull request merged**
