### PR TITLE
Fix broken link to React storybook for fixed sidenav

### PR DESCRIPTION
**Pull request by samrobbins85**
#### Changelog

**Changed**

- Changed link to react storybook for fixed sidenav as it was broken

### CODE REVIEW

**Comment by samrobbins85** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by samrobbins85** [comment]
recheck

**Review by tay1orjones — APPROVED** [review]
Thanks for catching this!

**Review by aagonzales — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
