### PR TITLE
update the team page members

### PR DESCRIPTION
**Pull request by theiliad**
adds additional team members to the `all-about-carbon/the-team/` page

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
🚀 🎉  👍🏻 ✅

**Review by tay1orjones — APPROVED** [review]

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
We need to look at the organization of this page if we're adding people not on the core team. (Also we will want names alphabetical)

**Comment by theiliad** [comment]
> We need to look at the organization of this page if we're adding people not on the core team. (Also we will want names alphabetical)

sure, what can I do @alisonjoseph, should I re-org the page to be in alphabetical order?

**Comment by jeanservaas** [comment]
@theiliad I'm going to go ahead and tweak these images. I think there are two options for the page organization

- Put the new additions in alphabetical order and add a descriptor (like Carbon Charts) that gives users a little more information about what you guys do

OR

- Have a separate section for Carbon Charts

@janchild what do you think?

**Comment by jeanservaas** [comment]
Here are the updated images @theiliad — they look a lot closer to the others, but I can only do so much with the lower resolution. Should be fine though. I'll talk to @janchild on Monday and decide where we want to put you guys.

[charts_team_imgs.zip](https://github.com/carbon-design-system/carbon-website/files/6410693/charts_team_imgs.zip)

**Comment by theiliad** [comment]
deploy preview  still building
image

**Review by alisonjoseph — APPROVED** [review]
🚀

**Review by janchild — APPROVED** [review]

**Pull request merged**
