### PR TITLE
chore(elements): update elements for font hotfix

### PR DESCRIPTION
**Pull request by joshblack**
Closes https://github.com/carbon-design-system/carbon-website/issues/762

Update elements dependencies for font hotfix in: https://github.com/IBM/carbon-elements/pull/301

#### Changelog

**New**

**Changed**

- Elements packages are now on `alpha.31`

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
cc @mjabbink if you have a chance to verify that italics are no longer the forced variants 👍

**Comment by alisonjoseph** [comment]
Italic text looks identical on live site and preview link. 
screen shot 2019-01-28 at 6 34 24 pm

**Comment by mjabbink** [comment]
those italics in above screen grab comparison are both forced italics

**Comment by mjabbink** [comment]
Also on Typography page in this section:

screen shot 2019-01-28 at 8 19 07 pm

**Comment by alisonjoseph** [comment]
@joshblack I'm not setting the font family anywhere, is this because I'm still pulling in v9 Carbon experimental and not v10 alpha?

**Comment by joshblack** [comment]
@alisonjoseph yeah, I believe the reset from type sets the font family but it's most likely being overwritten by the carbon styles.

https://github.com/IBM/carbon-elements/blob/master/packages/type/scss/_reset.scss#L18-L25 in the reset, but we could totally isolate the styles using the `font-family` mixin so that the font families match: https://github.com/IBM/carbon-elements/blob/master/packages/type/scss/_font-family.scss#L16

**Comment by alisonjoseph** [comment]
fyi 🎉 
screen shot 2019-01-29 at 3 34 08 pm

**Comment by mjabbink** [comment]
yes!

**Comment by mjabbink** [comment]
:muscle-ltr-270:

**Pull request merged**
