### PR TITLE
fix(syntax): update font-family

### PR DESCRIPTION
**Pull request by joshblack**
Update from carbon-components v9 ibm-plex-mono to IBM Plex Mono.

#### Changelog

**New**

**Changed**

- Update `syntax.css`

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
cc @vpicone

**Comment by vpicone** [comment]
It might be worth adding it to our Prism theme as well: https://github.com/carbon-design-system/carbon-website/blob/99655eec06ec84e8f6684615c5b2ca9d1f314491/src/styles/prism.css#L11

**Comment by alisonjoseph** [comment]
FYI, just updated this to master branch. we aren't using v10 anymore

**Comment by vpicone** [comment]
So looks like this might be resolved then?

**Pull request merged**
