### PR TITLE
comment out toolbar for datatable until done

### PR DESCRIPTION
**Pull request by alisonjoseph**

### CODE REVIEW

**Comment by designertyler** [comment]
@jnm2377 We don't need the pagination and small examples right now either, right?

**Comment by jnm2377** [comment]
Oh yeah we haven't added the small styles so we should comment that one out too. Pagination data table is just pulling in styles from pagination so that one's ok to include.

**Comment by jnm2377** [comment]
If we wanted to hide the actual toolbar in the data tables though, is that something that we have to do in the carbon-components repo or could we remove it from the html here? I can open up a PR if need be.

**Comment by alisonjoseph** [comment]
I commented out the small one, @jnm2377 the data table is pulling html directly from carbon-components. Is there a version without the toolbar?

**Comment by jnm2377** [comment]
ah, no, the configs have a toolbar from v9, I can submit a PR to remove the toolbar from the examples in that repo. 👍

**Pull request merged**
