### PR TITLE
fix: put comma inside quotes

### PR DESCRIPTION
**Pull request by xylish7**
Closes :

- https://zenhub.ibm.com/app/workspaces/-bsxd-master-workspace-5d5fd4b90c9aa55544db8833/issues/brand/bxd/95

### Changelog

**Changed**

- Fixed misplaced commas of https://www.carbondesignsystem.com/guidelines/motion/choreography

### CODE REVIEW

**Comment by xylish7** [comment]
@janchild I was told by @vpicone to replicate this [PR](https://github.com/carbon-design-system/design-language-website/pull/581#issuecomment-647797525) here. The decision to make this doesn't belong to me, but to the copywriter of the design-language-website, where this change was also made.

**Comment by vpicone** [comment]
Oh interesting! Perhaps we should revert the IDL change. @xylish7 can you show your content author/designer @janchild's comment here? If they still want to diverge, that's their prerogative, but we should inform them it's counter to IBM style.

**Comment by xylish7** [comment]
Sure! I gave her the link to this issue and waiting for her response.

**Comment by mjabbink** [comment]
@vpicone I think @janchild is correct and the styling should stay as it was with the comma outside the quote in this case.

**Comment by vpicone** [comment]
@xylish7 great! going to close this for now

**Comment by mjabbink** [comment]
but this was executed as far as I can see and needs to revert.

**Comment by vpicone** [comment]
@mjabbink this PR is in the carbon website repo, it wasn't merged here. The one that'll be reverted is in IDL.

**Pull request closed without merging**
