### PR TITLE
[WIP] Motion content

### PR DESCRIPTION
**Pull request by lovemecomputer**
ref https://github.com/carbon-design-system/carbon-website/issues/508

### CODE REVIEW

**Comment by lovemecomputer** [comment]
ooop my local repo wasn't building after merging in the latest changes from v10, so i went branched off from a previous commit to get this PR for content. (either that or it's bc v10 doesn't incorporate those commits from the other branch?) will verify or resolve this all before merge!

**Comment by alisonjoseph** [comment]
.example-content needs a `width: 100%;` to fix the hidden images.

the images inside the tabs are getting cut off, did you pull these from the box folder? Sync up with @claycrenshaw and @shixiedesign on what images go inside the tabs, I think they should be in the box folder in the issue.

**Comment by lovemecomputer** [comment]
@alisonjoseph i have a separate PR up addressing the CSS fixes here: https://github.com/carbon-design-system/carbon-website/pull/779 , but i can just include those fixes into this PR if you prefer! it would def make this preview easier

also yeah, the images i'm getting from the Box folder are what you see here, and there aren't many assets available. i'm prepping all the markup to hand off to @claycrenshaw / @shixiedesign so they can plug in final assets!

**Comment by shixiedesign** [comment]
Thanks @lovemecomputer!! So glad to see this coming together. I can certainly help with putting in the final assets. It's probably gonna be easier since I know the content & videos well. Let me know when I should start doing it. Looks like you still have WIP tag on this so I am waiting.

**Pull request merged**
