### PR TITLE
update: add text error token and update support token 01

### LINKED ISSUE #810: [token] add new $text-error token to color usage page
Add new token `text-error` to color usage page on the website.

Screen Shot 2020-01-20 at 12 20 18 PM

### PR DESCRIPTION
**Pull request by xxxle0**
Closes #810

+ add text-error token
+ update support token 01

### CODE REVIEW

**Comment by vpicone** [comment]
What is text-06 coming from?

**Comment by xxxle0** [comment]
Yep.

**Comment by xxxle0** [comment]
I think add a new token text-06 with role error text better than add text-error token. How do you think ?

**Comment by xxxle0** [comment]
ok @laurenmrice

**Comment by xxxle0** [comment]
@vpicone please merge it. Thanks.

**Pull request merged**
