### PR TITLE
docs: partners and advisory board updates

### LINKED ISSUE #2529: Updates for “Advisory board” page
- [x] Remove Phil

- [x] Add “Katrina Alcorn” portrait, title

Title:
General Manager of Design

K portrait crop

- [x] Update Mike’s title to “Executive Creative Director, Design, IBM Distinguished Designer”

- [x] Add Tessa Rodes portrait

- [x] Add Nigel Prentice portrait

### PR DESCRIPTION
**Pull request by laurenmrice**
Closes #2529 

**Changelog**

**New**

- Katrina Alcorn photo and title

**Changed**

- Mike Abbink title
- Tessa Rodes photo
- Nigel Prentice photo

**Removed**
- Phil Gilbert photo and title

----
**Testing**
- Go to `All about Carbon`  --> `Partners` 
- Look for new, changed, and removed updates on this page

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by mjabbink** [comment]
@laurenmrice You can you

- [ ]  remove DPO after Katrina’s title and replace with “Cloud and Cognitive Software”

- [ ]  remove “IBM” in front Cloud and Cognitive Software for Arin Bhowmick. This way all those are treated the same on the page.

**Comment by mjabbink** [comment]
@laurenmrice Sorry. I realized Doug’s position is not updated either. 

Doug Powell
Vice President, Design Program Office
Cloud and Cognitive Software


`update (see if this fits)`
Sarah Brooks
Director, Design, Design Program Office, IBM Distinguished Designer

**Comment by mjabbink** [comment]
@laurenmrice Looks good to me.

**Pull request merged**
