### PR TITLE
fix(grid-demo): bg color and full-bleed demo spacing

### PR DESCRIPTION
**Pull request by jnm2377**
Rel: https://github.com/carbon-design-system/design-language-website/issues/849

**Changed**

- changes bg color token for grid demo
- adds styles to remove unnecessary padding for full-bleed demo (padding between demo and code snippet)

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
built and tested locally, looks good to me. preview is not building and github CI doesn't seem to have run correctly though

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Review by jeanservaas — COMMENTED** [review]
Hey guys, looks good on IDL, but the Carbon typography overview page is still wonk

image

**Comment by jnm2377** [comment]
@jeanservaas that'll have to be fixed in the IDL repo. It's a custom component on that website.

**Comment by jnm2377** [comment]
@jeanservaas I'm not seeing that bug on the IDL site tho. Have you cleared your cache? https://www.ibm.com/design/language/typography/type-specs-ui It has a bg color for me.
Screen Shot 2021-01-26 at 4 25 08 PM

**Comment by jnm2377** [comment]
ohhh wait jk. I read your comment wrong. You meant this page: https://www.carbondesignsystem.com/guidelines/typography/overview Gotcha! Ok, will add a fix in this PR. Sorry for the confusion.

**Comment by jnm2377** [comment]
@jeanservaas done!

**Comment by jnm2377** [comment]
@jeanservaas is this ok to merge?

**Review by alisonjoseph — APPROVED** [review]
confirmed the typography page looks good now after latest update 👍

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
