### PR TITLE
docs(dataviz): add histogram

### PR DESCRIPTION
**Pull request by theiliad**

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]

**Comment by mjabbink** [comment]
Nice!

**Review by andreancardona — APPROVED** [review]
🎉

**Comment by theiliad** [comment]
Visual review was done mainly with the carbon-charts PR

**Comment by mjabbink** [comment]
@jeanservaas

**Review by jnm2377 — APPROVED** [review]

**Comment by mjabbink** [comment]
@theiliad @jeanservaas approved. Go to the glass!

**Pull request merged**
