### PR TITLE
Update link for github tutorials

### PR DESCRIPTION
**Pull request by mariuszmickiewicz**
Previous link gives 404

### CODE REVIEW

**Comment by mariuszmickiewicz** [comment]
I have read the DCO document and I hereby sign the DCO.

recheck

**Comment by mariuszmickiewicz** [comment]
recheck

**Comment by mariuszmickiewicz** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by alisonjoseph — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
