### PR TITLE
fix: title on AI component cards

### LINKED ISSUE #4283: [AI] Component names not displaying on the AI component list cards
## Detailed description
- [ ] Fix the component names so they are displayed on the [AI component list cards.](https://carbondesignsystem.com/guidelines/carbon-for-ai/#component-list) in the same way they appear on the [Components' overview page](https://carbondesignsystem.com/components/overview/components/#components).
    >

    > Screenshot 2024-09-24 at 3 35 18 AM

- It appears that the names are included in the code, but they are not showing up for some reason.
   > Screenshot 2024-09-24 at 6 46 45 PM
   > (Code snippet)

**Note: This issue might require assistance from a developer.**

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #4283

#### Changelog

- update to correct prop names so title shows up on AI component cards

### CODE REVIEW

**Review by Kritvi-bhatia17 — COMMENTED** [review]
Hi @aagonzales, could you please confirm whether the font size here should be 12px to match the Components’ Overview cards, or should it be 14px?

image


@alisonjoseph thanks for fixing this so quickly! Although not directly related to this issue, just wanted to confirm with you—are these ImageCards responsive? 🤔

**Comment by alisonjoseph** [comment]
@Kritvi-bhatia17 @aagonzales ah yea they are different font sizes. The AI page is using the ImageCard from the gatsby theme https://gatsby-theme-carbon.vercel.app/components/ImageCard/

Where the component overview page is a custom component built just for our website.

and yes they should be responsive by default

**Comment by aagonzales** [comment]
@Kritvi-bhatia17 @alisonjoseph I think its fine that they are different font sizes since they wont be seen together on the same page. I don't think its worth doing any extra work or customization just for that.

**Review by Kritvi-bhatia17 — APPROVED** [review]
Got it, thanks @alisonjoseph & @aagonzales for the confirmation!
LGTM 🚀

**Review by ariellalgilmore — APPROVED** [review]

**Pull request merged**
