### PR TITLE
docs: add new content guidance sections

### PR DESCRIPTION
**Pull request by tomwaterton**
This PR is related to issue #602 

- This overhauls the old, limited content guidance that was available, and introduces much more content guidance. 

**New**
On the Guidelines > Content page: 
- Adds a new "Punctuation" tab 
- Adds a new "Capitalization" tab 
- Adds a new "Numbers" tab
- Adds a new "UI labels" tab 

**Removed**
- Removed the former "Guidance" tab (as the content of that is now present in the other tabs.

### CODE REVIEW

**Comment by tomwaterton** [comment]
Related: #602

**Comment by tomwaterton** [comment]
This new commit adds a "Numbers" section to the Content guidelines.

**Comment by tomwaterton** [comment]
@janchild and @connor-leech - apologies that this is quite a large PR to review! But I have now finished adding the agreed additional content guidance from my voice and tone guide into the Carbon Content page.

As discussed, for now I've had to add more tabs, which I know is not really ideal. 
However, this PR means that all of the content guidance is now in Carbon, and as and when new/improved page navigation is available in Carbon, we can re-structure the content accordingly (i.e. to avoid the use of lots of tabs).

**Comment by cwgormanIBM** [comment]
@tomwaterton Thanks for putting this together; this PR helps clarify some questions we had.

Question regarding this:
>When you refer to a UI element, use the same capitalization as used in the UI.

Your example from https://github.com/carbon-design-system/carbon/issues/1566#issuecomment-567509469:
>To view more detailed information, click the Status tab.

What should this look like if the tab name is multiple words? For example, "Network status"? Would it be 
>To view more detailed information, click the Network status tab.

 or 

>To view more detailed information, click the Network Status tab.

or something like 

>To view more detailed information, click the **Network status** tab.

Thanks.

**Comment by tomwaterton** [comment]
HI @cwgormanIBM 

The Carbon guidance regarding capitalization of text in UIs is this:

> Use sentence-style capitalization in text and for all text elements in the UI except for proper nouns. Sentence style capitalizes only the first word of each sentence. 
> (Source: [Carbon capitalization guidance](https://www.carbondesignsystem.com/guidelines/content/guidance#capitalization))

Regarding your question:
> What should this look like if the tab name is multiple words? For example, "Network status"?

Answer: As **all** UI text should use sentence case capitalization, the correct capitalization is:
> To view more detailed information, click the Network status tab.
(Based on the fact that the tab in the UI should be labeled "Network status".)

Whether our docs opt to render references to UI text labels in bold font (i.e. "...click the **Network status** tab") or not is a visual design matter not related to our capitalization guidance. 

For what it's worth, I'll mention that I recently added some further details and examples to the capitalization guidance. These are contained in this PR604, which hasn't been reviewed yet, but here is a screengrab from my local build, which hopefully makes things clearer: 

Screenshot 2019-12-23 at 11 46 06

**Comment by vpicone** [comment]
I have a couple issues with the block quotes at the top of the pages.

1. I'm not sure how I feel about the substance of the quotes. They feel sort of flippant/silly. This one in particular feels a little tone-deaf...

	> “Every time you use an apostrophe to make a word plural, a puppy dies.”

2. On the design side of things, I think we'll need approval for this use of the block quote. It looks off when not surrounded by text.

	Screen Shot 2020-02-06 at 6 56 33 PM

**Comment by janchild** [comment]
@tomwaterton, I'm closing the PR for now but will pull from your contributed content as we work on each section. Thank you very much for all of this great work! Much appreciated.

**Pull request closed without merging**
