### PR TITLE
chore: sync `v11` branch with `main`

### PR DESCRIPTION
**Pull request by emyarod**
This PR syncs the latest changes on `main` with the `v11` branch and runs the format command to clean up unformatted files

also incorporates fixes from #2398

Confirm the following PRs are ok to merge from `main` to `v11`

- #2361
- #2294
- #2335
- #2365
- #2371
- #2362
- #2392
- #2400

### CODE REVIEW

**Comment by emyarod** [comment]
DCO check is failing because #2349 and #2351 were merged before the DCO was signed

**Comment by vpicone** [comment]
@emyarod I messaged @mjabbink

**Comment by mjabbink** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by joshblack — APPROVED** [review]

**Review by jillianhowarth — APPROVED** [review]

**Pull request merged**
