### PR TITLE
Fix broken link to gutter mode guidelines

### PR DESCRIPTION
**Pull request by crlordan**
#### Changelog

**Changed**

- Updated link to gutter modes (/elements/2x-grid/usage/#gutter-modes)

**Removed**

- Old link was: /guidelines/2x-grid/implementation#gutter-modes

### CODE REVIEW

**Comment by crlordan** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by Kritvi-bhatia17 — APPROVED** [review]
Thanks, @crlordan, for fixing it! It looks good to me 🎉

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by laurenmrice — APPROVED** [review]
Looks good!

**Pull request merged**
