### PR TITLE
Spacing updates

### LINKED ISSUE #1259: fix[spacing]: match spacing on intro content for guidelines pages to DL spacing
## Match intro spacing to DL spec

Intro paragraph and anchor links should be treated like one pattern; anchor links need to start much closer to the intro paragraph so content doesn't get pushed much further down the page. This pattern only occurs right now on the Guidelines pages... but we may bring intro paragraphs onto other pages eventually too.

- [x] Spacing between intro paragraph and anchor links should be 24px (right now it looks like 88-96px)

- [x] Spacing between anchor links and first H2 should be 80px (right now it looks like 88-96px)

image

### LINKED ISSUE #1355: fix[intro paragraph]: line length too long at tablet
## fix[intro paragraph]: line length too long at tablet

To match IDL site:

- [x] Carbon's intro paragraph should only span 6 columns in tablet not all 8 columns.

### PR DESCRIPTION
**Pull request by vpicone**
This closes #1355, and closes #1259

#### Summary
Fixes for markdown spacing and malformed props

#### Changelog

**Changed**

- anchor link margins
- h3 column width on tablet
- various class→className "true"→{true} prop fixes

### CODE REVIEW

**Comment by vpicone** [comment]
@alisonjoseph I went ahead and reverted the prop-type change, it seems like we use "true" far more than {true} in these components. Can look into it at a later date.

**Comment by alisonjoseph** [comment]
👍its just something I missed in the conversion to MDX, because all props were strings prior to that

**Comment by alisonjoseph** [comment]
@jeanservaas do you have time to review today?

**Comment by alisonjoseph** [comment]
should be good to merge after merge conflict is fixed @vpicone

**Comment by vpicone** [comment]
ugh forgot about this PR when I nuked my fork from orbit. I'll make a new one tonight.

**Pull request merged**
