### PR TITLE
Do not merge: Community Edit Pattern V2

### PR DESCRIPTION
**Pull request by chloepoulterdesign**
Cloud & Cognitive Design System Adoption Guild is working on a V2 for the Community edit pattern to bring it up to date with the new create pattern. 

Will update as we make progress.

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by chloepoulterdesign** [comment]
I have read the DCO document and I hereby sign the DCO.

recheck

**Comment by chloepoulterdesign** [comment]
recheck

**Review by dakahn — APPROVED** [review]

**Comment by tay1orjones** [comment]
I'm going to mark this as a draft until it's ready to be reviewed and merged

**Comment by tay1orjones** [comment]
This one has gone quite stale. Going to close it out, we can reopened if desired!

**Pull request closed without merging**
