### PR TITLE
feat: add edit link component

### LINKED ISSUE #1216: Dev: Site Feedback Loop
For the cupcake site feedback loop we want to link to the .mdx file in github so a user can propose changes for any page.

The link should go directly to the page's .mdx file similar to the "Edit Topic" link in cloud docs https://cloud.ibm.com/docs/apps/tutorials?topic=creating-apps-tutorial-starterkit#create_starterkit

Design specs from here https://github.com/carbon-design-system/carbon-website/issues/862#issuecomment-467622946

> ### Updated design:
> image
> 
> ### Spec
> Currently footer & buttons is 160px after main content. 1 liner with button should be 16px above footer.
> 
> image

### PR DESCRIPTION
**Pull request by vpicone**
Closes #1216

Adds a link at the bottom of every page to allow editing on github.

#### Changelog

**New**

- EditLink component

**Changed**

- Increased padding-bottom of the page component to be closer to the `160px` target (some of the content lacks a padding bottom and will still come up short). This handles the most common case.
- Repository link

### CODE REVIEW

**Comment by designertyler** [comment]
GitHub should be spelled with an uppercase `G` and `H`. Other than that change, this is amazing.

**Comment by shixiedesign** [comment]
So glad you figured this one out! 
- [ ] Click zone stretches out too far, users could accidentally click it while thinking they wanna click Next button.
Mar-27-2019 11-13-48
- [ ] Any chance of getting "Last updated..." in there? If not let's not close the issue yet so we don't forget to update later.
image

**Comment by vpicone** [comment]
@shixiedesign should be resolved now

Adding the `last updated` bit will require some Gatsby source magic. 

I'm okay with opening a new feature request issue or modifying the current one. Whichever makes more sense to @designertyler.

**Comment by designertyler** [comment]
Let's add the time stamp in another PR so we can get this one merged today. I'll create an issue for the time stamp.

**Pull request merged**
