### PR TITLE
Update website deps for v10.47.2

### PR DESCRIPTION
**Pull request by tay1orjones**
Updates deps for patch release v10.47.2

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]

**Comment by tay1orjones** [comment]
Looks like we're not getting the updated versions of the carbon deps. The deploy preview still shows tooltips center aligned
image

**Comment by tay1orjones** [comment]
@vpicone I had to add the `resolutions` field back in to get the proper versions. The deploy preview should show correct tooltips once redeployed

**Comment by tay1orjones** [comment]
For reference, without the resolutions field here's what `yarn why` gives me

```
❯ yarn why carbon-components
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "carbon-components"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "carbon-components@10.47.1"
info Has been hoisted to "carbon-components"
info Reasons this module exists
   - "workspace-aggregator-f0392798-4856-4e9b-91bb-41bf42662a72" depends on it
   - Specified in "dependencies"
   - Hoisted from "_project_#carbon-components"
info Disk size without dependencies: "17.99MB"
info Disk size with unique dependencies: "19.87MB"
info Disk size with transitive dependencies: "39.08MB"
info Number of shared dependencies: 139
=> Found "gatsby-theme-carbon#carbon-components@10.46.0"
info This module exists because "_project_#gatsby-theme-carbon" depends on it.
info Disk size without dependencies: "17.93MB"
info Disk size with unique dependencies: "19.81MB"
info Disk size with transitive dependencies: "39.03MB"
info Number of shared dependencies: 139
=> Found "@carbon/charts#carbon-components@10.40.0"
info This module exists because "_project_#@carbon#charts-react#@carbon#charts" depends on it.
info Disk size without dependencies: "16.09MB"
info Disk size with unique dependencies: "17.97MB"
info Disk size with transitive dependencies: "37.19MB"
info Number of shared dependencies: 139
✨  Done in 2.63s.
```

After adding resolutions:
```
❯ yarn why carbon-components
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "carbon-components"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "carbon-components@10.47.1"
info Has been hoisted to "carbon-components"
info Reasons this module exists
   - "workspace-aggregator-f908692f-6fdf-405c-b061-da6565e635d7" depends on it
   - Specified in "dependencies"
   - Hoisted from "_project_#gatsby-theme-carbon#carbon-components"
   - Hoisted from "_project_#carbon-components"
   - Hoisted from "_project_#@carbon#charts-react#@carbon#charts#carbon-components"
info Disk size without dependencies: "19.16MB"
info Disk size with unique dependencies: "21.53MB"
info Disk size with transitive dependencies: "40.74MB"
info Number of shared dependencies: 139
✨  Done in 1.43s.
```

**Comment by vpicone** [comment]
Works for me, just gotta remember to remove them post release!

**Comment by vpicone** [comment]
Just installing and specifying our own min version doesn't work? We're still in the theme versions range right? Resolutions would be for if our specified version was in conflict with the theme version.

**Comment by tay1orjones** [comment]
@vpicone Yeah, with just the version bump in package.json dependencies we were not seeing updated styles for tooltip on the site from the new patch release I cut yesterday. We're in the theme versions range, but for some reason it was still pulling `"gatsby-theme-carbon#carbon-components@10.46.0"` instead of `"carbon-components@10.47.1".`

Once I added the resolutions and rebuilt the site I saw the updated tooltip styling fix come through. It's fixed on the deploy preview now too, https://carbondesignsystem-git-fork-tay1orj-5f02e3-carbon-design-system.vercel.app/components/tooltip/usage/

**Comment by tay1orjones** [comment]
@vpicone I think if we had yarn v2 we could avoid using resolutions by using it's improved `dedupe` command. It's more robust than the auto-dedupe that yarn v1 includes by default with `yarn install`. https://dev.to/arcanis/yarn-2-2-dedupe-faster-lighter-ha5

The monorepo uses v2 and includes `yarn dedupe --check` as a preflight status check on PRs

**Comment by vpicone** [comment]
Atlassian also has a tool for that. Yeah, something's broken with the lock file. Could probably just nuke it and start from scratch 🤷 

https://github.com/atlassian/yarn-deduplicate

**Comment by vpicone** [comment]
If that doesn't work, I'm down for this as a temporary fix but hand changing the resolutions every patch of the monorepo isn't a sustainable workflow.

**Comment by tay1orjones** [comment]
@vpicone yep, I regenerated the lock file and it's fixed without `resolutions` 👍

**Review by vpicone — APPROVED** [review]

**Comment by tay1orjones** [comment]
Not sure why this is failing with

```
ENOENT: no such file or directory, open '/vercel/path2/src/gatsby-theme-carbon/components/MediumPosts/index.js'
```

It builds for me locally. @vpicone could you try a redeploy for me?

**Comment by vpicone** [comment]
@tay1orjones on it! Vercel shows you on the member list is it not letting you redeploy?

**Pull request merged**
