### PR TITLE
remove unnecessary dataviz tutorials

### PR DESCRIPTION
**Pull request by theiliad**
Removing dated and unnecessary dataviz getting started tutorials.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
I think you will need to update the left nav file also since the url for the first page won't be /vanilla anymore. (we should also make sure no other pages are referencing that link)

**Comment by theiliad** [comment]
> I think you will need to update the left nav file also since the url for the first page won't be /vanilla anymore. (we should also make sure no other pages are referencing that link)

Good point, just pushed that. And running just a simple file search I don't think there are any other links to the page

**Comment by theiliad** [comment]
Hi team, ready to merge?

**Comment by theiliad** [comment]
just a heads up, we need this PR out asap since the info that's currently on the site is dated and irrelevant

**Pull request merged**
