### PR TITLE
fix(typography): fix controls bug

### LINKED ISSUE #2864: Typography>Type set layout bug
https://www.carbondesignsystem.com/guidelines/typography/type-sets

Breakpoints/type set sections should be side by side
Screen Shot 2022-04-06 at 1 06 26 PM

Should display side by side I believe? (screen shot from v10 website)
Screen Shot 2022-04-06 at 1 07 46 PM

### PR DESCRIPTION
**Pull request by aledavila**
Closes #2864

Removes wrap styles added in controls.

#### Changelog

**Removed**

- removed flex wrap

### CODE REVIEW

**Review by laurenmrice — APPROVED** [review]

**Comment by tw15egan** [comment]
Should this break to a new line on smaller viewports?

Screen Shot 2022-09-06 at 6 27 42 PM

**Comment by jnm2377** [comment]
@laurenmrice any thoughts on TJ's question above?

**Comment by laurenmrice** [comment]
Oh yes, thanks @jnm2377 missed that comment. @aledavila At mobile it needs to stack into two rows. It should be working how IDL currently has it on their website. https://www.ibm.com/design/language/typography/type-specs-ui

Screen Shot 2022-09-08 at 3 37 49 PM

**Comment by aledavila** [comment]
@tw15egan @jnm2377 @laurenmrice ok should be fixed now !

**Review by jnm2377 — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by laurenmrice — APPROVED** [review]

**Pull request merged**
