### PR TITLE
Carbon platform update

### PR DESCRIPTION
**Pull request by francinelucca**
Platform Sync, pulling in new content from main into carbon-platform branch

### CODE REVIEW

**Review by andreancardona — CHANGES_REQUESTED** [review]
@francinelucca vercel is failing :(

**Review by tay1orjones — APPROVED** [review]
Code looks fine, but I'm not sure what's up with Vercel. None of the errors seem to point to files you changed. Does this build and run locally for you?

**Review by aagonzales — APPROVED** [review]
Just reviewed the files changed and it looks good!

**Comment by andreancardona** [comment]
> Code looks fine, but I'm not sure what's up with Vercel. None of the errors seem to point to files you changed. Does this build and run locally for you?

Could also just need a redeploy?

**Comment by francinelucca** [comment]
@tay1orjones @andreancardona  yeah vercel failure is expected, because of the changes we've done to the code (previously) on `carbon-platform` this code isn't actually runable as a website

**Pull request merged**
