### PR TITLE
docs: fix pagination table

### LINKED ISSUE #4265: [Pagination] Bug with the variants table of Pagination
## Acceptance criteria

- [x] There is a markdown bug with the table appearing in the `Variants` section on the Usage tab for Pagination. It needs to be fixed.
- [x] Review
Screenshot 2024-09-18 at 10 53 58 AM

### PR DESCRIPTION
**Pull request by laurenmrice**
Closes #4265 

Fixes some markdown in a table on the Pagination Usage tab

#### Changelog

**Removed**

- Removed some extra columns

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]

**Review by Kritvi-bhatia17 — COMMENTED** [review]
For some reason, the preview link is still building on my end, even after trying different browsers. I'm not quite sure what's causing the issue. 🤔 
Screenshot 2024-09-18 at 9 45 28 PM

**Comment by laurenmrice** [comment]
@Kritvi-bhatia17 It is working for me. Here is the direct link to it: https://carbondesignsystem-git-fork-laurenm-5d8917-carbon-design-system.vercel.app/components/pagination/usage/

**Review by ariellalgilmore — APPROVED** [review]

**Review by Kritvi-bhatia17 — APPROVED** [review]
LGTM!

**Comment by laurenmrice** [comment]
This PR is ready to merge in but is having a vercel deployment issue.

**Pull request merged**
