### PR TITLE
chore: enable service worker

### PR DESCRIPTION
**Pull request by vpicone**
Enables service worker for performance/poor connectivity experiences. 

Previously, we got stuck on the toast notification "new version available click to refresh" solution. This PR enables a pretty clever workaround for that we added to the theme. Whenever the service worker detects a new version is available, the next time a user clicks a LeftNav link, it acts like a regular anchor link rather than a Gatsby Link. This means it gets a fresh copy from the server.

I tested by leaving a deployment up in my browser, pushing an update, then navigating around. It successfully refreshed in all the major browsers and we got some nice performance boosts.

**The reduction for time to interactive seemed particularly nice, it's a pain when nothing is clickable**

### Before
Screen Shot 2020-10-07 at 1 35 49 PM

### After
Screen Shot 2020-10-07 at 1 35 54 PM

### CODE REVIEW

**Comment by alisonjoseph** [comment]
I'm trying to remember why we removed this initially, weren't we having issues with not being able to view updated versions of the site when we deployed an update?

**Comment by vpicone** [comment]
@alisonjoseph yeah, we got stuck on the toast notification "new version available click to refresh" solution.

I think this is PR is a pretty clever workaround for that. Whenever Gatsby detects a new version is available, the next time a user clicks a left LeftNav link, it acts like a regular anchor link rather than a Gatsby `Link`. This means it gets a fresh copy from the server.

I tested by leaving a deployment up in my browser, pushing an update, then navigating around. It successfully refreshed in all the major browsers and we got some nice performance boosts.

**Comment by alisonjoseph** [comment]
Oh nice 🎉 I'm all for adding it in

**Review by alisonjoseph — APPROVED** [review]

**Review by shinytoyrobots — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
🎉 👍 ✅

**Comment by mattrosno** [comment]
@vpicone very cool. I like that better than putting this in gatsby-browser.js because it's a noticeable ~1s delay before the entire page refreshes (if service worker has something new).

```
export const onServiceWorkerUpdateReady = () => {
  window.location.reload();
};
```

**Comment by vpicone** [comment]
@mattrosno yeah I think the sudden page refresh can be jarring, could potentially be disruptive on sites with forms/videos as well.

**Pull request merged**
