### PR TITLE
fix(loading): enable `withOverlay` knob

### LINKED ISSUE #2106: [live demo] loading audit bugs
Live demo loading:
- [ ] missing the toggle to turn on an overlay
- [x] in the demo the small loading is wobbling around and not staying in place.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2106

may be affected by or depends on #2262 #2281 #2283

This PR adds support for the `withOverlay` knob on the Loading component live demo

### CODE REVIEW

**Comment by tw15egan** [comment]
I see the `withOverlay` prop in the code (and can actually toggle it by editing the code), but I don't see the prop over in the knob section 

Screen Shot 2021-05-05 at 11 47 56 AM

**Review by janchild — COMMENTED** [review]
The overlay is present on the Code tab but not on the Usage tab.

**Comment by emyarod** [comment]
it should be present on both tabs now

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by janchild — APPROVED** [review]

**Pull request merged**
