### PR TITLE
docs: add images and description of drag and drop single file functionality

### LINKED ISSUE #3705: Single File Uploader: Docs
### Acceptance criteria

**Usage tab**
- [x] Add content that the Drag and Drop variant by default enables you to upload multiple files, but we also have one that allows only one file upload. 
- [x] Add any images to support the new content if needed.

**Style tab**
- [x] Add structure image

### PR DESCRIPTION
**Pull request by laurenmrice**
Closes #3705 

- Usage tab: Added a short description and image of when the drag and drop file uploader has a single file upload functionality.
- Style tab: Added a structure image.

**New**

- New description and images of drag and drop with single file functionality.

### CODE REVIEW

**Review by guidari — APPROVED** [review]
LGTM! 🚀

**Comment by thyhmdo** [comment]
### Usage tab
**Drag and drop file uploader h1** 

- Maybe we can add a small heading for multiple vs single uploads, I was hard to distinguish the info at first. 
- This is an old image, but I'm not sure if it's the same with dragging interaction, but in the code, we have the underline for the text inside. Though, the current image could be the correct way because it's rendered as the button instead of a link. 

image
- Shouldn't drag and drop zone here in the enabled state? 

image

-----
### Style tab 

**Structure**
The ending points are not in the right style. 

image

image

**Comment by laurenmrice** [comment]
- Updated the above^ 
- For the Style tab structure image, yes, I kept this new image the same because all the other structure images are outdated. But I can just take some time to fix all of the structure images to use the updated style.

**Review by alina-jacob-ibm — APPROVED** [review]
Looks good!

**Comment by laurenmrice** [comment]
@guidari I keep running into a formatting failure. When you have time, could you help me fix that? Thanks!

**Pull request merged**
