### PR TITLE
Update to data table accessibility tab

### PR DESCRIPTION
**Pull request by mbgower**
Rewrite of content and addition of 4 images

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by abbeyhrt — APPROVED** [review]

**Comment by mjabbink** [comment]
@mbgower I think the below copy can get the “why/benefit” part I mentioned in the other issue. 
Screen Shot 2022-03-04 at 11 07 49 AM

**Comment by mbgower** [comment]
@mjabbink I'd missed your other [comment](https://github.com/carbon-design-system/carbon-website/pull/2737#issuecomment-1058467132)

>Suggestion
What Carbon provides
Carbon bakes keyboard operation into its components, as well as many other accessibility considerations. This allows for... benefits, advantages... the why.

I've opened an internal issue to address your request.
When we were testing, we got some pushback on having too much text at the top. I'll see if I can't put something succinct in as part of what is effectively boiler plate when I start working on my next component (in a few weeks), and run it by some sponsor users. Then I can just loop back and add it to these already created components.

In the meantime, I'm just going to push the existing text since it's gone through handoff. That okay?

**Comment by mjabbink** [comment]
The additional sentence that describes the “so that you can... ” or “in order to provide...” is helpful to provide context to why Carbon provides the thing you’re talking about. The designers need to know that information.

**Comment by mjabbink** [comment]
What Carbon provides

Carbon bakes keyboard operation into its components, as well as many other accessibility considerations which can better optimize or improve experiences for screen readers.

or

Carbon bakes keyboard operation into its components, as well as many other accessibility considerations which can improve experiences for blind users and others who need to operate via the keyboard API.

**Review by laurenmrice — APPROVED** [review]
👍

**Pull request merged**
