### PR TITLE
fix(Typography): Remove italic from helper-text-01

### PR DESCRIPTION
**Pull request by shixiedesign**
Closes https://github.com/carbon-design-system/carbon-website/issues/314

Remove "italics" from `$helper-text-01` description & example

#### Changelog

**Changed**

Typography page, `$helper-text-01` description.
Change `helper text` example to be not italic.

### CODE REVIEW

**Comment by shixiedesign** [comment]
Looks like I was unable to remove the italic in the example. Welp! 

image

**Comment by shixiedesign** [comment]
Let's wait for the rest of the color PRs to line up and merge together.

**Comment by alisonjoseph** [comment]
> I removed the "italic" mention in the spec, but looks like I was unable to remove the italic in the example. Welp!

This is pulling styles directly from the type package. Has it been updated there?

**Comment by shixiedesign** [comment]
Ah that explains it! Thank you @alisonjoseph . I will make an issue to update the type package.

**Comment by alisonjoseph** [comment]
fix was merged in and will be avail in next Carbon minor release https://github.com/carbon-design-system/carbon/pull/4004

**Comment by shixiedesign** [comment]
This issue fixes the text description on the website, not the actual token value. Waiting for release date to merge because we don't wanna update the website without releasing the token in prod.

**Pull request merged**
