### PR TITLE
docs(modal): Update usage.mdx

### PR DESCRIPTION
**Pull request by mbgower**
Some suggested changes that address accessibility and other considerations, to be discussed at the Guild call.

### CODE REVIEW

**Review by aagonzales — CHANGES_REQUESTED** [review]
This is good except you need to convert the "Labels" on the style tab to "Heading" as well.

**Comment by mbgower** [comment]
@aagonzales Agreed. I wasn't sure if this was a welcome change, and would still like to discuss. As well, there are a number of other potential changes to make to the Style page, which I'd like to go over on the Carbon call.

**Comment by mbgower** [comment]
@laurenmrice a reminder that the image of Drag and drop file upload, which currently reads "Drag and drop files here or upload" needs to applied across both Usage and Style to read:
> Drag and drop files here or click to upload"

This matches the implementation.

**Comment by mbgower** [comment]
Just thought I'd capture what I put in slack. The wording and style was based what is already used on the Carbon website (such as modal)
image

**Review by mbgower — COMMENTED** [review]
Addressed style update

**Review by aagonzales — APPROVED** [review]
LGTM

**Review by aledavila — APPROVED** [review]

**Pull request merged**
