### PR TITLE
Color docs: Update tab names for consistency 

### LINKED ISSUE #3528: Color docs: Update tab names for consistency
- [x] Rename Usage to Tokens
- [x] Rename Implementation to Usage
- [x] Tab order for Color should be Overview, Usage, Tokens, Code
- [x] Add redirect for Implementation->Usage

Screenshot 2023-05-03 at 9 12 03 AM

https://www.figma.com/file/mtARocDBevZmtgEMjb1cJs/2x-grid-overview-updates?node-id=0-1&t=EjP5Om4KoQC3al2O-0

### PR DESCRIPTION
**Pull request by guidari**
Closes #3528

it was changed the menu naimg and order:

 - Renamed Usage to Tokens
 - Renamed Implementation to Usage
 - Renamed the "file.mdx" to match the the new name in the menu

New tab order **Overview, Usage, Tokens, Code**

**Testing**

Make sure the links goes to the expected page:
https://carbondesignsystem.com/guidelines/color/overview/

### CODE REVIEW

**Review by andreancardona — APPROVED** [review]
Looks good!

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
This LGTM! We probably want to add a redirect in for Implementation to redirect to code, you can add that in this file here, let me know if you have questions. 

https://github.com/carbon-design-system/carbon-website/blob/main/conf.d/rewrite.conf

**Comment by alisonjoseph** [comment]
@guidari I would add this to line 5

`rewrite /guidelines/color/implementation /guidelines/color/code/\$1 permanent;`

**Review by alisonjoseph — APPROVED** [review]

**Comment by alisonjoseph** [comment]
@aubrey-oneal can you take a quick look when you get a chance 😄

**Review by aubrey-oneal — APPROVED** [review]
Looks good! 🚀

**Pull request merged**
