### PR TITLE
feat(homepage): change theme to white

### PR DESCRIPTION
**Pull request by tay1orjones**
Some new visual treatment for the v11 release!

#### Changelog

**Changed**

- update theme on the homepage to be white

@carbon-design-system/design There are elements on the page that appear to have been given specific styling to go with the default dark theme, like the big black callout under the image. 

I assume we'll want to modify these to be more in-line with the white theme, but I'm not sure what the exact delta is or what to change it to.

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]

**Comment by jnm2377** [comment]
Agree, also have some questions around the dark callouts, and other items that were meant to go with the dark theme, but everything else is looking great! 🔥

**Review by aledavila — APPROVED** [review]

**Comment by aagonzales** [comment]
Here's a spec for the page. @tay1orjones 
- The banner image is still TBD, @thyhmdo will be working on one this week
- Included are two new png images for the get started sections (let me know if you need a different format.
- The top intro section will be a Blue-20 background with Gray 100 type (text-primary)
- The contribution section at the bottom will be Purple-20 with Gray 100 type (text-primary). 


Homepage_Final
getting-started-designers
getting-started-developers

**Comment by aagonzales** [comment]
Also while we're at it can we add a link in the "Resources" section to include a tile to the [Figma kit page](https://v11.carbondesignsystem.com/designing/kits/figma) as well (add beside the Sketch kit tile)/

**Comment by tay1orjones** [comment]
@aagonzales Love it! For those two `getting started` images you provided, it looks like we currently have different sizes exported for tablet and mobile.

**Comment by aagonzales** [comment]
@tay1orjones the little feedback guys in the bottom right are going behind some of the banners when you scroll. 

image

**Review by aagonzales — CHANGES_REQUESTED** [review]
@tay1orjones the little feedback guys in the bottom right are going behind some of the banners when you scroll. Also can we kill the little grid dots that are showing up on it too?

image

**Comment by tay1orjones** [comment]
@aagonzales that will be fixed over in https://github.com/carbon-design-system/carbon-website/pull/2823 where I've updated the gatsby theme version and related carbon dependencies. Sorry for the confusion.

**Review by aagonzales — APPROVED** [review]
Awesome! Then I think this is good to go. We can either merge this now and do the banner image update separately or wait for the image.

**Comment by tay1orjones** [comment]
I vote merge and I'll follow up with a new PR for the new banner image from @thyhmdo 🎉

**Pull request merged**
