### PR TITLE
docs(dataviz): add tree diagram demos, update network thumbnail

### PR DESCRIPTION
**Pull request by theiliad**
image
image

### CODE REVIEW

**Comment by mjabbink** [comment]
@theiliad The teal  `Design only `tag can be removed from the Network diagram thumbnail

Screen Shot 2021-09-13 at 12 08 07 PM

**Review by joshblack — APPROVED** [review]

**Review by kingtraceyj — APPROVED** [review]
looks good 💥

**Comment by theiliad** [comment]
> @theiliad The teal `Design only `tag can be removed from the Network diagram thumbnail
> 
> Screen Shot 2021-09-13 at 12 08 07 PM

that's a separate PR. I'm adding the demo there and removing the tag

**Comment by mjabbink** [comment]
Looks good. Great job on the thumbnails @thyhmdo

**Pull request merged**
