### PR TITLE
fix(IconLibrary): fix issue with glyph only icons

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon-website/issues/2448

Fixes an issue where we were importing all icons at the `32px` size, even if it was a glyph-only variant. This was causing the `guidelines/iconography` page to crash when one of these icons were loaded

#### Changelog

**Changed**

- If there is only 1 icon size, and the icon size is `glyph`, sets a flag that will load from the `index` file rather than `32` 

**Testing**

Go to `guidelines/iconography` and search for `caution` and ensure the page does not crash

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
it looks like there are some build errors with the new imports

**Review by theiliad — APPROVED** [review]

**Comment by tw15egan** [comment]
@joshblack not sure whats going on with this, it all runs fine locally but seems to run out of memory when Vercel tries to deploy

**Comment by joshblack** [comment]
@tw15egan ugh, I see what you mean. If you change this line: https://github.com/carbon-design-system/carbon-website/blob/main/package.json#L17 to use 8192 instead of 4096 does that help?

**Review by jnm2377 — APPROVED** [review]
Page doesn't break for me when I search for caution ✅

**Review by laurenmrice — COMMENTED** [review]
Looks good to me.

**Pull request merged**
