### PR TITLE
status indicator pattern

### PR DESCRIPTION
**Pull request by jeanservaas**
TO DO:

- [ ] @vpicone add the tables (# https://github.com/carbon-design-system/carbon-website/issues/2199)
- [x] @janchild quick content review (with an eye to naming... I think that's the most awkward thing about the pattern content-wise the (Full status indicator, Badge status indicator, Shape status indicator and Differential status indicator) — that's what I most want your opinion on. **Don't bother with the Notion document anymore except for the tables.**

Closes # https://github.com/carbon-design-system/carbon-website/issues/2199

ADDITIONS:
Sorry vince, I don't have an issue for this, I thought I could handle it in markdown but I cannot.

- [ ] @vpicone could you also add the new colors into the palette component (I need the blue, purple and gray added) — I'm hoping this won't be too much trouble, @josefina already has these components made... I just can't change the colors in markdown. https://www.carbondesignsystem.com/data-visualization/color-palettes/

image

Light values

image

Dark values

image

- [ ] I also need to enter the yellow and orange values into the palette component, but I do not need it to have tabs... it doesn't have separate dark and light values.

image

image

### CODE REVIEW

**Comment by jeanservaas** [comment]
@vpicone here are the assets for all the tables. I still need to consult @janchild about a couple of content issues... I'm not sure how useful this page would be without the tables anyway.

[Status_icons.zip](https://github.com/carbon-design-system/carbon-website/files/6454161/Status_icons.zip)

**Comment by vpicone** [comment]
@jeanservaas that's the idea behind removing it from the nav-items. We can publish the page without surfacing it in the side nav until the tables are ready.

**Comment by vpicone** [comment]
@jeanservaas I temporarily removed the entry from the sidebar. When it's ready we can "soft launch" it and I can open a new PR for the tables. 

Reviewers: You can still see the page by manually adding `/patterns/status-indicator-pattern/` to the URL.

**Comment by jeanservaas** [comment]
@vpicone can you put back the .yaml file on the status indicator page? We’re not going to soft launch it, there’s really no point in a soft launch without the tables and colors in there

**Comment by jeanservaas** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by vpicone** [comment]
Made a new issue to finish this off here: https://github.com/carbon-design-system/carbon-website/issues/2366

**Pull request merged**
