### PR TITLE
Update resource card link

### PR DESCRIPTION
**Pull request by aagonzales**
Resource was not downloading but had correct link. Just linking to the Sketch Cloud page for now.

### CODE REVIEW

**Review by laurenmrice — APPROVED** [review]
Thank you!!!

**Review by alisonjoseph — APPROVED** [review]

**Comment by aagonzales** [comment]
@alisonjoseph do you know why the deployment is failing?

**Comment by alisonjoseph** [comment]
yea, the closing tag was missing, added it back 😄

**Comment by aagonzales** [comment]
dang! so sneaky those closing rags. thanks!

**Pull request merged**
