### PR TITLE
fix(component-index): 1768 & 1743 component-index-visual-bugs

### LINKED ISSUE #1768: [index] remaining visual bugs
- [ ] Filter text is misaligned https://github.com/carbon-design-system/carbon-website/issues/1743
- [x] Border between search and sort bar should be Gray-20/ui-03 (below is as is)
image
- [x] Border between filter categories is shortened (regression, was correct at one point). It should span the width of that filter content area. (or be 224px wide)
image
- [x] Filter labels should be 12px not 14px.
image

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #1768 & #1743

Fixes the following visual issues on the Component Index: 

- [x] Filter text is misaligned https://github.com/carbon-design-system/carbon-website/issues/1743
- [x] Border between search and sort bar should be Gray-20/ui-03
- [ ] Border should be 224px wide
- [x] Filter labels should be 12px not 14px.
image

### CODE REVIEW

**Review by aagonzales — COMMENTED** [review]
On smaller screens those filter dividers are running off the edge. Can have make sure it has 32px on the edge there. The rest looks great!

image

**Comment by andreancardona** [comment]
> re it has 32px on the edge there

Ooops yes doing that now

**Comment by andreancardona** [comment]
@aagonzales let me know how it looks now!

**Review by aagonzales — APPROVED** [review]
Yes, perfect!

**Review by tw15egan — APPROVED** [review]
👍 ✅

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
