### PR TITLE
feat(image-component): added custom component for images

### LINKED ISSUE #683: Image Component
### Image component requirements (revisited by Shixie)

- [ ] Caption support. Ref Jeanie's comment below for spec https://github.com/carbon-design-system/carbon-website/issues/683#issuecomment-454586014
- [ ] Need a way to specify how many columns an image should span. 
We only need 4 options: `lg=12 col` ,`md=8 col`, `sm=6 col`, `xs=4 col` (these are values at max breakpoint. More detail see below image or https://github.com/carbon-design-system/carbon-website/issues/524)
image

- [ ] An option to turn on-off "on grid". fixed (has a max pixel width and max-width 100%) vs. fluid (scales on grid)

- [ ] Default images in Markdown eg. `caption` should have `md` size if landscape, `sm` size if portrait.

**post-THINK**

- [ ] A way to turn on the ability to "onClick to view large" in a modal
We would need for component spec images coz specs are usually small and hard to read, not necessary for all images). The ideal experience is to expand the image in a modal (instead of in a new Tab because it will be missing background). This is also good in preparation of future iteration of "live spec"

### PR DESCRIPTION
**Pull request by marijohannessen**
Closes #683 

Added in custom component `ImageComponent`. Wraps around all the images on the website.

Example:

```
<image-component cols="12" caption="I am an image">

![image-alt-text](/images/cool.png)

</image-component>
```

### Customizable:

`cols`: The image can span over either 4, 6, 8 or 12 columns
`border`: If set to true, will have an 1px solid `$ui-03` border
`fixed`: If set to `default` or `large`, it will have a max-width of either 720px or 1120px
`bg`: If set to `none` then it will not have a white background

### TODO

- [x] Right now it only specifies columns on large screens, need to figure out how this translates down on smaller screens
- [x] Trying to figure out how to remove the image from the grid (per requirement in #683), not sure if this is possible when the max-width is set in the gatsby image plugin, do you know @alisonjoseph ?

### CODE REVIEW

**Comment by alisonjoseph** [comment]
> Trying to figure out how to remove the image from the grid (per requirement in #683), not sure if this is possible when the max-width is set in the gatsby image plugin

The only thing I can think of is that we add a width property and add the specific width the image should be, then make sure it has a max-width 100% so it scales when the browser is smaller. Not 100% sure that would work, but I think so?

**Comment by marijohannessen** [comment]
> Can we make it possible to add custom classes (in case a specific image need overrides?)

Yes definitely!

**Comment by marijohannessen** [comment]
Just pushed up the initial work on how the component would handle images that don't follow the grid. @shixiedesign and @jeanservaas can you guys take a look and see if it is behaving as expected? I've only tested it out on the images on accordion/style, breadcrumbs/style, and buttons/style. These all have a max-width of 720px now. I have not tested it out on the larger variant (1120px).

**Comment by marijohannessen** [comment]
Deploy link: https://deploy-preview-811--carbon-website.netlify.com/

**Comment by shixiedesign** [comment]
Images (on accordion breadcrumb button) are responding correctly!! Exactly what we want. Just to clarify, we still have the option to use fluid behavior on images on Elements pages, correct? Currently the images on elements pages look affected. They are still fluid but their captions are no longer styled. 

So overall images (on component style tabs & elements pages) are behaving right, just need to restore caption styling! 

Eg. below image caption line length should be 4 col wide, and fluid with browser width...let us know if this is a difficult change. Thank you Mari!! 🙏

image

**Comment by shixiedesign** [comment]
I noticed the markdown syntax is `fixed = default`. What should that be when the image is fluid?

**Comment by marijohannessen** [comment]
> Images (on accordion breadcrumb button) are responding correctly!! Exactly what we want. Just to clarify, we still have the option to use fluid behavior on images on Elements pages, correct? I noticed the markdown syntax is `fixed = default`. What should that be when the image is fluid?

You just wouldn't add the `fixed` option at all!

**Comment by shixiedesign** [comment]
Hey @marijohannessen , sorry I noticed an issue...both `fixed="default"` and `fixed="large"` are displaying at large size (1120px). The images with `fixed="default"` flag should display at `720px` width. Is this an easy fix?

**Pull request merged**
