### PR TITLE
Update in step-1.mdx

### PR DESCRIPTION
**Pull request by cassiasamp**
Closes #

Just adding some detail to instructions about creating an empty `app.scss` file. 
The parts in the tutorial about recompiling starting on `line 182` are still unclear to me as their meaning. 
So, I hope the creation of this empty file is the right way to go and it seems a good idea to make it explicit.

#### Changelog

**New**

- Included "(...) a separate file. Create an empty file `app.scss` in the 'src' directory, and then import it in (...)"

**Changed**

- The line "speed this up by moving our custom app Sass into a separate file, `app.scss` in
the 'src' directory, and import that from `App.js`."

**Removed**

- Some words and punctuation.

### CODE REVIEW

**Comment by cassiasamp** [comment]
recheck

**Comment by cassiasamp** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by cassiasamp** [comment]
recheck

**Comment by guidari** [comment]
Hey @cassiasamp thank you for your contribution! 

We are actually doing a new tutorial using NextJS in this [PR](https://github.com/carbon-design-system/carbon-website/pull/3710) which means the current tutorial will senset soon.

**Review by guidari — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]

**Comment by cassiasamp** [comment]
Thanks @guidari, that's an interesting info...would you say it's best if I switch from React to Next.js? 
I'm guessing the new tutorial would make things simpler 😅

**Pull request closed without merging**
