### PR TITLE
fix: align status indicator table to grid

### LINKED ISSUE #2435: [pattern] status indicator grid issues
### Grid issues:
Also, the the status icon and status shape tables are not on grid, to the spec that was given. And they're not consistently off grid either. 

**See misalignment:**

image

**Table specs:** (See complete table specs at breakpoints here)
https://github.com/carbon-design-system/carbon-website/issues/2199

To do:

- @vpicone we need to align the tables to the specs that were in the other issue; I didn't catch these discrepancies in my review

### PR DESCRIPTION
**Pull request by alisonjoseph**
Ref #2199
Closes #2435 

Aligns status indicator table to grid.

### CODE REVIEW

**Review by jeanservaas — COMMENTED** [review]
Hey guys... wow... this happened fast. I thought it was close to impossible!!!???

Looks good in Firefox and Chrome

But Safari is having issues, the icon columns are huge! Not sure why that's happening

image

image

**Comment by alisonjoseph** [comment]
>I thought it was close to impossible!!!???

We all thought it was! Ale was set to start the re-write of this using grid components this sprint/next, and I decided to take a look and try something first, will look at Safari, hopefully can find a workaround that works there too 🤞

**Comment by aledavila** [comment]
Yea I'm looking at safari trying to figure it out thats super weird

**Comment by mjabbink** [comment]
@jeanservaas I think the two-column for small indicators is nice. Good as is. Nice work @aledavila and @alisonjoseph!

**Comment by alisonjoseph** [comment]
Fixed in safari! https://carbondesignsystem-ie873jn6c-carbon-design-system.vercel.app/patterns/status-indicator-pattern/

**Comment by alisonjoseph** [comment]
Ready to review in Safari @aledavila @jeanservaas 🙏

**Review by aledavila — APPROVED** [review]
Yes great fix @alisonjoseph thank you for tackling  that

**Comment by alisonjoseph** [comment]
approved by Jeannie via slack

**Review by abbeyhrt — APPROVED** [review]

**Pull request merged**
