### PR TITLE
fix: sticky nav on color page

### PR DESCRIPTION
**Pull request by alisonjoseph**
Noticed the math was off on the sticky tabs on the Color page after merging in the sticky page level tabs. 

Fixes when/where color page tabs become sticky

### CODE REVIEW

**Comment by lovemecomputer** [comment]
good catch!! there is one small issue still:

Apr-29-2019 15-44-06

**Comment by alisonjoseph** [comment]
@lovemecomputer it should be fixed now. still not 100% when scrolling fast, but it should be in the right position now

**Comment by lovemecomputer** [comment]
okay cool thanks!! i’m seeing a little issue on mobile which is: after scrolling up to reveal the sticky header, it obscured the page tabs. happens on this page 


4DDADAC5-5550-432A-B9CD-240F32C4EE20
D31C3446-BE47-4F35-A2C5-849C8ECB1E8C

however, i see a couple of other mobile issues, so maybe that would be best handled in a separate issue & PR for mobile fixes 
- color page “White” theme label is truncated to “Wte”?
- transitions for sticky header not happening in iOS Chrome—everything just snaps into place

**Comment by alisonjoseph** [comment]
I think "Wte" was on purpose? 🤷‍♀ but yea, we might want to address these other issues in the theme, so we don't duplicate work. 😅

**Comment by tw15egan** [comment]
Noticed the nav does not match the width of the table below it when it sticks, seems to be about 2-3px short


Not sticky:
Screen Shot 2019-05-01 at 10 43 33 AM

Sticky: 
Screen Shot 2019-05-01 at 10 43 38 AM

**Comment by tw15egan** [comment]
Guess it's just 1 breakpoint: 

Screen Shot 2019-05-01 at 10 50 25 AM

**Comment by alisonjoseph** [comment]
@tw15egan what breakpoint are you seeing that? I'm not able to duplicate it 🙈

**Comment by tw15egan** [comment]
I think it's only between `1280px` and `max`, so not a big deal at all 😄

**Comment by alisonjoseph** [comment]
@tw15egan ah ha! I see it. fixed.

**Comment by tw15egan** [comment]
Woo! 🎉

**Pull request merged**
