### PR TITLE
docs: clarify icon placement

### PR DESCRIPTION
**Pull request by designertyler**
Adds clarity to icon placement. 

image

### CODE REVIEW

**Comment by shixiedesign** [comment]
I'm not close to this work so feel free to ignore this comment, but at a glance, I wonder if changing up the content's sequence could help. See below, I cut&pasted the pieces to rearrange a bit so the main example is the first image, and do-don't as a follow up explanation. 

image

**Comment by aagonzales** [comment]
Yeah I agree shixie. I also think the "do" example should have the same content as the don't but just doesn't show the gap, like:
image

**Comment by designertyler** [comment]
@shixiedesign the example image is meant to be paired with the icon/position table below it. Since there can be any number of icon configurations I wanted to make it clear that it was only an example of icon placement so people don't take it as the only way you can place icons.

**Comment by designertyler** [comment]
I updated the do/don'ts to be square. It fits the space a little better than before.

image

**Pull request merged**
