### PR TITLE
[Structured list] Implement feature flag in live demo

### LINKED ISSUE #4064: [Structured list] Implement feature flag in live demo
## Acceptance criteria 

- [ ] The [Structured List Feature flag implementation](https://react.carbondesignsystem.com/?path=/story/experimental-feature-flags-structuredlist--selection) needs to be added to the [live demo section](https://carbondesignsystem.com/components/structured-list/usage/#live-demo) on the website. This will ensure that users can properly view and interact with the updated feature.

### PR DESCRIPTION
**Pull request by 2nikhiltom**
Closes #4064, #4100

Adds `enable-v12-structured-list-visible-icons` flag Implement in live demo

#### Changelog

**New**
Adds a new variant: `experimental-feature-flags-structuredlist--selection`

**Removed**
Removed a variant : `Simple` (As part of  #4100)
Note
- live demo broken for "Simple" variant
- There is no story with `simple` variant in [React storybook](https://react.carbondesignsystem.com/?path=/story/components-structuredlist--default) as well
- I feel simple variant should be removed from live demo
Please review and confirm the removal of `simple` variant 

**Testing / Reviewing**
Review the live demo of structured list under `Visible Icons` label

### CODE REVIEW

**Review by Kritvi-bhatia17 — COMMENTED** [review]
Nice work, @2nikhiltom! 🔥

I'm wondering if we should stick with the name "**Visible**" or choose something closer to what we have in Tiles, like "**Selectable with Improved Accessibility (unstable)**". 
What do you think? @laurenmrice 


image

**Comment by laurenmrice** [comment]
@Kritvi-bhatia17 I think what you suggested makes sense and is aligned more with what we already do for this in the Tiles live demo.

**Review by Kritvi-bhatia17 — CHANGES_REQUESTED** [review]
Got it @laurenmrice, thanks for validating!

@2nikhiltom now you can update the name from "**Visible Icons**" to "**Selectable with Improved Accessibility (unstable)**"

**Review by Kritvi-bhatia17 — APPROVED** [review]
LGTM! 🎉

**Review by guidari — APPROVED** [review]

**Pull request merged**
