### PR TITLE
fix: fix search component hover and height

### LINKED ISSUE #1306: Search Close icon should get a gray 80 hover
The search X has a gray 10 hover color.

Expected results: The search X has a gray 80 hover

### PR DESCRIPTION
**Pull request by aledavila**
Closes #1306 
#### Changelog

**Changed**

- hover color

**Removed**

- margin of input

### CODE REVIEW

**Comment by designertyler** [comment]
I'm seeing this in Chrome 
Mar-26-2019 11-35-44

**Comment by aledavila** [comment]
@designertyler yup dev and prod are not showing the same. pushed a fixed

**Comment by designertyler** [comment]
The close button is interfering with the focus state.

**Comment by aledavila** [comment]
@designertyler yea don't check yet since I can only work in production and it looks different in dev env I have to push everytime to see the correct fix. I will ping you

**Comment by designertyler** [comment]
Fixes look good. The icons for search and sweitcher are 2px too high. It should be 14px from the top and 14px from the bottom of the top bar.

**Comment by alisonjoseph** [comment]
Seeing this gap? is this supposed to be here? @designertyler 
Screen Shot 2019-03-26 at 2 59 57 PM

**Comment by designertyler** [comment]
@alisonjoseph yes, I'm seeing that gap too. I don't know where that came from. Can we get that resolved in this PR, too?

**Comment by aledavila** [comment]
@designertyler yup im not sure either. I don't know if changes to component messed with the aligning of this one but pushing a fix now

**Comment by alisonjoseph** [comment]
tested the build locally and looks good
Screen Shot 2019-03-27 at 9 16 49 AM

**Pull request merged**
