### PR TITLE
Fixed vercel links

### PR DESCRIPTION
**Pull request by guidari**
Closes https://github.com/carbon-design-system/carbon/issues/16028
Fixed vercel preveiw links for React tutorial

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
## Step 1, Step 2, and Step 3

### Large breakpoint (1056px width)

- Below the “The Principles” section at the bottom of the page, the background color should be using $background color token to make it gray instead of white. 


### Medium breakpoint (672px width)

**About tab**
- The image needs to move below the button. Refer to the design spec for the specs for this.

Screenshot 2024-04-16 at 1 09 00 PM

- The section called “The Principles” at the bottom of the page, refer to the design spec for this breakpoint to arrange the text correctly on the right columns. “Carbon is Modular” should be with the other Carbon is Open and Consistent text.

Screenshot 2024-04-16 at 1 09 18 PM

**Design tab and Develop tab**
- Below the “The Principles” section at the bottom of the page, the background color should be using $background color token to make it gray instead of white. 
- The text in the white space under the tabs needs to be $heading-03 type token.

### Small breakpoint (320px width)

- The spacing between the page heading and the tabs needs to be smaller in the small breakpoint. It should be 64px instead of 128px.

Screenshot 2024-04-16 at 1 11 01 PM

**About tab**
- We need to remove the Notifications and User Avatar icons in the UI Shell header, so the “IBM Carbon Tutorial” heading can fit. Usually those would then be added as menu items in the left hand nav. 

Screenshot 2024-04-16 at 1 11 16 PM

- The section called “The Principles” at the bottom of the page, refer to the design spec to add more padding between each line of text.

Screenshot 2024-04-16 at 1 11 39 PM

- The image should not appear in the small breakpoint.

**Design tab and Develop tab**
- The background page color below the “The Principles” section, should be using the $background color token so it is gray instead of white.

**Review by laurenmrice — CHANGES_REQUESTED** [review]
### Step 4

- For all breakpoints, there is too much padding between the white box where the image is and the “The Principles” text. It should be 40px padding.

Screenshot 2024-04-16 at 1 20 44 PM

### Large breakpoint (1056px width)

**About, Design, and Develop tabs**
- “The Principles” section at the bottom: The three different areas of text for Carbon is Open, Modular, Consistent, need to go below the “The Principles” heading. 

Screenshot 2024-04-16 at 1 22 20 PM

### Medium breakpoint (672px width)

**About tab**
- Mentioned earlier, but the image needs to be go below the button at this breakpoint.
- “The Principles” section at the bottom: This needs to be readjusted to match the design spec. 

Screenshot 2024-04-16 at 1 23 02 PM

**Design and Develop tabs**
- Mentioned earlier, but the text in the white space under the tabs needs to be $heading-03 type token.
- “The Principles” section at the bottom: This needs to be readjusted to match the design spec. 

**Small breakpoint (320px width)**
- Mentioned earlier, about the UI shell header content needing to be readjusted for this breakpoint. 
- The image should not appear in the small breakpoint.
- “The Principles” section at the bottom: This needs to be readjusted to match the design spec. 

Screenshot 2024-04-16 at 1 23 49 PM

**Review by laurenmrice — CHANGES_REQUESTED** [review]
I also noticed the **Step 5** vercel link was not updated in this PR, but it is also experiencing the same issues. Maybe that preview for Step 5 will be fixed by these.

**Review by alina-jacob — APPROVED** [review]

**Comment by laurenmrice** [comment]
@guidari Great work! ⭐️ Everything looks pretty good except for just 1 thing I am seeing across **Steps 4 and 5**:

- At the Large breakpoint: In the "The Principles" section, each individual section needs to span more columns to fill the width of the page. This is how the sections span the grid columns in the Figma file below.

Figma file:
Screenshot 2024-04-29 at 3 47 12 PM

Whats in the preview right now:
Screenshot 2024-04-29 at 3 44 59 PM

**Review by laurenmrice — APPROVED** [review]
Looks good! Thank you Gui! 🎉

**Pull request merged**
