### PR TITLE
Disabled image swap

### PR DESCRIPTION
**Pull request by connor-leech**
Our guidance suggests disabled elements should not be interactive. Swapped out the disabled state image showing a tooltip on a disabled primary button.

Also snuck some hyphen removal in 😉.

### CODE REVIEW

**Comment by connor-leech** [comment]
@alisonjoseph Is the reformatting of the `react-docgen.json` file an issue?

**Comment by alisonjoseph** [comment]
No idea what that file is, maybe @vpicone can help 😄

**Comment by jnm2377** [comment]
@alisonjoseph that file is what we use for the component demo knob data for all of the components.

**Comment by jnm2377** [comment]
Looks like the formatting just changed the indentation. The component demos all appear to be working correctly, so it should be fine. Although idk why the indentation changed, it looks weirder to me this way. 🤷‍♀️

**Comment by connor-leech** [comment]
@jnm2377 I'm guessing it was Prettier

**Comment by vpicone** [comment]
hmmmm, I wonder why it got ran here @connor-leech. Did you maybe edit something in that file by chance? Either way you can run `git checkout master -- ./src/data/docgen/react-docgen.json` from the package root to undo it in this PR. If we need to run prettier on it, we wanna do that in it's own issue.

**Pull request merged**
