### PR TITLE
Content switcher accessibility

### PR DESCRIPTION
**Pull request by mbgower**
Update of content switcher accessibility guidance

### CODE REVIEW

**Review by francinelucca — APPROVED** [review]

**Comment by laurenmrice** [comment]
For some reason the images are not showing up. This was happening in another PR recently in the website repo. @tw15egan do you know how to fix it?

**Comment by mbgower** [comment]
My suggestion is that if you're happy with the text content, we just squash and merge. They'll be there, 98%. And the prior images were definitely deployed, so worst case scenario, we'll go live with Jess's images and then just need a quick PR to resolve.

**Comment by laurenmrice** [comment]
@mbgower Currently the accessibility tab images are visually broken in the link preview provided in this PR and I am not comfortable with approving something from a design standpoint that could potentially still be broken if it goes live on our website. I will approve the PR once the image issue is resolved with the help from one of our devs.

**Comment by francinelucca** [comment]
@laurenmrice @mbgower images should be up now https://carbondesignsystem-git-content-swit-ae2abb-carbon-design-system.vercel.app/components/content-switcher/accessibility

**Pull request merged**
