### PR TITLE
docs: added AI slug examples for demo to components mentioned in #4072

### LINKED ISSUE #4072: AI documentation: Add AI Slug examples to the Live Demo
Add the Slug stories to the Live Demos for the following components. 
Also if there is a better way to show the AI prop with these components that dev can think of let me know. 

- [x] Checkbox
- [x] Data table
   - [x] [Column with sort](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-datatable--column-slug-sort)
   - [x] [Row with selection and expansion](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-datatable--slug-with-selection-and-expansion)
- [x] Date picker
   - [x] [Single with calendar ](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--date-picker)
- [x] Dropdown 
   - [x] Default
   - [x] Combo-box
   - [x] Multiselect 
- [x] Modal
- [x] Number input
- [x] Radio button
- [x] Select
- [x] Tag
- [x] Text area
- [x] Text input
- [x] Tile

### PR DESCRIPTION
**Pull request by Gururajj77**
Closes #4072

Added AI slug examples and fixed storybook ID mismatch for `FluidTextInput` and `FluidPasswordInput`

#### Changelog

**New**

- Added AI slug examples as new variants to the listed components

**Changed**

- updated correct storybook path ID for `FluidTextInput` and `FluidPasswordInput`

### CODE REVIEW

**Review by aagonzales — APPROVED** [review]
They look good to me!

**Review by 2nikhiltom — APPROVED** [review]
Looks good to me 🔥

**Review by alisonjoseph — APPROVED** [review]

**Comment by alisonjoseph** [comment]
@Gururajj77 this is good to merge once the merge conflict is resolved

**Review by guidari — APPROVED** [review]
LGTM!
This merge conflict is happening on most PRs from `carbon-website`. To fix you just have to revert the changes from `install-state.gz`

**Pull request merged**
