### PR TITLE
[Bug] updating the color tokens on the color page

### PR DESCRIPTION
**Pull request by thyhmdo**
Fixes https://github.com/carbon-design-system/carbon-website/issues/3314
updating the color tokens on the color page

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
@thyhmdo what issue # should this reference or close?

**Comment by thyhmdo** [comment]
> @thyhmdo what issue # should this reference or close?

@tay1orjones it's this one https://github.com/carbon-design-system/carbon-website/issues/3314

**Comment by tay1orjones** [comment]
@thyhmdo Great! If you auto link it in the PR body it'll automatically close the issue when this PR is merged.

[The docs here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) do a great job explaining the keywords/syntax that work

**Comment by thyhmdo** [comment]
> The docs here

Thanks Taylor!

**Review by francinelucca — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]
Looks good, thanks for doing this!

**Pull request merged**
