### PR TITLE
feat(banner): update banner text, add close functionality

### LINKED ISSUE #1672: Update website banner to increase 2020 election awareness
I'm glad we've used our platform to show support and bring awareness to the Black Lives Matter movement. With election day less than two months away, we should update our messaging towards increasing civic engagement and ensuring people are registered to vote. I've noticed a few websites/apps have already changed their messaging in a similar fashion:

[Microsoft / GitHub](https://github.com/)

Screen Shot 2020-09-04 at 9 24 40 AM

Links to an internal blog post about [civic engagement](https://github.blog/2020-09-01-ready-to-vote-in-the-u-s-2020-elections/)

Discord

Screen Shot 2020-09-04 at 11 47 42 AM

Links to [vote.org](https://www.vote.org/) which has a lot of valuable election day info, like checking to make sure you are registered and letting people sign up to vote by mail.

@vpicone suggested the idea of having it be a different color this time, so people know that the banner has changed 👍

### PR DESCRIPTION
**Pull request by tw15egan**
Closes #1672 

Updates banner to new voting text. Adds in functionality to hide the banner.

#### Changelog

**New**

- New copy in the banner, color tweaks
- `X` button now closes the banner and will not show again

**Changed**

- Style tweaks to account for no banner

cc @janchild for copy suggestions

### CODE REVIEW

**Review by jeanservaas — COMMENTED** [review]
Cool! So fast!

Need to get @janchild to look at the copy, I just pooped that out and @mjabbink had a couple of better suggestions too

And also, I think we'll just avoid the hover on the close 'x' and just keep it to a cursor change. which is what we do in notifications.

**Comment by vpicone** [comment]
image

Mobile issues.

**Review by vpicone — CHANGES_REQUESTED** [review]
image

Mobile issues

**Comment by janchild** [comment]
I wrote some short ones but I feel like the longer ones are better (less brusque). @jeanservaas, is there something we can do with the line spacing to make the longer versions look better?

Every vote counts, America! [Check your registration.](vote.org)

Every vote counts, America! Check your registration. [vote.org](vote.org)


Remember to vote. [Check your registration.](vote.org)

Every vote counts! [Vote, America.](vote.org)

Make your choice. [Vote!](www.vote.org)

Make your choice, America. [Vote!](www.vote.org)

**Comment by tw15egan** [comment]
Keep in mind we will most likely need two variants, one for desktop and one for mobile as Vince has already pointed out an issue with long copy on mobile

**Comment by vpicone** [comment]
@tw15egan we have that at the moment. That's what the initialism stuff was for, maybe you could repurpose that to swap between.

**Review by vpicone — APPROVED** [review]

**Comment by tw15egan** [comment]
@vpicone Yup, making sure we agree on two sets of copy 👍

**Comment by mjabbink** [comment]
Remember to vote. Vote.org

Mobile: Make your choice! vote.org

Desktop: Make your choice, America. vote.org

Desktop: Every vote counts, America! vote.org

Mobile: Every vote counts! vote.org

**Comment by mjabbink** [comment]
But as long as we have one that works in mobile I’m good with most of these!

**Comment by janchild** [comment]
@mjabbink These two are my favorite. I like adding America to the desktop version. 

I agree that it's nice to show the address too, so that you can see it's a .org. We don't need to put the www in front, so it's nice and short! 

Mobile:
Make your choice! [vote.org](https://www.vote.org/)

Desktop:
Make your choice, America! [vote.org](https://www.vote.org/)

**Comment by janchild** [comment]
@tw15egan, we have a winner! See above. ☝️

**Review by emyarod — APPROVED** [review]
looks good to me after copy changes

**Comment by janchild** [comment]
This is still the old copy. The ones to go with are:

Mobile:
Make your choice! [vote.org](https://www.vote.org/)

Desktop:
Make your choice, America! [vote.org](https://www.vote.org/)

Thanks!!

**Review by janchild — CHANGES_REQUESTED** [review]
Need to update to the latest.

**Review by andreancardona — APPROVED** [review]
once copy is updated :)

**Comment by tw15egan** [comment]
Changes should be deployed 👍

**Comment by janchild** [comment]
Hey @tw15egan! One more tweak. Could you please change the exclamation mark to a period in both the desktop and the mobile versions?

Thank you!

**Review by janchild — APPROVED** [review]
🚀

**Comment by tw15egan** [comment]
@jeanservaas once you sign off it's g2g  💥

**Review by jeanservaas — APPROVED** [review]

**Pull request merged**
