### PR TITLE
fix broken storybook example url's in UI-Shell, CheckBox

### PR DESCRIPTION
**Pull request by 2nikhiltom**
Closes https://github.com/carbon-design-system/carbon-website/issues/4291

This PR fixes react storybook broken URLs

#### Changelog

URL's updated

#### Review
Open deploy preview
Verify react storybook pages open for all variants of `UIShell` and `CheckBox` components

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
🎉

**Review by ariellalgilmore — APPROVED** [review]

**Review by Kritvi-bhatia17 — COMMENTED** [review]
Hi Nikhil! Thanks for fixing the broken links.

I just had a quick question—was there a reason behind not adding the respective component’s React overview page link? For example, for the checkbox, the updated link could be this: [Checkbox React overview](https://react.carbondesignsystem.com/?path=/docs/components-checkbox--overview).

**Comment by 2nikhiltom** [comment]
Kritiv,
I observed most of the component's react storybook examples are linked to there default variants

**Review by Kritvi-bhatia17 — APPROVED** [review]
> I observed most of the component's react storybook examples are linked to there default variants

Got it, Nikhil! Thanks for confirming. LGTM 🚀

As a side note, I’ve noticed there are a few more components where the React link in the Code tab is broken. I’m not sure if it’s due to a recent change or something else. I’ll create a separate issue for it for now.

**Pull request merged**
