### PR TITLE
docs(website): update links

### PR DESCRIPTION
**Pull request by abbeyhrt**
Removes some hardcoded links and fixes broken WAI-ARIA link. 

I'm not sure why `yarn.lock` was updated. LMK if I need to discard those changes/

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
I got the same `yarn.lock` changes locally - probably something we lost/forgot when merging `v11` into `main`. So I think it's fine to leave in

**Comment by abbeyhrt** [comment]
@tay1orjones do you know if the format rules changed? I'm getting format errors in a lot of files I haven't touched :/

**Comment by tay1orjones** [comment]
@abbeyhrt Yeah the format check isn't required, so incorrect formatting can slip into the build.

@joshblack has a PR up to fix some of the various errors we have currently in https://github.com/carbon-design-system/carbon-website/pull/2851

**Comment by abbeyhrt** [comment]
@tay1orjones ah okay, thanks for clarifying!

**Review by joshblack — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
