### PR TITLE
[Homepage] Homepage revamp + Banner change

### PR DESCRIPTION
**Pull request by thyhmdo**
Closes #https://github.com/carbon-design-system/carbon-website/issues/4057 and #https://github.com/carbon-design-system/carbon-website/issues/4058

Updating the homepage with new Carbon AI related elements

#### Changelog

**Changed**

- Banner illustration
- Resource card illustration for Design, Develop, and Migration 
- 3-row Resource card group for Other resources

### CODE REVIEW

**Review by jeanservaas — APPROVED** [review]

**Comment by alina-jacob** [comment]
Looks awesome @thyhmdo! ❤️ 🚀

**Comment by mjabbink** [comment]
Did we consider a mobile version?

**Review by alisonjoseph — APPROVED** [review]
This LGTM. Super minor thing but can you delete the old homepage images that are no longer being used? 

I also had a question, is the intention to keep the migrate to v11 resource card, or are we going to add a link to AI once Anna's PR is ready/merged?

**Comment by thyhmdo** [comment]
> This LGTM. Super minor thing but can you delete the old homepage images that are no longer being used?
> 
> I also had a question, is the intention to keep the migrate to v11 resource card, or are we going to add a link to AI once Anna's PR is ready/merged?

Yeah I think we should link it to AI

**Pull request merged**
