### PR TITLE
chore(project): update to carbon v11.0.0

### PR DESCRIPTION
**Pull request by tay1orjones**
Updates the website to the v11 rc

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by aledavila — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
🚀

**Comment by tay1orjones** [comment]
@aagonzales I just updated this with all the latest from `main`. I believe the two largest pieces of work to verify we have correct here are the new accessibility pages and the progress bar work.

@mbgower could you give the deploy preview a once-over to verify the accessibility changes you made came over properly to the v11 site here?

@thyhmdo could you validate the progress bar content came over correctly as well?

Thank you! 🙏

**Comment by tay1orjones** [comment]
Dropdowns are intentionally missing from the website on various pages. They're not working at the moment, I'm still putting together a fix for it and need them commented out for now so the site deploy preview works so we can validate all the other changes.

**Review by aagonzales — APPROVED** [review]
OK I went through and compared the docs and I made some edits for the accessibility tabs directly too this branch. Hope that was ok. Everything else looks good including progress bar docs.

**Comment by mbgower** [comment]
@tay1orjones a couple of things..
1. The preamble is missing from accordion's accessibility.mdx. I didn't seem to have edit access, so you'll need to add the following before the anchor links:
```
<PageDescription>

Design annotations are needed for specific instances shown below, but for the standard accordion component, Carbon already incorporates accessibility.

</PageDescription>
```
2. There's some weirdness in the formatting at the bottom of the checkbox accessibility.mdx page just before the "mixed" code formatting. It's actually on both versions. I can't see anything wrong in the code. Hopefully you can suss!
image

**Pull request merged**
