### PR TITLE
WIP   feat: add layout code page content

### LINKED ISSUE #273: Layout page[Code tab]: Getting started content
Rewrite Getting started content (with attached code) to address multiple entry points for user:

- Happy path: assuming people have carbon-components installed 

- Installing the grid package independently 

Flow diagram:

image

Note: I haven't started a branch for the grid code tab yet but I will this week.

Grid_code_tab

### PR DESCRIPTION
**Pull request by alisonjoseph**
Ref #339 
Closes #273 

preview link https://carbon-website-git-fork-alisonjoseph-layout-code.carbon-design-system.now.sh/guidelines/layout/code

FYI @joshblack @jeanservaas

### CODE REVIEW

**Comment by alisonjoseph** [comment]
I think we need to add collapsible code snippets back to the website theme 😅 these are pretty long

**Comment by alisonjoseph** [comment]
Tagging @joshblack for technical content feedback and @connor-leech for content feedback in general. Images/video still needs to be added.

**Comment by alisonjoseph** [comment]
@joshblack thoughts on what code to show here? 
Screen Shot 2019-09-20 at 8 34 24 AM

> Are we no longer showing gutter as white-space?
Not sure what you mean? I was following the sketch file, but if something else makes more sense let me know 😅

**Comment by joshblack** [comment]
@alisonjoseph just was noting that the columns seem ambiguous as to what is gutter versus what is the column, in the past we were talking about showing white-space for the gutters but another option from the original demo was just a different tint:

image

For the code snippets for the rail, maybe something like:

```html
<aside class="side-nav">
  <!-- Toggle side-nav--expanded class above, or add it back in -->
</aside>
<div class="bx--grid">
  <!-- ... -->
</grid>
```

**Comment by alisonjoseph** [comment]
So adding the shading we're showing here to all the examples to show the gutter?
Screen Shot 2019-09-20 at 12 06 17 PM

**Comment by alisonjoseph** [comment]
closing in favor of #377

**Comment by alisonjoseph** [comment]
closing in favor of #377

**Comment by jeanservaas** [comment]
Just noticed a couple of things looking at the grid demos, the side margin jumps from 32px to 40px causing the edge of the grid to be misaligned with the paragraph above.

- Can we keep it at 32px so there's a nice even 16px border around the grid at the top and the bottom?


**it's correct (32px) up til about 1176px:**

image

**Then the margin jumps to 40px**

image

- Also, right now the type within the grid cells has a 16px margin, could we reduce that to 8px top 8px side to help with breakage at smaller breakpoints

image


### Responsive breakpoints example:

- everything just stacks at table to mobile for responsive breakpoints, which doesn't really make sense

image


this is my fault for not specifying a table and mobile behavior but since tablet has an 8 col grid and mobile has a four column grid, this is how the "responsive columns" demo should behave at tablet and mobile

image

**Pull request closed without merging**
