### PR TITLE
(docs) Carbon Labs on core

### PR DESCRIPTION
**Pull request by aagonzales**
Closes https://github.com/carbon-design-system/carbon-website/issues/4181

#### Changelog

**Changed**

- Added "Carbon Labs" section on "Contributing/Getting Started" page
- Added "Carbon Labs" section under "Discovery" on PDLC page

### CODE REVIEW

**Comment by aagonzales** [comment]
@alisonjoseph Could you help me figure out why my build is failing?

**Comment by alisonjoseph** [comment]
@aagonzales should be good now, I pulled it down and ran `yarn format`

**Comment by aagonzales** [comment]
Thank you! I'll remember to try that first next time

**Comment by aagonzales** [comment]
@alisonjoseph sorry to bug you again, but could you restart the vercel build?

**Review by laurenmrice — APPROVED** [review]
Looks good to me!

Just a small comment on the PDLC > Discovery criteria > "Added to Carbon Labs" section. Wondering if the heading here should instead say "Add to Carbon Labs" or "Adding to Carbon Labs". It's up to you though!

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
