### PR TITLE
(docs) Content template: updated style sections

### PR DESCRIPTION
**Pull request by aagonzales**
Closes https://github.com/carbon-design-system/carbon-website/issues/4180

Updated the content template to include a section for `Style tab with multiple variants`

#### Changelog

**New**

- Added "Style template: for components with multiple variants" 
- Added an "AI presence" template section to both "one variant" and "multiple variants" sections (style tab only)

**Changed**

- Updated "Style template: for components with one variant" to be exclusive about a single variant. I removed any information that was talking about variant structure. 
- Reformatted the instructional comments to be more skimmable.

### CODE REVIEW

**Review by laurenmrice — APPROVED** [review]
I think this looks really good, and its working well for my Pagination Style tab docs! 

Going to approve and I think one thing you could add to the Typography section is to be more explicit about how to treat different variants that have different type specs, since Pagination ran into that issue.

**Review by Kritvi-bhatia17 — COMMENTED** [review]
Hi @aagonzales! This looks great. 🔥
I just wanted to confirm one small thing: the current docs mention "interactive state," but in the updated document templated, it says "interactive state color." Which one is correct? As this could lead to changes in almost all the components' docs.

Screenshot 2024-08-16 at 12 11 04 PM
Screenshot 2024-08-16 at 12 18 00 PM

**Comment by aagonzales** [comment]
@Kritvi-bhatia17 oh yes good catch. I think Aubrey changed it to "interactive state color" the last time she updated the template so I just kept it that way. You are right to point out its inconsistent with what's showing in most docs. We probably need to do a content scrub to make sure all our style tabs will reflect the new template.

**Review by Kritvi-bhatia17 — APPROVED** [review]
LGTM! 🎉

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
