### PR TITLE
Update usage.mdx

### PR DESCRIPTION
**Pull request by denniskigen**
Some grammatical suggestions for the Expandable section under the `Data Table` component usage [page](https://www.carbondesignsystem.com/components/data-table/usage).

### CODE REVIEW

**Review by jillianhowarth — APPROVED** [review]
Thanks for the fixes!! 🙂

**Review by emyarod — APPROVED** [review]

**Comment by denniskigen** [comment]
> Thanks for the fixes!!

Glad to help. Loving Carbon so far. Thanks for all the amazing work!

**Review by andreancardona — APPROVED** [review]
@denniskigen looks good!  🎉

**Review by tw15egan — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
