### PR TITLE
Update angular tutorial

### PR DESCRIPTION
**Pull request by cal-smith**
Supersedes #771

- updates the text so the output of each step matches
- enables the tutorial in the left nav
- fixes a few minor typos
- pushes out the completion date to around the end of Q1 ... We plan to announce the tutorial's availability on our community call next week, so it would be nice to give folks a chance to actually complete it and get something for it

### CODE REVIEW

**Comment by vpicone** [comment]
Tagging in @mattrosno we might want React to be the first in the list since it's the canonical implementation?

**Comment by mattrosno** [comment]
Yes I'll review and also make sure the SurveyGizmo is good to go for the Acclaim form.

**Comment by cal-smith** [comment]
>we might want React to be the first in the list since it's the canonical implementation?

I mean everything else is alphabetical so that's what I went with 🤷‍♂ We can totally switch it around, though I'm not sure lexicographical ordering implies canonicalness 🙂

**Comment by cal-smith** [comment]
Hey @mattrosno any updates?

**Comment by vpicone** [comment]
@cal-smith @mattrosno we good to merge here?

**Comment by mattrosno** [comment]
@vpicone I will review today.

**Pull request merged**
