### PR TITLE
Fix experimental date picker styles on website

### LINKED ISSUE #376: Bug: experimental date picker calling wrong menu on website.
Experimental Date Picker menu is not correct. Not sure why its not calling the correct one. It was correct in the dev environment. 

image

Should be: 
image

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #376

Adds style overrides to get date picker rendering correctly on website.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Will double check and see if there is a way to avoid !important before merging.

**Comment by alisonjoseph** [comment]
Looks like it wasn't needed 😉

**Comment by asudoh** [comment]
Great news - Thanks @alisonjoseph for taking a look at this!

**Comment by alisonjoseph** [comment]
@aagonzales can you check that the date picker is behaving as expected and I didn't miss anything style wise. http://carbon-website-random-impressive-mongoose.stage1.mybluemix.net/experimental/date-picker/code

_I just noticed its jumping to the bottom of the page for some reason when you select the range, so will look in to that._

**Comment by aagonzales** [comment]
It needs a fit row of dates. The whole month should be viewable in one window. Notice this one only goes up to the 24th. But besides that the rest of it looka correct.

image

**Comment by marijohannessen** [comment]
Alright, I figured out the problem so I'm going to make a PR to carbon-components with a fix ASAP.

**Comment by marijohannessen** [comment]
Alright, here's the PR that fixes the issue https://github.com/IBM/carbon-components/pull/1485

**Pull request merged**
