### PR TITLE
chore(release): update carbon to v10.10.0-rc.2

### PR DESCRIPTION
**Pull request by joshblack**
Update website to v10.10.0-rc.2 of Carbon.

#### Changelog

**New**

**Changed**

- Update website to v10.10.0-rc.2 of Carbon

**Removed**

### CODE REVIEW

**Comment by sstrubberg** [comment]
Looks like the build is error'ing out.

**Comment by vpicone** [comment]
@joshblack did we remove any readme content for the code component? Weird error :/

**Comment by tw15egan** [comment]
@vpicone We removed most of the old outdated documentation files that hadn't been updated since like v6/v7 and before we were using `mdx` files. If we want to keep that information up to date we can move it to the website side of things rather than in the component package. 

https://github.com/carbon-design-system/carbon/pull/5277
https://github.com/carbon-design-system/carbon/issues/5237

I can throw up a PR for the website that removes the documentation blocks.

**Comment by joshblack** [comment]
@vpicone right, this is due to the metadata changes correct?

**Comment by vpicone** [comment]
@joshblack ah right, I have a branch to handle those changes somewhere 🕵️‍♂️

**Comment by vpicone** [comment]
Gonna close this in favor of https://github.com/carbon-design-system/carbon-website/pull/970

Grats on the release!

**Pull request closed without merging**
