### PR TITLE
docs: update notification images with correct content

### LINKED ISSUE #3898: [Docs] notification docs need content and image updates to reflect IBM style guidelines
## Acceptance criteria 
Content guidance is needed for notifications and graphical examples should match the IBM Style guidelines.

- [x] **Update Usage tab written content:** Update written guidance with correct content from IBM style.
- [x] **Update Usage and Style tab images with incorrect content:** Like periods in titles, incorrect title naming, punctuation problems, etc.

-----
**Questions from issue author**
1. There doesn’t seem to be explicit guidelines about how [notifications](https://carbondesignsystem.com/components/notification/style) should be worded. Are we to use these "Informational notification", "Error notification", "Warning notification", and "Success notification" as titles?
    - No, these words were just examples to describe the kind of each notification that we offer.

image

----

2. Are we supposed to use complete sentences and punctuation in notification titles or no?
    - Title: We do not use a period to end a title in the notification.
    - Body content: We do use a period to end the body content which should be in sentence form. 

image

----

3. Are exclamation marks ok to use? Typically supposed to avoid them (IBM Style).
   - No, we should not use exclamation marks. 

image

----

4. Or even punctuation after incomplete sentences (notice how the visual style is different too). Should titles be complete sentences with verbs and with/without punc or no?
  - If we are recommending users not use a period in titles, then titles should not be full sentences and should be more concise.

image

### PR DESCRIPTION
**Pull request by laurenmrice**
Closes #3898 

- Updated all notification images on the Usage and Style tabs for the Notification component, that displayed incorrect content.

---

**Changed**

- Updated various images and corrected content.

**Removed**

- Removed some old images.

### CODE REVIEW

**Comment by laurenmrice** [comment]
@thyhmdo @tw15egan this PR is ready for review when you get a chance. Thanks!

**Review by thyhmdo — APPROVED** [review]
Looks great! There are a few questions but this is a separate issue. 

- In the code, when I resize the browser, the Action button stays at the bottom, but it should stay inline and top with the text, right?
- Also, when do you use the body text right next to the Title vs placing it below the title?

https://github.com/carbon-design-system/carbon-website/assets/77697351/4b1e065b-ec99-4b65-9ec5-2b2381073fb5


image

**Comment by laurenmrice** [comment]
- The inline notification should not push the button to another line, because then it looks more like a toast. It should be responding like your last image.

- The single line versus multi line inline notification is mostly up to the user and what will best fit the content at hand. Single lines are good for content that can fit on a single line at most breakpoints and when it is placed in condensed or compact spaces.

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
