### PR TITLE
fix(dropdowns): use correct v11 `size` prop

### PR DESCRIPTION
**Pull request by tay1orjones**
Part of https://github.com/carbon-design-system/carbon-website/issues/2785

#### Changelog

**Changed**

- Update our usage of dropdowns to use the new size values from v11. 

#### To Review

- View component demos, the dropdowns should now be the proper size
- View the icon library page, the dropdown in the search filter bar should now be properly sized.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by tay1orjones** [comment]
I pushed an update, I believe the component demo sizes are correct so I reverted them. Added a style fix for the border between dropdowns on the component demo and the width of the dropdowns should now be correct.

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**Live demo**
- The live demo dropdowns that sit on top of the live demo have increased in width and are too long. They should span the width of the demo window only. They should not span the right panel.
- The live demo dropdowns are also missing a vertical rule between them

To be:
Screen Shot 2022-03-28 at 5 34 40 PM

Current in this PR:
Screen Shot 2022-03-28 at 5 34 26 PM

---------

**Icons (library tab) and Pictograms (library tab)**
- I think there were some overrides set on the dropdowns on both of these pages to match the styling of the Search input that it sits next to. Looks like we need to exclude the $border-strong bottom-border in these scenarios. 

To-be:
Screen Shot 2022-03-28 at 5 41 14 PM


Current in this PR:
Screen Shot 2022-03-28 at 5 41 04 PM

**Comment by jnm2377** [comment]
The color palette dropdown is also shorter than the content switcher now

Screen Shot 2022-03-29 at 10 08 45 PM

**Review by laurenmrice — APPROVED** [review]
✅

**Review by jnm2377 — APPROVED** [review]
unrelated - but as soon as I opened the deploy preview I was like WOAHHH the homepage looks so nice with the light banner updates!

**Pull request merged**
