### PR TITLE
fix(typography): add expressive-heading-06

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon-website/issues/1864

- Updates type scales to use correct token names
- Adds `expressive-heading-06`

### CODE REVIEW

**Comment by tw15egan** [comment]
@joshblack WOuld definitely make these updates easier in the future. Not sure how this page will be put together with the Gatsby theme but something for @vpicone and @alisonjoseph to look into

**Comment by alisonjoseph** [comment]
100% would love all the elements data to get pulled in directly to the website. Hopefully we can prioritize it in a future project.

**Comment by jeanservaas** [comment]
Hey @tw15egan soweee looks like the preview link failed. wah wah

**Comment by tw15egan** [comment]
@jeanservaas https://5d4b1e1ad17318397ac3e3fb--carbon-website.netlify.com/guidelines/typography/expressive

**Comment by jeanservaas** [comment]
LGTM!

**Pull request merged**
