### PR TITLE
Docs: v11 color token updates for Content switcher component

### PR DESCRIPTION
**Pull request by thyhmdo**
This PR updates the color tokens on the Style tab for the content switcher component.

### CODE REVIEW

**Comment by aagonzales** [comment]
Yes, this needs to be switched to the v11 branch @emyarod @thyhmdo

**Review by aagonzales — APPROVED** [review]
The token names look good 👍

**Comment by emyarod** [comment]
got it! for future reference, you can change the target branch by clicking "Edit" next to the PR name and then selecting the branch

image

image

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by thyhmdo** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by andreancardona — APPROVED** [review]
looks good!

**Pull request merged**
