### PR TITLE
docs: update steering committee info

### PR DESCRIPTION
**Pull request by alisonjoseph**
Update description for steering committee on Partners page
Add photo of Marko Thornhauer

### CODE REVIEW

**Comment by mjabbink** [comment]
Looks good to me. @jeanservaas should weigh-in.

👍

**Review by aledavila — APPROVED** [review]
Lgtm

**Review by jeanservaas — COMMENTED** [review]
Hey girl can we also add this photo of Marko Thornhauer?

thornhauer-marko

**Comment by alisonjoseph** [comment]
done @jeanservaas

**Comment by mjabbink** [comment]
Thanks @alisonjoseph and @jeanservaas. Marko will appreciate his mug being up on the glass.

👍

**Comment by alisonjoseph** [comment]
@jeanservaas is this good to merge, or does it need any design tweaks?

**Comment by mjabbink** [comment]
I think you can rock this. @jeanservaas

**Pull request merged**
