### PR TITLE
feat: remove component index

### PR DESCRIPTION
**Pull request by andreancardona**
Closes # https://github.com/carbon-design-system/carbon-platform/issues/1439

Updates to `Community Assets` content: https://carbondesignsystem.com/community/overview/

- Removed `ComponentIndex` since it no longer needed

## Testing: 

- [ ] Confirm there are no breaking changes
- [ ] Make sure updates follow Figma design: https://www.figma.com/file/nwqobPLCIzp2O6CTprT4zh/CommunityAssets?node-id=23%3A797

### CODE REVIEW

**Review by aagonzales — COMMENTED** [review]
Everything looks good except the image on the overview tab doesn't look like its spanning the full 12 columns at the larger breakpoints

image

**Review by jeanservaas — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]
Yes, that fixed it. Looks good now!

**Review by tay1orjones — APPROVED** [review]
🔥

**Review by tay1orjones — COMMENTED** [review]
Actually, on second thought - should we add a redirect for the page/tab that was deleted?

Since moving the site to GH Pages redirects are done in one of the gatsby config/ssr files at the root

**Pull request merged**
