### PR TITLE
Update loading.md

### PR DESCRIPTION
**Pull request by claycrenshaw**
Add Index links

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Did you mean to make this PR to master or should it be v10?

**Comment by claycrenshaw** [comment]
Ah, good catch! Supposed to be v10. What's the best way to correct this? @alisonjoseph

**Comment by lovemecomputer** [comment]
@claycrenshaw have a couple screenshots: u can click the top-right edit button on the issue, and a dropdown will appear to select which base branch u want to change it to!

screen shot 2019-01-14 at 10 10 45 am
screen shot 2019-01-14 at 10 10 51 am

**Comment by alisonjoseph** [comment]
You can switch the branch at the top, but make sure the content is still up to date. If you originally edited a file on master instead of v10 they might not be in sync anymore.

**Comment by alisonjoseph** [comment]
@claycrenshaw please re-open from v10 branch.

**Comment by claycrenshaw** [comment]
Changed the base re: Audrey's hint. Thanks!

**Comment by claycrenshaw** [comment]
Er, maybe that wasn't the right way to do it. Going to just re-open a fresh PR from v10. Thanks :)

**Pull request closed without merging**
