### PR TITLE
feat(type): major rewrite of typography section

### PR DESCRIPTION
**Pull request by sstrubberg**
co-authored: @janchild

This PR is for the new guidance for expressive and productive type sets. 

Issue for component work: https://github.com/carbon-design-system/carbon/issues/8934

#### Notes from Scott:

- I took the `typeScale` and `typeSets` JSON and moved them into their own individual files to make `TypesetStyle` more readable.
- Lots of renaming style tokens to match the spec. Pretty much everything got a renaming.
- Refactored `TypesetStyle` to allow for a boolean prop to turn the old header off and on. Even though there's no use-case for the old header, I didn't have the heart to remove the code, thinking we might bring it back someday. Added defaults of `breakpointControls={false}` & `header={false}` to make the component easier to implement.

##### Testing

Head to /guidelines/typography/type-sets and make sure everything is in order.

### CODE REVIEW

**Comment by janchild** [comment]
@sstrubberg Just fixed a few little things in each of the three pages. Will check after the build, but we should be good after this.

**Review by janchild — APPROVED** [review]

**Comment by mjabbink** [comment]
@janchild This is missing something IDL about it. This current intro text could be the language used for anyone but what can make a touch more about our approach?

What about something like?

The approach to our typographic system uses IBM Plex as the typeface. It has been carefully engineered with suitable scales and weights to help create clear hierarchies and organize information that guides users through IBM products or experiences.

or

Our approach to the typographic system uses IBM Plex as its typeface. It has been carefully engineered with suitable scales and weights to help create clear hierarchies and organize information that guides users through IBM products or experiences.


or feel free to stab at this further.

**Comment by janchild** [comment]
> @janchild This is missing something IDL about it. This current intro text could be the language used for anyone but what can make a touch more about our approach?
> 
> What about something like?
> 
> The approach to our typographic system uses IBM Plex as the typeface. It has been carefully engineered with suitable scales and weights to help create clear hierarchies and organize information that guides users through IBM products or experiences.
> 
> or
> 
> Our approach to the typographic system uses IBM Plex as its typeface. It has been carefully engineered with suitable scales and weights to help create clear hierarchies and organize information that guides users through IBM products or experiences.
> 
> or feel free to stab at this further.

Love it! Thanks, @mjabbink! Will do!

**Comment by mjabbink** [comment]
Maybe better to add “styles” in the there too.

... scales, **styles**, and weights...

**Comment by mjabbink** [comment]
There is a spacing issue here.
https://carbondesignsystem-git-fork-sstrubb-19b965-carbon-design-system.vercel.app/guidelines/typography/overview/#scale

Should be more space between image and text

Screen Shot 2021-09-29 at 5 25 13 PM

**Comment by mjabbink** [comment]
I’ve mention before to update the login image with a more recent illustration style. That illustration is not really IDL so not a good example of illustration. Maybe @thyhmdo or @kingtraceyj can help replace this with something more current. See Cloud or Security designs which use some recent illustration designs. 


Screen Shot 2021-09-29 at 5 27 31 PM

**Comment by mjabbink** [comment]
@janchild in https://carbondesignsystem-git-fork-sstrubb-19b965-carbon-design-system.vercel.app/guidelines/typography/type-sets

current intro:
Carbon uses type tokens to manage typography, and these tokens sit within two type sets: expressive and productive.

Maybe something like...

Carbon uses clear naming approach and type tokens to manage typography across complex and layered design experiences, and these tokens sit within two type sets: expressive and productive.

or

Carbon uses clear naming approach and type tokens to manage typography across complex and layered layouts and patterns, and these tokens sit within two type sets: expressive and productive.

**Comment by mjabbink** [comment]
In “Typesets” the outer columns with specs  within the table is off Grid. All of it is off grid but @alisonjoseph has a fix under way to sort that out but even with that upcoming fix that last spec typography is not on the column.

Screen Shot 2021-09-29 at 5 40 58 PM

**Comment by mjabbink** [comment]
@janchild in “Code” intro again.

current:
Type is a core part of any offering. Use the Carbon type package to leverage IBM Plex across your product.


maybe something like...


Type is a core part of any offering and critical to how brands express and communicate throughout any experience. Use the Carbon type package to leverage IBM Plex and create effective typography across your product more easily.

or

Type is a core part of any offering and critical to how brands express and communicate throughout any experience. Use the Carbon type package to leverage IBM Plex and create effective typography for your users and across your products.

**Comment by alisonjoseph** [comment]
@sstrubberg Let me know if you want to pair up on the grid alignment for this, but after applying my fix for overall grid, looks like these two styles below need to get removed. 
Screen Shot 2021-09-30 at 8 45 09 AM

also looks like `bx--typeset-example-specs` and `bx--typeset-example-description` are not on the grid. I don't have the spec in front of me, but looks like its 7.5 cols and 4.5 cols right now. Do we want 7/5 or 8/4?
.
Screen Shot 2021-09-30 at 8 49 30 AM

One last thing to make sure we don't forget because we are removing / changing urls people may have bookmarked. 
- [ ] Add redirect from Productive and Expressive pages

**Review by abbeyhrt — APPROVED** [review]

**Review by janchild — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]
🚀

**Comment by mjabbink** [comment]
@janchild need to add “a” in “Carbon uses a clear naming approach...”

I had left it out on my copy suggestions above my accident.

Carbon uses a clear naming approach and type tokens to manage typography across complex and layered layouts and patterns, and these tokens sit within two type sets: expressive and productive.

**Comment by mjabbink** [comment]
@jeanservaas and @theiliad Should we not include any details for the condensed which is used in Carbon Charts?

**Pull request merged**
