### PR TITLE
Add dotcom components

### PR DESCRIPTION
**Pull request by shinytoyrobots**
Adds 18 more components from the dotcom library to the community index.

Need to automate this. 👀

### CODE REVIEW

**Review by joshblack — COMMENTED** [review]
Just wanted to confirm, were the images removed in the diff intentional changes that we should be reviewing too? :eyes:

**Review by joshblack — APPROVED** [review]

**Review by jeanservaas — COMMENTED** [review]
Hey Robin, could you actually update ALL the images in the index. I tweaked almost all the other ones too. They should all have the same names so it should be a simple drag and drop. 

The package that I sent you in slack and the most recent one I posted in that (other?) PR had the updated files. If you think it's cleaner, I guess I could make another PR for that update but my local build's wonk.

Also, something happened here to the logo grid, let me see what's wrong and update it. 

image

Here is the updated logo grid

logo_grid

**Comment by shinytoyrobots** [comment]
@jeanservaas - all the images for the dotcom components that were already in the index were updated in the other PR - this one is just for the components that hadn't been added yet. I just merged the master updates back into this branch, which should then show **all** of the dotcom thumbnails.

Submitted the update to the logo-grid thumbnail, too, so should be good to go once the preview builds.

**Review by aledavila — APPROVED** [review]

**Review by jeanservaas — APPROVED** [review]
lgtm!

**Pull request merged**
