### PR TITLE
feat: add halloween easter egg

### PR DESCRIPTION
**Pull request by jnm2377**
#### changelog

- update gatsby theme dependency
- change feedback btn
- ~add toggle (ghost) button to footer~
- ~add halloween classname and context to Layout.js~
- ~add a bunch of halloween style overrides for sidenav, header, page tabs and link focus~

no halloween easter egg. womp womp 🤷‍♀️ 

SHOUT OUT TO @aledavila AND @joshblack for pair programming with me!

### CODE REVIEW

**Comment by jeanservaas** [comment]
Girrrrrrrl!

Love the idea of halloween Easter eggs and don't want to be the heavy. 

I don't mind the bat so much even though it's not an IDL icon. But I know the orange is going to be a NO NO

image

Also, the "Happy Halloween" ghost button took me a while to find and because when it's not hovered, it's not aligned with the other type below it.

image

Then the only payoff is the header, which 1) becomes an alert color and 2) doesn't seem like enough of a punch.

Let's see what @mjabbink 

I feel like I get the asshole award here.

**Comment by mjabbink** [comment]
@jnm2377 I will provide a bat that is more inline with icons rules.

**Comment by mjabbink** [comment]
Let’s NOT change the header to orange.

**Comment by jnm2377** [comment]
@jeanservaas the navigation (active) colors and focus outlines also change to orange.

**Comment by jnm2377** [comment]
We'd be happy to get a design for a halloween theme, this is just put something together at our dev hackathon yesterday. I don't quite remember what the halloween theme that Tyler and Alison did in the past looks like, but we wanted to do something like that.

**Comment by jnm2377** [comment]
Also, as far as the button, we did want it to be an easter egg, and the whole idea of that is for it to be pretty hidden, which is why we made it a ghost button. Open for any other ideas that can also be hidden somewhere.

**Comment by mjabbink** [comment]
Bat options following the grid and style guidance.

Screen Shot 2020-10-22 at 12 47 56 PM

**Comment by jnm2377** [comment]
@mjabbink do we have an svg for those?

**Comment by mjabbink** [comment]
@jnm2377 Making SVGs now. Standby.

**Comment by mjabbink** [comment]
Screen Shot 2020-10-22 at 12 54 50 PM

**Comment by mjabbink** [comment]
What about the Bee bat larger and leave the smile face alone?

Screen Shot 2020-10-22 at 12 56 57 PM

**Comment by mjabbink** [comment]
Get some garishness and ghoulishness going

**Comment by mjabbink** [comment]
@jeanservaas see above

**Comment by mjabbink** [comment]
Quite version

**Comment by mjabbink** [comment]
@conradennis made this which would be great for the feedback face.

Screen Shot 2020-10-22 at 2 09 28 PM

**Comment by jnm2377** [comment]
^ LOVEEE that monster face! @mjabbink

**Comment by mjabbink** [comment]
@jeanservaas @jnm2377 What do you think of Bee bat in Feature card and Frankenstein in the Feedback button?

Also garish and ghoulish colors.

——————

Screen Shot 2020-10-22 at 1 21 15 PM

**Comment by mjabbink** [comment]
[monster.svg.zip](https://github.com/carbon-design-system/carbon-website/files/5424984/monster.svg.zip)

**Comment by mjabbink** [comment]
@jnm2377 sending SVGs soon. Conrad is tinkering on the monster

**Comment by mjabbink** [comment]
[bee-bat.svg.zip](https://github.com/carbon-design-system/carbon-website/files/5425119/bee-bat.svg.zip)
[monster.svg.zip](https://github.com/carbon-design-system/carbon-website/files/5425120/monster.svg.zip)

**Comment by mjabbink** [comment]
Screen Shot 2020-10-22 at 2 01 26 PM

**Comment by jnm2377** [comment]
@mjabbink those get started feature cards on the homepage are images, do you know who created them and can edit them to have the orange stripe/bat? Idk how to do that/don't have any photo editing software.

**Comment by mjabbink** [comment]
Not sure what the button in the footer does?

**Comment by mjabbink** [comment]
@jeanservaas or @laurenmrice Can you provide the svg feature card images to @jnm2377

**Comment by mjabbink** [comment]
getting-started-designers


getting-started-developers

**Comment by mjabbink** [comment]
getting-started-designers


————

getting-started-developers

**Comment by jnm2377** [comment]
@mjabbink the button in the footer changes the theme to halloween. I updated it so that it doesn't have an orange nav, rather just keeps everything dark and the navigation styles are orange. I was having a hard time changing the images in the homepage feature cards when the halloween theme is set, so I just changed the bg color of one of the callouts instead. However, if we wanted the halloween images in the feature card, we can still do that, it just won't be toggle-able like the rest of the theme. I also would need those updated images. The feature cards use art direction, so we'd need an image for mobile, tablet and desktop.  

You should be able to see in the preview how the halloween theme changes:



Thoughts??? cc: @jeanservaas

**Comment by mjabbink** [comment]
I misunderstood the theme switching. I was suggesting just swapping out the two images for the week. Also the face icon for feedback. I’m less into the theme switching as that big hit of orange is not great especially with the blue link.

**Comment by mjabbink** [comment]
@jeanservaas @jnm2377 Could we just swap out the tab and left nav use of Blue for Orange for the week. As well as swap the two images on the home page. I think that would be enough. It’s more controlled but fun and expressive.

**Comment by mjabbink** [comment]
So because I’m confused about what we’re doing I’m outlining what I think we’re doing

- [ ] — swap monster face with wink face in feedback button

- [ ] — replace both images on homepage (Start Designing and Start Developing)

I think that is all we need to do for the week. I think the theme switcher might be too invisible to users and the above will hit anyone coming to the site or engaging the feedback dialogue.

**Comment by jeanservaas** [comment]
Yup agree with @mjabbink, no switcher and no orange banners. 

So we're half way there. We have Frankenstein guy in the feedback, all we still need to do then is just swap those two start designing and start developing images which mike attached above. Should be a fast swap and then we can leave it up all week. 

Wondering if we can get this up by tomorrow so we can have it up for the week?

**Comment by jnm2377** [comment]
@jeanservaas I can update the PR as soon as I have all 6 images. Those images are using art direction, so we need one for desktop, tablet, and mobile, for each.

**Comment by jnm2377** [comment]
> @jeanservaas @jnm2377 Could we just swap out the tab and left nav use of Blue for Orange for the week. As well as swap the two images on the home page. I think that would be enough. It’s more controlled but fun and expressive.

so to be clear, we don't want to have orange on the tabs/side navs when they're active instead of blue?

**Comment by jnm2377** [comment]
If the issue is that the theme isn't obvious, I just want to point out that that's the point of an easter egg. It's what we did before for our halloween theme. We had a hidden button that activated it, if I recall correctly.

**Comment by jeanservaas** [comment]
@jnm2377 yes, the idea is not to make it an Easter egg this year, but just put it out there for a week.

**Comment by mjabbink** [comment]
The desktop images were supplied above so we need tablet and mobile only.

**Comment by mjabbink** [comment]
getting-started-developers-mobile

**Comment by mjabbink** [comment]
@jnm2377 

[desktop.zip](https://github.com/carbon-design-system/carbon-website/files/5439615/desktop.zip)


[getting-started-developers-tablet.png.zip](https://github.com/carbon-design-system/carbon-website/files/5439672/getting-started-developers-tablet.png.zip)


[getting-started-developers-mobile copy.png.zip](https://github.com/carbon-design-system/carbon-website/files/5439673/getting-started-developers-mobile.copy.png.zip)

**Comment by mjabbink** [comment]
@jnm2377 

[getting-started-designers-tablet.png.zip](https://github.com/carbon-design-system/carbon-website/files/5439696/getting-started-designers-tablet.png.zip)


[getting-started-designers-mobile.png.zip](https://github.com/carbon-design-system/carbon-website/files/5439697/getting-started-designers-mobile.png.zip)

**Comment by jnm2377** [comment]
Ok. I just wanted to verify the final decision before undoing things bc it wasn't easy to do in the first place. For context, though @jeanservaas, the easter egg was not just my idea. It was something a lot of people wanted, which is why we put dev effort into it via our hackathon: 

Screen Shot 2020-10-26 at 10 40 25 AM

**Comment by mjabbink** [comment]
@jnm2377 @jeanservaas Whatever is the most efficient and can have an effect on the most people. The latest proposal of monster face and halloween images seems to be fast to change and will be seen by every visitor versus minimal who catch the Easter egg. Let’s proceed with this please.

**Comment by mjabbink** [comment]
@jnm2377 Looks good to me. I think this will be great. For the record I was not opposed to changing the blue to orange for the tabs and left nav select stripes. But totally cool with this and seems the most efficient.

**Comment by jnm2377** [comment]
Welp.. I already undid the theme changes (which controlled the orange tabs) bc it seemed like a no from design. So let's just merge as is. Thanks for the work on the svgs.

**Comment by tw15egan** [comment]
Seeing this in the footer on the preview build, not sure if that's what you're seeing locally 

Screen Shot 2020-10-26 at 10 30 34 AM

**Review by joshblack — APPROVED** [review]

**Comment by jnm2377** [comment]
> Seeing this in the footer on the preview build, not sure if that's what you're seeing locally
> 
> Screen Shot 2020-10-26 at 10 30 34 AM

That's so weird! It looked fine locally.

**Comment by mjabbink** [comment]
@jeanservaas @jnm2377 Monor thing and low priority but this scale is better for mobile version of bee bat. 

[getting-started-developers-mobile.png.zip](https://github.com/carbon-design-system/carbon-website/files/5440449/getting-started-developers-mobile.png.zip)

**Comment by tw15egan** [comment]
@jnm2377 if you're not seeing it locally, then I'm guessing it's just a weird Vercel thing 🤷

**Review by tw15egan — APPROVED** [review]

**Comment by jnm2377** [comment]
@tw15egan phewww! ok. Yeah, I doubled checked and everything's working fine locally. 
Screen Shot 2020-10-26 at 12 45 26 PM

**Comment by jnm2377** [comment]
@mjabbink updated the image

**Pull request merged**
