### PR TITLE
docs: add francinelucca to team page

### PR DESCRIPTION
**Pull request by francinelucca**
#### Changelog

**Changed**

- Added Francine Lucca entry to carbon team grid (src/pages/all-about-carbon/the-team.mdx)

image

### CODE REVIEW

**Comment by francinelucca** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by francinelucca** [comment]
recheck

**Comment by francinelucca** [comment]
recheck

**Review by alisonjoseph — APPROVED** [review]
Welcome 🎉

**Review by joshblack — APPROVED** [review]

**Review by aledavila — APPROVED** [review]
Yaaay welcome

**Review by laurenmrice — APPROVED** [review]
🎉

**Review by tay1orjones — APPROVED** [review]
🎉

**Pull request merged**
