### PR TITLE
update(List): add info on List expressive 

### PR DESCRIPTION
**Pull request by shixiedesign**
Related #

Website update part 2/3

carbon-design-system/carbon#8301

#### Changelog

**Changed**

- Style / Typography to mention the larger list. 
- **FYI all classnames are guesswork and should be verified by devs!**

### CODE REVIEW

**Comment by shixiedesign** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by shixiedesign** [comment]
recheck

**Review by dakahn — APPROVED** [review]

**Review by emyarod — APPROVED** [review]

**Review by janchild — APPROVED** [review]

**Review by janchild — CHANGES_REQUESTED** [review]
I am going to make a content update first thing tomorrow. Just need to check one thing!

**Review by janchild — APPROVED** [review]
Changes in for type tokens and new intro paragraph for Typography section. This is good to go with the release.

**Pull request merged**
