### PR TITLE
Update images in community Create pattern

### PR DESCRIPTION
**Pull request by andrea-gm**
Closes #

Deleting unused images and updating Side Panel images, per previous feedback. Somehow these updated images did not make it in when @chloepoulterdesign 's PR was merged. 

#### Changelog

**New**

- N/A

**Changed**

- Side panel images

**Removed**

- Unused images

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
This image needs to be using the Magenta 60 color (#D12771) instead of Magenta 80.
Screen Shot 2021-01-13 at 3 22 23 PM

**Comment by andrea-gm** [comment]
@laurenmrice [all the images](https://carbondesignsystem-rie5vef65.vercel.app/community/patterns/create-flows) in the pattern are using the darker color. So they all need to be updated, correct?

**Comment by laurenmrice** [comment]
It was just for this one because it is not on a dark background (like the modal overlay images).

**Comment by andrea-gm** [comment]
There are 2 others that are not on a dark background. See the [full page Create](https://carbondesignsystem-rie5vef65.vercel.app/community/patterns/create-flows#anatomy-of-a-full-page). And if you scroll up a little, same for the wide tearsheet. Should we revise these as well?

**Comment by laurenmrice** [comment]
yes 👍🏻 @andrea-gm

**Comment by ampersandrew-IBM** [comment]
@andrea-gm 

Image updated: https://ibm.box.com/s/m34t3z7jupbu4ob3mwnwmvkxwgkhg9pj

**Review by laurenmrice — APPROVED** [review]
Thanks for updating this! Looks good! 🙌🏻

**Pull request merged**
