### PR TITLE
chore(demos): remove vanilla links from all component demos

### PR DESCRIPTION
**Pull request by tay1orjones**
Ref https://github.com/carbon-design-system/carbon/issues/10889

#### Changelog

**Added**
- Add prettier ignore blocks around the component demos. Automatically applied formatting malformed the ComponentDemo internal content causing the build to fail

**Removed**

- Remove vanilla links from all component demos

### CODE REVIEW

**Review by laurenmrice — APPROVED** [review]

**Review by jnm2377 — APPROVED** [review]

**Review by aledavila — APPROVED** [review]

**Comment by joshblack** [comment]
bump @tay1orjones when you get a sec, just some merge conflicts are preventing this from being merged 👀

**Comment by tay1orjones** [comment]
I really messed the merge up somehow. Will try and fix.

**Comment by joshblack** [comment]
@tay1orjones seems like there is a weird deploy issue happening where it's failing in build 🤔

**Comment by tay1orjones** [comment]
@joshblack Yikes, I'm not sure what's happened here. I went ahead and made a whole new PR. 

Closing in favor of https://github.com/carbon-design-system/carbon-website/pull/2921

**Pull request closed without merging**
