### PR TITLE
Added fix for heading difference

### LINKED ISSUE #1178: docs: Update the Get Started guide for Angular
**Description**
In Step 1 of the Angular Get Started module, the heading type of certain elements does not align with the standard. 
For example, https://www.carbondesignsystem.com/tutorial/angular/step-1#add-starter-remote and https://www.carbondesignsystem.com/tutorial/angular/step-1#build-and-start are the same types of headings but the heading size is different.

### PR DESCRIPTION
**Pull request by rayandasoriya**
Closes #1178 

Fixes the difference in the heading types for Angular Getting Started Tutorial in Step 1.

#### Changelog

**New**

**Changed**

- Changed the heading type of three headings in Angular to make it consistent with the rest of the UI.

**Removed**

-

### CODE REVIEW

**Comment by rayandasoriya** [comment]
@janchild I have added that change as well. Let me know if there's anything else.

**Comment by rayandasoriya** [comment]
@jnm2377 The reason is that for Angular, there are two ways to start. One is through the `starter app` and the other one is `start from scratch`. For the same step in React and Vue, we have only one way to start building the application. Due to this, we have multiple sets of anchor links.

**Comment by janchild** [comment]
@rayandasoriya Given that there are two paths with eight steps within each path, I would not be concerned with trying to make the heading levels consistent with the other pages and just work to make this page easy for people to follow. 

Here is my recommendation for the content hierarchy to be correct on this page. 

- [ ] Leave anchor links as they are as the top of the page.
- [ ] Under the H2 "Use starter app" heading, restyle the anchor links  to <AnchorLinks small>.
- [ ] Change the H2 headings that fall under "Use starter app" to H3s, and change any H3 to H4. 
- [ ] Under the H2 "Start from scratch" heading, restyle the anchor links to <AnchorLinks small>.
- [ ] Change the H2 headings that fall under "Start from scratch" to H3s, and change any H3s to H4.

**Comment by rayandasoriya** [comment]
@janchild I think this is a good idea. I'll do that. Thanks.

**Comment by janchild** [comment]
@rayandasoriya A copy tweak for you. Could you please change this line

> "Now you can skip most of [Start from scratch](#start-from-scratch) and jump straight to [Create pages](#create-pages)."

to the following:

"From here you can continue the steps in [Start from scratch](#start-from-scratch) from [Create pages](#create-pages) onwards."

I think this change will make it clearer and address some of the awkwardness of jumping into a new set of instructions. Sorry I wasn't able to change it inline. 

Thank you!

**Comment by rayandasoriya** [comment]
Sure. I can do that.

**Comment by janchild** [comment]
@jnm2377 This looks good to me!

**Pull request merged**
