### PR TITLE
feat(Addons) Move WebsiteCodeSnippet to add-on

### LINKED ISSUE #1236: [website add-on] AnchorLinks
- [x] Move AnchorLinks  from `/src/components/` to `/packages/addons-website/src/`
- [x] Update add-on storybook
- [x] Update imports inside website to pull from add on instead of components folder. 

Import is set here https://github.com/carbon-design-system/carbon-website/blob/master/gatsby-config.js#L22

example component pulling in from add-on https://github.com/carbon-design-system/carbon-website/pull/1198/files#diff-b9e136416b90437fa1dac910280b45fcR34

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #1236 

Moves Snippet component to website addons and renames to WebsiteCodeSnippet

Also addresses style bugs from previously merged PR

### Testing
Make sure code snippet examples work and storybook works

### CODE REVIEW

**Comment by designertyler** [comment]
I can't scroll the code far enough to see anything that would be under the button. Adding an extra 32px to the bottom of the scrollable content could fix this by allowing the content to scroll above the button's background. 

Mar-14-2019 08-16-49

**Comment by alisonjoseph** [comment]
@designertyler that spacing is pulling directly from the carbon component, so we will want to look at it there. I also fixed the selection highlight color.

**Comment by designertyler** [comment]
Screen Shot 2019-03-14 at 9 43 13 AM

**Comment by alisonjoseph** [comment]
updated @designertyler

**Comment by vpicone** [comment]
If you scroll the first code snippet by using your mouse, the scroll track looks odd:
Screen Shot 2019-03-22 at 10 47 07 AM

**Comment by alisonjoseph** [comment]
@vpicone that might be a component issue? looks the same here http://react-experimental.carbondesignsystem.com/?selectedKind=CodeSnippet&selectedStory=single%20line&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by vpicone** [comment]
You're right! For the Component: 

We could avoid setting 'multi' to state and use something like this:

```
 state = {
    copied: false,
  };

  componentDidMount() {
    Prism.highlightAll();
  }
  
  componentDidUpdate() {
    Prism.highlightAll();
  }

  render() {
    const { children } = this.props;
    const type = this.codeRef && this.codeRef.clientHeight < 20 ? 'single' : 'multi';
...
```

**Comment by vpicone** [comment]
Realized the react  stuff might not be relevant to this PR 😅. The rest looks good to me!

**Comment by alisonjoseph** [comment]
Yea this PR is just moving what we have, but definitely down to optimize things in the future!

**Pull request merged**
