### PR TITLE
fix(checkbox): update checkbox colors and props

### PR DESCRIPTION
**Pull request by aledavila**
Closes https://github.com/carbon-design-system/carbon/issues/11268

Update checkbox color var and props

#### Changelog

**Changed**

- updated override color token
- added checked modifier to live demo

**Removed**

- removed a prop

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- [ ] The Checkbox heading and Checkbox label are not turning to disabled colors when "Disabled" is selected in dark themes. The text color should be `$text-disabled `. The icon is also getting some kind of border around it and there should be no border.
Screen Shot 2022-05-09 at 1 59 30 PM

**Comment by aledavila** [comment]
Hey @laurenmrice the border around the box seems to be an issue with the component when its is both checked and disabled and not the website. Would you mind opening an issue in the carbon repo please.

**Comment by laurenmrice** [comment]
@aledavila Ok! Issue has been made here: https://github.com/carbon-design-system/carbon/issues/11403

**Review by laurenmrice — APPROVED** [review]

**Comment by aledavila** [comment]
@tay1orjones one more review please 😄

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
