### PR TITLE
chore: use blob instead of copy strat

### PR DESCRIPTION
**Pull request by vpicone**
Uses blob strategy (like IDL) to generate SVG markup that is identical to the equivalent React markup.

Testing: SVG downloads should still work

### CODE REVIEW

**Comment by sstrubberg** [comment]
I can check this by ensuring that the icons can still be searched for?

**Comment by vpicone** [comment]
@sstrubberg this has to do with their downloading.

**Comment by sstrubberg** [comment]
Download works like champ. However, there is an odd, what feels like half-a-second delay when I hover over the download icon.

Feb-27-2020 10-18-51

**Comment by vpicone** [comment]
@sstrubberg hmmm, i'm not getting that. What browser?

**Pull request merged**
