### PR TITLE
feat: add banner to v9 website

### PR DESCRIPTION
**Pull request by alisonjoseph**
Ref #881 & PR https://github.com/carbon-design-system/carbon-website/pull/893

@aagonzales same question here around mobile

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Updated, the text seems a little bit long on mobile though. 
@claycrenshaw suggestions to shorten the text?

screen shot 2019-02-05 at 8 17 23 pm

**Comment by claycrenshaw** [comment]
For mobile I say we can just kill the second sentence. Also please be sure to include the hyphen in "production-ready". Thanks!

**Comment by alisonjoseph** [comment]
Can we get copy that works across all breakpoints. Also "Carbon X has arrived" might not be the best thing to say, since it hasn't actually arrived yet 😉

**Comment by aagonzales** [comment]
What about  just "See what's coming soon with Carbon V10-beta."

**Comment by aagonzales** [comment]
And can we make the banner not sticky and go away on scroll down?

**Comment by alisonjoseph** [comment]
Copy updated. will look at making it not sticky in separate PRs.

**Pull request merged**
