### PR TITLE
feat: update carbon-components to beta v10

### LINKED ISSUE #1377: bug fix[image component]: captions are wrong size and wrong distance from image
## bug fix[image component]: captions are wrong size and wrong distance from image

This must've happened recently but caption text on the image component is now the same size as the body copy, this is not correct... it should be styled the same as the text in the Do / Don't component.

- [x] change all captions size back to .875rem / 1.125rem 

- [x] captions should be spaced 8px below the image (right now there is no space, or in the case of animated gifs, there is 16px of space)

(random addition from Tyler, we could do this in markdown, but maybe this will reduce PRs)

- [x] For accordion usage, remove "zoom" and Caption: "test"

<br>

#### Correct caption styling:

<br>

#### Incorrect caption styling:

**Animated gif:** (16px spacing before caption, should be 8px)

**Static image:** (No spacing before caption, should be 8px)

**Accordion usage issue** (doesn't need this caption or zoom)

### PR DESCRIPTION
**Pull request by alisonjoseph**
Ref #1294 
Closes #1377

- updated to beta version of carbon-components, carbon-components-react, and carbon-elements (TODO: icons)
- removed sample html, examples are now pulling directly from carbon-components
- fixes image caption styles

## Review

- make sure no major regressions from live next.carbondesignsystem.com
- Any component example style issues can be flagged here https://github.com/carbon-design-system/carbon-website/issues/1370

Netlify builds are still timing out, will have to review locally, unfortunately.  (I'll try running it again)

### CODE REVIEW

**Comment by alisonjoseph** [comment]
@vpicone this gives us the option to pull html directly from the html folder instead of carbon-components, and I believe we are still using experimental for UI Shell.  I do see the error however, let me take a look

**Comment by vpicone** [comment]
I'm getting 
```
WARNING  Compiled with 1 warnings                                                                                         12:26:04 PM

 warning  in ./src/components/ComponentCode/ComponentCode.js

Module not found: Error: Can't resolve '../../html' in '/Users/vincepicone/Programming/Work/website/src/components/ComponentCode'**
```

**Comment by vpicone** [comment]
I think we might have accidentally nuked the `src/html` directory.

**Comment by alisonjoseph** [comment]
@vpicone ok, should be good now 🙏

**Comment by shixiedesign** [comment]
Hey Alison, not sure if you need visual review on this, but I noticed a few things. Could be future PR's fixes of course: 
- [ ] Combo box should not be showing as a component on component overview. Because it's actually put together with Dropdown, considered a Dropdown variant.
image
- [ ] Some type sizes became small. Should be regular body copy:
Lists are affected:
Eg. https://deploy-preview-1369--carbon-website.netlify.com/components/checkbox/usage
image
Eg https://deploy-preview-1369--carbon-website.netlify.com/components/structured-list/usage
image
Paragraph on https://deploy-preview-1369--carbon-website.netlify.com/components/dropdown/code
image
- [ ] Content / glossary page lost spacing, and some type became small
image

**Comment by alisonjoseph** [comment]
@shixiedesign working on these bugs in a new PR 👍

**Pull request merged**
