### PR TITLE
docs(Accordion): update Accordion knobs to include new props

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon-website/issues/1915

Adds in `disabled` props to `Accordion` demo. Also updates packages to the newest versions.

#### Changelog

**New**

- New knobs on the `Accordion` demo

**Changed**

- Updated `react-docgen.json`

**Removed**

- `Accordion` overrides from `overrides.json`

Ensure all component demos still work as expected

### CODE REVIEW

**Comment by tw15egan** [comment]
Noticing an issue when disabling a single `AccordionItem` the disabled border styles are being passed to all AccordionItems

**Comment by tw15egan** [comment]
Pushed up a fix here: https://github.com/carbon-design-system/carbon/pull/7142

**Review by jillianhowarth — COMMENTED** [review]
This is awesome! One note - it doesn't look like there's a way to go back to the default accordion size once another size is selected.

**Comment by tw15egan** [comment]
@jillianhowarth that sort of due to how that prop is used, we only allow `sm` and `xl` as options for size... to get the default size, you just wouldn't pass in the size prop i.e `size="xl"`

**Comment by jillianhowarth** [comment]
@tw15egan right, that makes sense in the code. My concern is that folks using the demo will click `sm` or `xl` and then not realize that there’s a third default size and not be able to get back to it if they want to see that size. It seems like in the demo we should have a third option for `default` the way we do for some of our other components

**Review by joshblack — APPROVED** [review]

**Comment by tw15egan** [comment]
We only allow `sm` or `xl` as options

Screen Shot 2020-10-27 at 12 03 28 PM

Just going to remove the size switcher for now, as this behavior can be seen in the react storybook and I don't want to spend too much time duplicating functionality

**Review by jillianhowarth — APPROVED** [review]
Sounds good!

**Review by aledavila — APPROVED** [review]

**Pull request merged**
