### PR TITLE
fix: added vertical tab variant

### LINKED ISSUE #4160: [Tabs] Add vertical variant to tab live demo
Need to add [vertical tab variant](https://react.carbondesignsystem.com/?path=/story/components-tabs--vertical) to the the live demo in usage docs.

We might need to switch to use the largest live demo component so that a user does not need to scroll horizontally but it also might fit in the current ratio.

### PR DESCRIPTION
**Pull request by riddhybansal**
Closes #4160 

Added vertical variant to tabs

#### Changelog

**New**

Added vertical variant to tabs

**Testing**

Go to Tabs and check if there is a vertical variant in livedemo and it works as intended

### CODE REVIEW

**Review by Kritvi-bhatia17 — COMMENTED** [review]
Hi @riddhybansal! I am able to see the "Vertical" option under the Tabs' Live demo, but I'm unsure about the output it’s showing. The output in the Live demo doesn’t seem to match what we have in our [React Storybook](https://react.carbondesignsystem. Could you please confirm that?

> Live demo 
> Screenshot 2024-08-28 at 3 07 16 AM 


> React storybook 
> Screenshot 2024-08-28 at 3 06 57 AM

**Review by alina-jacob — APPROVED** [review]
Looks good Riddhi! 🚀

**Comment by riddhybansal** [comment]
> Hi @riddhybansal! I am able to see the "Vertical" option under the Tabs' Live demo, but I'm unsure about the output it’s showing. The output in the Live demo doesn’t seem to match what we have in our [React Storybook](https://react.carbondesignsystem. Could you please confirm that?
> 
> > Live demo
> > Screenshot 2024-08-28 at 3 07 16 AM
> 
> > React storybook
> > Screenshot 2024-08-28 at 3 06 57 AM

Hi @Kritvi-bhatia17  I could see the same in preview, not sure whats happening for you.

**Review by Kritvi-bhatia17 — APPROVED** [review]
> > Hi @riddhybansal! I am able to see the "Vertical" option under the Tabs' Live demo, but I'm unsure about the output it’s showing. The output in the Live demo doesn’t seem to match what we have in our [React Storybook](https://react.carbondesignsystem. Could you please confirm that?
> > > Live demo
> > > Screenshot 2024-08-28 at 3 07 16 AM
> > 
> > 
> > > React storybook
> > > Screenshot 2024-08-28 at 3 06 57 AM
> 
> Hi @Kritvi-bhatia17 I could see the same in preview, not sure whats happening for you.

Hi @riddhybansal , thanks for confirming that. It is working fine in another browser, LGTM 🎉

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
Looks good, just needs to also get added to the demo on the code page.

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
