### PR TITLE
feat(ai-label): add overview image & accessibility table

### LINKED ISSUE #4130: AI label docs: Add live demo and a11y testing status
For the new AI label (formerly slug) component page, we need to add in a live demo and a11y status page. Can we add these things before the whole "making slug stable" issue? 

- [x] Add Live demo on usage tab
- [x] Add Live demo on code tab
- [ ] Add accessibility testing status
- [ ] Add to the [component overview](https://carbondesignsystem.com/components/overview/components) page

### PR DESCRIPTION
**Pull request by ariellalgilmore**
Closes #4130

Add to overview page:
Screenshot 2024-09-09 at 10 34 40 AM

AI Label accessibility overview
Screenshot 2024-09-09 at 10 36 24 AM

#### Changelog

**New**

- add `a11ystatus` component to view table
- ai label svg 

**Changed**

- components.json from "slug" -> "ai label"

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Hey, I noticed the advanced states are marked as `Not tested`. Do you have any thoughts on why the [advanced states tests](https://github.com/carbon-design-system/carbon/blob/7b69c563c23ad58af9ed31284a6a72ff66647a55/e2e/components/AILabel/Slug-test.avt.e2e.js#L25-L49) aren't pulling through in the report?

There's nothing wrong with this PR though, LGTM!

**Review by Kritvi-bhatia17 — COMMENTED** [review]
Hi @ariellalgilmore! This looks amazing 🔥

I just want to confirm one small thing with @laurenmrice first—although the AI label's Accessibility tab hasn't been updated with the latest template (which is totally fine as that workstream isn't part of this PR), should we place the accessibility testing status table under 'Development Considerations,' as we do for most components (like Button, Breadcrumb, etc.), or is it okay to place it at the top, just below the anchor links?

**Comment by laurenmrice** [comment]
@Kritvi-bhatia17 The "Accessibility status" table on the AI label > Accessibility tab should be an H3 under the H2 "Development considerations" section for consistency since that is how it appears on all of the other Accessibility tabs.

**Review by Kritvi-bhatia17 — CHANGES_REQUESTED** [review]
> @Kritvi-bhatia17 The "Accessibility status" table on the AI label > Accessibility tab should be an H3 under the H2 "Development considerations" section for consistency since that is how it appears on all of the other Accessibility tabs.

Got it, thanks for confirming that, @laurenmrice! That’s what I thought as well.

In that case, @ariellalgilmore, could you please move the Accessibility tab as an H3 under the H2 'Development considerations'? You can refer to the Button's [Accessibility tab](https://carbondesignsystem.com/components/button/accessibility#accessibility-testing-statusobject-objectobject-object) for guidance. 

Thank you! ✨

**Comment by ariellalgilmore** [comment]
thanks @Kritvi-bhatia17 and @laurenmrice. forgot to move it! just updated to the correct position

**Review by alisonjoseph — COMMENTED** [review]
This LGTM, one quick question, do we also want to add the status cards to the Usage page the way we do for other components? I think so? It likely just wasn't outlined in detail in the issue.

https://carbondesignsystem.com/components/accordion/usage/#accessibility-testing-status
Screenshot 2024-09-10 at 8 17 43 AM

**Comment by ariellalgilmore** [comment]
@alisonjoseph just updated! thanks!

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
