### PR TITLE
Tags: Remove AI presence for operable and selectable tags

### PR DESCRIPTION
**Pull request by aagonzales**
Related https://github.com/carbon-design-system/carbon/issues/17694

#### Changelog

**Removed**

- Remove `operable` and `dismissable` tags from the AI presence images

### CODE REVIEW

**Review by guidari — APPROVED** [review]

**Review by Kritvi-bhatia17 — COMMENTED** [review]
Hi @aagonzales!
Everything looks good, but I noticed one small issue. I checked in two different browsers, and while the Usage tab looks fine, the image in the Style tab doesn’t show the updated version. Can you please confirm this? If it's correct, I’ll approve it. Thanks!

image

**Comment by aagonzales** [comment]
@Kritvi-bhatia17 yeah I'm not sure why the preview isn't loading the new image version...

**Review by alisonjoseph — APPROVED** [review]

**Comment by Kritvi-bhatia17** [comment]
> @Kritvi-bhatia17 yeah I'm not sure why the preview isn't loading the new image version...

Hi @guidari, @alisonjoseph! could you please help us with this.

**Comment by alisonjoseph** [comment]
It's working locally for me and showing correct images, just fixed the formatting and pushed an update, hopefully the preview deploys.

**Review by Kritvi-bhatia17 — APPROVED** [review]
Thanks Alison, it's working fine now!

LGTM 🚀

**Pull request merged**
