### PR TITLE
fix[overflow menu icon]: overflow menu icon on color usage tab too sm…

### PR DESCRIPTION
**Pull request by sravan7**
…all #1861

Closes #
#1861  fixes this issue as mentioned in the comment

#### Changelog

**New**

- 
```
.color-token-value .bx--overflow-menu__icon {
  width: rem(16px);
  height: rem(16px);
}
```
**Changed**

- 
```
.color-token-value .bx--overflow-menu__icon {
  width: rem(12px);
  height: rem(12px);
}
```

**Removed**

- {{removed thing}}

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]

**Review by jeanservaas — COMMENTED** [review]
Yay, thanks for fixing this. One quick thing. Can you make the top margin be 8px to match the side margin on the hover state... so basically bump the whole thing up 8px?

image

**Review by aledavila — APPROVED** [review]
After Jean’s updates. Looks good

**Comment by tw15egan** [comment]
@jeanservaas I've made the requested changes for ya 👍

**Comment by jeanservaas** [comment]
@tw15egan huh, don't know why, but I'm still seeing it riding 8px low

image

**Comment by tw15egan** [comment]
Not sure what's going on with deployments, but it's rendering properly locally and picking up the -8px negative margin to bump it up 

Screen Shot 2020-10-19 at 12 57 41 PM

Screen Shot 2020-10-19 at 12 57 37 PM

**Review by jeanservaas — APPROVED** [review]
preview's not working but TJ sez it's koo.

**Pull request merged**
