### PR TITLE
Update step-2.mdx

### PR DESCRIPTION
**Pull request by JuliusKoronci**
Step 2 is broken atm and fails with missing mixins, when compared to step 3 the diff is the missing "carbon--" in front of the mixins which fixes the broken build

Closes #

Following the tutorial, step 2 failed for me with missing mixin error

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by JuliusKoronci** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by JuliusKoronci** [comment]
recheck

**Comment by JuliusKoronci** [comment]
recheck

**Comment by tay1orjones** [comment]
Hi @JuliusKoronci! Thanks so much for opening this to correct the tutorial's usage to include the new naming scheme for mixins. 

All the tutorial instructions are based on the v10 packages and have not been updated to reflect changes for the next major version. We'll need to make this update and all the other updates in one swoop, https://github.com/carbon-design-system/carbon/issues/10991. The team is working on this now.

**Comment by tay1orjones** [comment]
Hi @JuliusKoronci! Thanks so much for opening this to correct the tutorial's usage to include the new naming scheme for mixins. 

All the tutorial instructions are based on the v10 packages and have not been updated to reflect changes for the next major version. We'll need to make this update and all the other updates in one swoop, https://github.com/carbon-design-system/carbon/issues/10991. @aledavila and @jnm2377 are working on this now.

**Comment by aledavila** [comment]
Tutorial update PRs are up and closing in favor of #2917 and #2912 

Please comment again if this is incorrectly closed

**Pull request closed without merging**
