### PR TITLE
Add information personal access token for push

### PR DESCRIPTION
**Pull request by jlczuk**
The push to origin requires authenticating to github.  The 2-factor authentication prevents being able to use an actual password.  For command line operations, a personal access token is required to be used as the password.  This proposal adds this information.

Closes #

{{short description}}

#### Changelog

**New**

- none

**Changed**

- react-step-1.mdx 

**Removed**

- none

### CODE REVIEW

**Comment by jlczuk** [comment]
I see that the whole Note block is italicized, so the _Generate needs to be fixed.

**Comment by mattrosno** [comment]
@jlczuk does this only happen if you cloned with HTTPS (instead of SSH) AND you're GH account as 2FA enabled?

**Comment by jlczuk** [comment]
@mattrosno tbh, I was just blindly stumbling through the tutorial.  So most likely, I cut an paste what was there, which I do believe was https.  Now I wonder what would have happened if I attempted the push using ssh, regardless of how I cloned the repo.  I'll give it a try when I can free up some time.  I'm a little jammed right now.

**Comment by jlczuk** [comment]
git remote -v says:
origin	https://github.com/jlczuk/carbon-tutorial.git (fetch)
origin	https://github.com/jlczuk/carbon-tutorial.git (push)
upstream	https://github.com/carbon-design-system/carbon-tutorial.git (fetch)
upstream	https://github.com/carbon-design-system/carbon-tutorial.git (push)

I will have to undo all of this and retry using SSH.

**Comment by jlczuk** [comment]
@mattrosno I redid the tutorial using SSH and the problem did not occur, so I have to conclude that it was only for HTTP cloned repos with accounts that have 2FA enabled.

**Comment by mattrosno** [comment]
Thanks for the contribution! I updated to this when fixing a merge conflict. I'll approve this PR and add this note to the other tutorial steps in a separate PR.

_Note: If your Git remote protocol is HTTPS instead of SSH, you may be prompted to authenticate with GitHub when you push changes. If your GitHub account has two-factor authentication enabled, we recommend that you follow these instructions to [create a personal access token for the command line](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line). That lets you use your token instead of password when performing Git operations over HTTPS._

**Pull request merged**
