### PR TITLE
fix: missing call to function and fixed type checking

### PR DESCRIPTION
**Pull request by httpsOmkar**
Added function call

#### Changelog

**Changed**

- Added function call
- Replaced == with ===
- And simplyfy code

### CODE REVIEW

**Comment by httpsOmkar** [comment]
fixed!

**Comment by alisonjoseph** [comment]
Images still appear broken 
Screen Shot 2019-04-29 at 11 38 47 AM

**Comment by dakahn** [comment]
@httpsOmkar was this ready to re-review, friend?

**Comment by httpsOmkar** [comment]
Work in progress. I will notify once it will complete.

**Comment by httpsOmkar** [comment]
@alisonjoseph @dakahn Ready to re-review

**Comment by alisonjoseph** [comment]
Looks good to me! Just need to fix the merge conflict 😸 Thank you!

**Comment by httpsOmkar** [comment]
@alisonjoseph can you check this now

**Pull request merged**
