### PR TITLE
chore(component-index): update index ai app links

### LINKED ISSUE #1802: Links to the AI Apps components in the community asset page are broken
Within the AI Applications business, we recently went through a major overhaul and migrated all of the guidance on the IoT PAL to our new [AI Applications PAL](https://pages.github.ibm.com/ai-applications/design/)

Because of the migration, all of the links to the AI Apps components in the **community asset > component index** section are broken.

We are also revisiting the use and guidance of some of our components, and would like to remove some of the components on the list for now. Some of the components are also now supported by Carbon, so we will not be supporting separate guidance to prevent duplication. 

### Updated links to the components already on the page

Catalog / marketplace
- [x] https://pages.github.ibm.com/ai-applications/design/components/catalog-marketplace/usage

Data table
- [x] https://pages.github.ibm.com/ai-applications/design/components/datatable/overview

Fixed button bar
- [x] https://pages.github.ibm.com/ai-applications/design/components/fixedbuttonbar/usage

Icon content switcher
- [x] https://pages.github.ibm.com/ai-applications/design/components/iconcontentswitcher/usage

List builder 
- [x] https://pages.github.ibm.com/ai-applications/design/components/listbuilder/usage

Menus
- [x] https://pages.github.ibm.com/ai-applications/design/components/menus/usage

Progress indicator
- [x] https://pages.github.ibm.com/ai-applications/design/components/progressindicator/usage

Rule builder
- [x] https://pages.github.ibm.com/ai-applications/design/components/rulebuilder/usage

### Components requested to be removed from the list

- [x] Charts
- [x] Chips
- [x] Dropdown
- [x] Floating palette
- [x] Icon buttons
- [x] Icon tabs
- [x] Large modals
- [x] Link bar
- [x] Page title bar
- [x] Status icons
- [x] Text inputs
- [x] Tile
- [x] UI shell header
- [x] UI shell right panel
- [x] UI shell side nav

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #1802 

updated links on the component index for the AI Apps maintainer - please reference the issue to see all updated links and components.

### CODE REVIEW

**Review by janchild — APPROVED** [review]

**Review by emyarod — COMMENTED** [review]
are these changes supposed to look like unresolved merge conflicts?

**Comment by andreancardona** [comment]
> are these changes supposed to look like unresolved merge conflicts?

nope...not sure what happened - let me fix this!

**Comment by andreancardona** [comment]
@emyarod ready for your review :)

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by tw15egan** [comment]
Did we need to also remove those components listed from the index as requested? Seems like they are still there 

Screen Shot 2020-09-29 at 11 04 15 AM

**Comment by andreancardona** [comment]
> Did we need to also remove those components listed from the index as requested? Seems like they are still there
> 
> Screen Shot 2020-09-29 at 11 04 15 AM

I'm so confused I thought I deleted them - something must have happened in the merge - I'll fix this now 🤦‍♀️

**Comment by andreancardona** [comment]
@tw15egan updated :)

**Review by tw15egan — APPROVED** [review]
💯 👍 ✅

**Pull request merged**
