### PR TITLE
Revert "Merge branch 'v10-update'"

### PR DESCRIPTION
**Pull request by vpicone**
This reverts commit c41b39a5e812de682be74ea9bde97de5ebde314e, reversing
changes made to 5e4302c6077df26054c0e8cef6a7263c5c1af01f.

### CODE REVIEW

**Comment by vpicone** [comment]
Looks like there might have been some other commits to master as well, unsure if we want to revert those too.

**Comment by asudoh** [comment]
Hi @vpicone just curious (though I believe @alisonjoseph is aware of this), any background on the revert? Thanks!

**Comment by vpicone** [comment]
There was a lot of merge requests going down today I think this one slipped through early.

**Comment by alisonjoseph** [comment]
@asudoh I accidentally merged a draft PR I was working on, got my branches confused somehow 🤦‍♀️ this is just reverting that mistake

**Comment by asudoh** [comment]
Got it - Thank you for clarifying! @vpicone @alisonjoseph - If you can see this PR makes `master` in the original state it'll be good to go!

**Pull request merged**
