### PR TITLE
[Selectable Components: Tile - Usage] Website Doc

### PR DESCRIPTION
**Pull request by Kritvi-bhatia17**
Closes # [3861](https://github.com/carbon-design-system/carbon-website/issues/3861)

**Updated some of the Tile's doc images with what came out of our [final design solutions](https://github.com/carbon-design-system/carbon/issues/14766#issuecomment-1874852921).**

### CODE REVIEW

**Comment by Kritvi-bhatia17** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by Kritvi-bhatia17** [comment]
Recheck

**Review by laurenmrice — APPROVED** [review]
The images you changed look good. They are not showing up in the website preview in this PR, but sometimes that happens and they should change once its merged.

**Comment by Kritvi-bhatia17** [comment]
Hii devs @alisonjoseph and @tw15egan!
Can you please review this PR!?
Thanks a lot in advance 🙌🏻

**Review by alisonjoseph — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
