### PR TITLE
docs:Latest article update

### PR DESCRIPTION
**Pull request by designertyler**
Updates the latest article on the homepage and resource page

image

image

### CODE REVIEW

**Comment by designertyler** [comment]
Thoughts on using a smaller title as a workaround? 
image

**Comment by connor-leech** [comment]
@alisonjoseph are you zoomed on your browser? I'm not getting that breakage at any breakpoints in Firefox

**Comment by alisonjoseph** [comment]
Not zoomed, just smaller screen size, its fine if browser is full screen but otherwise no

**Comment by connor-leech** [comment]
@designertyler I'd like to avoid numbered releases, as we're actively trying to avoid "versioning" these announcements. We can just do "New in Carbon: October 2019"

**Comment by alisonjoseph** [comment]
Related, the Hacktoberfest title is too long also

**Pull request merged**
