### PR TITLE
fix(CodeSnippet): update single line and inline links and demo content

### LINKED ISSUE #2138: Code snippet demo bugs
The single line code snippet is showing multiline content, and the Code Sandbox demos are broken out of the box

image

### LINKED ISSUE #2171: fix[live demo]:single and multi line code snippet not displaying correctly
## fix[live demo]:single and multi line code snippet not displaying correctly

- Looks like multiline code snippet content is trying to display in the single line code snippet

- Multiline code snippet is incorrectly centered in the middle of the component instead of being left aligned.

image

image

## Correct behavior in Storybook

single line

image

multiline

image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2138
Closes #2171 

This PR updates the storybook links in CodeSnippet examples and shows the correct content for single line and inline examples on the website

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by tw15egan** [comment]
@emyarod should we also throw a `width: 100%` on the `.bx--snippet-container` class? Right now they are centered 

Screen Shot 2021-02-16 at 1 32 30 PM

**Comment by emyarod** [comment]
the centering is caused by the component preview styles in the website: https://github.com/carbon-design-system/carbon-website/blob/master/src/components/ComponentDemo/ComponentDemo.module.scss#L290-L293

**Comment by tw15egan** [comment]
@emyarod yeah, I was wondering if we should override that on the website so it doesn't render centered

**Comment by emyarod** [comment]
yes I pushed https://github.com/carbon-design-system/carbon-website/pull/2139/commits/a13b7a9a86b0784e75ca9c4fd7c7be6a7d738cfa for that

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
