### PR TITLE
fix(motion): add video to motion overview

### LINKED ISSUE #1738: [Carbon site] Add Motion UX movie in lead space.
For whatever reasons the animation was left out when migrating this page from IDL. I think this needs to go in. 

Goes under the anchor links

https://www.carbondesignsystem.com/guidelines/motion/basics

### PR DESCRIPTION
**Pull request by tw15egan**
Closes #1738 

Adds in a video to `Guidelines/Motion`

### CODE REVIEW

**Review by jillianhowarth — COMMENTED** [review]
When I view the preview it says the video can't be played because of privacy settings. 
Screen Shot 2020-10-06 at 5 01 34 PM

**Comment by tw15egan** [comment]
@jillianhowarth should be fine once we get it on the main website, I'm guessing the Vercel preview is not one of the allowed domains.

Is the positioning on the page correct?

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by jillianhowarth — APPROVED** [review]
@tw15egan sounds good. Yep, otherwise it looks great!

**Pull request merged**
