### PR TITLE
Updated Optional versus required fields section

### PR DESCRIPTION
**Pull request by jjennings7**
Updated documentation to include the use of (required) as well as (optional).

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

### CODE REVIEW

**Comment by jjennings7** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by tw15egan — APPROVED** [review]

**Review by sstrubberg — APPROVED** [review]

**Review by laurenmrice — COMMENTED** [review]
@jjennings7 Where did you get the example content for the required image? Is this an actual product at IBM I can reference? I am just wondering because I was going to edit the two images and send them back but wanted some more info.
Screen Shot 2021-09-02 at 12 19 16 PM

**Comment by jjennings7** [comment]
@laurenmrice it's from DataStage, it's an example of properties for Cloud Object Storage but edited and super-simplified. I have the sketch files so I'm happy to make any changes you would suggest.

**Comment by laurenmrice** [comment]
@jjennings7 I made a couple tweaks to the Optional and Required images and am attaching the sketch file here. For the required image, can you add a heading and description text to the form and see if there is any placeholder text or real text you could put in for the fields that I indicated in the file?

**Comment by jjennings7** [comment]
@laurenmrice How's this? 
[revised form optional and required images.zip](https://github.com/carbon-design-system/carbon-website/files/7199071/revised.form.optional.and.required.images.zip)

**Comment by laurenmrice** [comment]
@jjennings7 Thanks for filling in the content! Sending this back one more time to you to export the images out. I just fixed a typo and the line length of a description.

[revised form optional and required images-lr.zip](https://github.com/carbon-design-system/carbon-website/files/7213506/revised.form.optional.and.required.images-lr.zip)

**Comment by jjennings7** [comment]
@laurenmrice Here are the exports, at 2x with white backgrounds. Thanks for your help!
form-usage-optional
form-usage-required

**Review by laurenmrice — APPROVED** [review]
The content looks good and I will update the images in a separate PR. 👍

**Pull request merged**
