### PR TITLE
Flucca/fix/tile component style page check change

### LINKED ISSUE #2497: update check emoji to carbon icon on tile style page
[Proportions for grid table](https://carbondesignsystem.com/components/tile/style#proportions-for-grid) on tile component's style page should be using carbon icons rather then the emoji checks check ✅

image

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #2497

Use checkmark outline svg component instead of check emoji in Tile component's style page
#### Changelog

**Changed**

- src/pages/components/tile/style.mdx: replaced check emoji

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]

**Comment by thyhmdo** [comment]
We need to use this checkmark and in green color instead of the success icon. The checkmarks inside the circle indicates the success or the completion of the process. [See more](https://carbondesignsystem-git-fork-francin-af6949-carbon-design-system.vercel.app/patterns/status-indicator-pattern/#medium-attention)

image

**Comment by francinelucca** [comment]
> We need to use this checkmark and in green color instead of the success icon. The checkmarks inside the circle indicates the success or the completion of the process. [See more](https://carbondesignsystem-git-fork-francin-af6949-carbon-design-system.vercel.app/patterns/status-indicator-pattern/#medium-attention)
> 
> image

@kingtraceyj just confirming, are we good to use `<Checkmark />` in green instead of `<CheckmarkOutline />` in `gray 100`?

**Comment by kingtraceyj** [comment]
@thyhmdo and @francinelucca — @jeanservaas said to use checkmark outline in gray 100 but i'm open to discussion!

image

**Comment by kingtraceyj** [comment]
@francinelucca we are going to go with `checkmark` but in `icon-primary` (or `gray 100` whatever token/color makes sense 😅 )

**Pull request merged**
