### PR TITLE
Switch from staticfile buildpack to nginx buildpack

### LINKED ISSUE #190: Redirects for tutorial links
With the launch of the Vue tutorial series, the paths for all the React tutorial links were broken. 

Can the website have redirects to handle these old paths? 

https://www.carbondesignsystem.com/tutorial/overview
https://www.carbondesignsystem.com/tutorial/react-step-1/
https://www.carbondesignsystem.com/tutorial/react-step-2/
https://www.carbondesignsystem.com/tutorial/react-step-3/
https://www.carbondesignsystem.com/tutorial/react-step-4/
https://www.carbondesignsystem.com/tutorial/react-step-5/
 https://www.carbondesignsystem.com/tutorial/wrapping-up

### LINKED ISSUE #247: Add redirects for updated navigation
We've recently had some navigation changes that are tripping people up and causing broken links. We need to add redirects. Recommend comparing https://github.com/carbon-design-system/carbon-website/blob/master/src/data/nav-items.yaml to https://github.com/carbon-design-system/carbon-website-archive/blob/master/src/data/navigation/navigation.json (check git history)

Some links I know for sure need to be redirected

- Getting started -> Get started
- Tutorial links

### PR DESCRIPTION
**Pull request by vpicone**
closes #247
closes #190

preview link: https://carbon-nginx.us-south.cf.appdomain.cloud

This switches from the `staticfile-buildpack` (which doesn't use Cache-Control headers at all) to the `nginx-buildpack`. There's two main advantages to this:

- Implement gatsby's ideal caching strategy: https://www.gatsbyjs.org/docs/caching/
- Server side rewrites/redirects

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Is there a way to test this? 

Also need to add contributions -> how to contribute also
```
  ['/contributions/overview', '/how-to-contribute/overview'],
    ['/contributions/governance', '/how-to-contribute/governance'],
    [
      '/contributions/bugs-and-requests',
      '/how-to-contribute/bugs-and-requests',
    ],
    ['/contributions/documentation', '/how-to-contribute/documentation'],
    ['/contributions/component', '/how-to-contribute/component'],
    ['/contributions/pattern', '/how-to-contribute/pattern'],
    ['/contributions/add-ons', '/how-to-contribute/add-ons'],
```

**Comment by vpicone** [comment]
@emyarod are you using the blue mix link? @alisonjoseph link is fixed

**Comment by emyarod** [comment]
yeah `/getting-started/about-carbon` and `/tutorial/overview` lead to 404s

**Comment by alisonjoseph** [comment]
Link is working now but some redirects aren't working/missing

**Comment by vpicone** [comment]
Is it the same ones @emyarod mentioned? I just used the ones in your plugin pr.

**Comment by alisonjoseph** [comment]
this is the full list

```
    ['/getting-started/about-carbon', '/get-started/about-carbon'],
    ['/getting-started/developers/vanilla', '/get-started/develop/vanilla'],
    ['/getting-started/designers', '/get-started/design'],
    ['/tutorial/overview', '/tutorial/react/overview'],
    ['/tutorial/react-step-1', '/tutorial/react/step-1'],
    ['/tutorial/react-step-2', '/tutorial/react/step-2'],
    ['/tutorial/react-step-3', '/tutorial/react/step-3'],
    ['/tutorial/react-step-4', '/tutorial/react/step-4'],
    ['/tutorial/react-step-5', '/tutorial/react/step-5'],
    ['/tutorial/wrapping-up', '/tutorial/react/wrapping-up'],
    ['/contributions/overview', '/how-to-contribute/overview'],
    ['/contributions/governance', '/how-to-contribute/governance'],
    [
      '/contributions/bugs-and-requests',
      '/how-to-contribute/bugs-and-requests',
    ],
    ['/contributions/documentation', '/how-to-contribute/documentation'],
    ['/contributions/component', '/how-to-contribute/component'],
    ['/contributions/pattern', '/how-to-contribute/pattern'],
    ['/contributions/add-ons', '/how-to-contribute/add-ons'],
```

So need to add all the contributions redirects and the ones that aren't working
`'/tutorial/overview`
`/getting-started/about-carbon`

**Comment by vpicone** [comment]
@alisonjoseph @emyarod redeployed with the new redirects

**Comment by vpicone** [comment]
@alisonjoseph @emyarod redeployed with the full list

**Pull request merged**
