### PR TITLE
feat: update-node-18

### LINKED ISSUE #3510: (project): update carbon-website to node v18

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #3510

### CODE REVIEW

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
There are some file changes in this PR that I don't think should be there? With component pages/images?

**Comment by tay1orjones** [comment]
@alisonjoseph I just updated this to remove those invalid changes

**Review by tay1orjones — APPROVED** [review]
Thanks for pairing up on this today!

The first attempt at updating this https://github.com/carbon-design-system/carbon-website/pull/3456 resulted in the icons and pictogram pages not working and it had to be reverted https://github.com/carbon-design-system/carbon-website/pull/3469

In this case, the deploy preview looks good (those pages didn't work on the #3469 deploy preview)

So I think this is good! 🎉  I'm not sure what the issue was with the old PR, we didn't do anything different here. Might've been an issue with a transitive dependency or something perhaps that has since been resolved.

**Review by alisonjoseph — APPROVED** [review]
LGTM other than ci failing

**Review by francinelucca — APPROVED** [review]

**Pull request merged**
