### PR TITLE
fix(icon-library): update dropdown max-height

### PR DESCRIPTION
**Pull request by jnm2377**
Rel: https://github.com/carbon-design-system/design-language-website/issues/560

### CODE REVIEW

**Comment by joshblack** [comment]
Seems like this may be a mismatch in code vs guidance, potentially?

cc @laurenmrice noticed you specified this in the new guidance over in: https://www.carbondesignsystem.com/components/dropdown/usage#scrolling-behavior

Do we need to make sure this is updated in code on the system side?

**Comment by laurenmrice** [comment]
-We already do this in code. Currently in code its cropping the 4th option. 
Screen Shot 2020-06-02 at 4 27 14 PM

-In the usage guidance for dropdown, I recommended cropping at the 5th option as a rule since this is being used for product UIs, however this could also depend on the usecase at hand. https://www.carbondesignsystem.com/components/dropdown/usage#scrolling-behavior

-Mike is suggesting to crop at the 6th option in the issue.

I think it is the matter of deciding what our recommendation would be of when to crop. 
@mjabbink what do you think?

**Comment by joshblack** [comment]
@laurenmrice totally makes sense to me. It seems like after we decide on 5 or 6 then we could have a fix put in upstream that the site pulls in versus needing to do an override here. What do you think, @jnm2377? 👀

**Comment by jnm2377** [comment]
@joshblack if we decide to fix it in upstream, I'm fine with closing this PR. I'll wait for design input.

**Comment by laurenmrice** [comment]
@joshblack and @jnm2377 we are going to stick with cropping at the 6th option. I'm going to update the dropdown usage docs to reflect that.

**Comment by joshblack** [comment]
Sounds great, @laurenmrice. Would you mind making an issue for updating this in code? I'll make sure we tackle it this week/next 👍

**Comment by laurenmrice** [comment]
on it! thank you

**Pull request closed without merging**
