### PR TITLE
chore(release): bump carbon to v10.16.0-rc.1

### PR DESCRIPTION
**Pull request by dakahn**
Let's bump Carbon's Website to rc.1, friends :surfer:

### CODE REVIEW

**Comment by vpicone** [comment]
@dakahn are we missin the new icons?

**Comment by dakahn** [comment]
@vpicone is it in here? 
https://github.com/carbon-design-system/carbon/releases/tag/v10.16.0

**Comment by vpicone** [comment]
@dakahn yeah, icons and icons-react got bumped right?

Also, did ya'll see the side nav @andreancardona @rjhenriquez? It's all grayed out.

Screen Shot 2020-07-20 at 3 40 17 PM

**Comment by vpicone** [comment]
When we update packages, gotta remember to run `yarn` afterwords so the lock file is updated as well.

**Comment by andreancardona** [comment]
@vpicone ugh shoot yep I see it now :/  @dakahn

**Comment by tw15egan** [comment]
The color on the site using this selector `.bx--side-nav .bx--side-nav__submenu[aria-haspopup=true], .bx--side-nav__item>a.bx--side-nav__link` to override the colors.

The `[aria-haspopup=true]`  selector was removed as part of https://github.com/carbon-design-system/carbon/pull/6468 for a11y reasons. Will need to update the override on the site to not use `aria-haspopup-true`

**Comment by vpicone** [comment]
@tw15egan published a patch removing those selectors last night, it's in the latest version of the gatsby theme. We needed them to match the specificity of Carbon without using `!importants` everywhere, just missed the memo on their removal haha.

**Comment by vpicone** [comment]
We can close this in favor of https://github.com/carbon-design-system/carbon-website/pull/1400 if you want @dakahn

**Comment by tw15egan** [comment]
Yeah sorry about that! Hopefully, this is the last selector in Carbon that relies on data attributes for styling... (don't quote me on that)

**Comment by vpicone** [comment]
@tw15egan I really like that pattern for things like `aria-busy` animating a loading spinner in a button. Is it a bad idea to be attaching styles to roles?

**Comment by tw15egan** [comment]
For things like that, not at all! I think the main issue is when we are attaching _wrong_ aria roles and then using them to style, as it increases the specificity too much and then anyone trying to override them has to then use those selectors as well.

**Pull request closed without merging**
