### PR TITLE
V10 homepage updates

### PR DESCRIPTION
**Pull request by alisonjoseph**
Homepage updates 

@jeanservaas below is the list of updates we went over yesterday. I'll tag you when they are done/ready for review!

- [x] header image should be 512px tall (@jeanservaas, assuming should scale down at smaller screens? let me know 😄 )
- [x] header image should align bottom not top
- [x] add 1px white dots (need an image, gradient is rendering too big and decimal values don't render on non-retina screens) 75% white
- [x] add 25% padding to the right of tiles at medium and bigger breakpoint
- [x] fix spacing on all h3s
- [x] check font weight on small headings at top/bottom of page, should be 400 not 300
- [x] add 4rem bottom padding to articles
- [x] add 1px black outline/stroke in between tiles (is currently transparent)

tracking these separately
- [x] tiles should match aspect ratio on IDL site when scaling (have fixed height)
- [x] update article images (get size from @jeanservaas )

### CODE REVIEW

**Comment by jeanservaas** [comment]
## Comments:

- Dot size look great, but can we take down the opacity now a bit more so they're a little less bright? (Is it at 75% opacity now?)

image

- I know we tried top aligning the homepage image... maybe we should try vertically centering it like you suggested... now it's riding a little low

image

- Seems small but this is a big issue for Mike, a FED at PwC told me there was a universal way that we can transform "dumb quotes" to "curly quotes" site wide... https://dwheeler.com/essays/quotes-in-html.html (have zero idea if this link is helpful... but it talks about curly quotes in code)

image

image

- Looks like there's a weird forced line break happening in the intro paragraph at the 1056 breakpoint

screen shot 2018-12-11 at 5 08 24 pm

- The "Start Designing" and "Start Developing" cards are 320 x 160px (at the 1312 breakpoint) should always maintain the 1:2 aspect ratio as they scale at various breakpoints; also they need to be bottom aligned to the graphic (Same scale treatment applies to the Other Resources cards)

screen shot 2018-12-11 at 5 22 14 pm


- Other resources cards and "Start Designing" / "Start Developing" are basically the same component;
the padding relationship should be the same (see below); but on staging, it looks like the Other Resources have 24px padding and the "Start designing" / "Start developing cards have 16px"

_(Streamline padding and, if possible, the arrow can be 14px from the bottom instead of the 16px for optical alignment):_

screen shot 2018-12-11 at 5 30 10 pm


- The divider rules between the cards and the articles (or tiles, whatever we're calling them) should be only 1px, they look like they are 2px now); they should be an actual 1px rule too (color: #000000), not a gap, so you can't see the dots between them

screen shot 2018-12-11 at 5 13 59 pm

screen shot 2018-12-11 at 5 16 25 pm

- Can we take Margin Bottom after H2 down to 24px (it looks like it's at 48px now); I can double check, but I think this could be a site wide change to align with IDL...

screen shot 2018-12-11 at 5 42 24 pm

- For the articles, the images can be 320x180 and maintain the 16x9 aspect ratio (I will get you some new images)

image

**Comment by alisonjoseph** [comment]
Hey @jeanservaas ready for re-review here http://carbon-website-random-impressive-mongoose.stage1.mybluemix.net/

*I noticed after building and pushing that the line break is missing from "Inclusive, flexible
and consistent" I updated that locally but didn't rebuild and push to the staging link above since that takes close to 10 min.

**Comment by jeanservaas** [comment]
This is looking so much better! Dots look great! Image is displaying much better too!

Couple small things:

- These are the aspect ratios we apply in the system for ref:

image

- The article images are perfect at 16:9

-  However the Card component (i.e. 'Start Designing' etc and the resources should actually be a 1:2 aspect ratio... half a square... in order to match IDL site. This will apply to that card component wherever it's used across the site.

image


- Also, really like the margin distance that you have above "Inclusive, flexible and consistent" (I tried to inspect it but I didn't see what it was...) Can we duplicate that distance throughout the homepage so those spacings are consistent? It looks like that's what you do have above "Other Resources,"  "Latest Articles" and "Wondering how to contribute" too.

image

image

image


- Last thing, since the article titles are shorter than I thought, can I get an 88px margin bottom on those guys to give them more weight? I think we have 48px now. Also, that little dash is actually an "Em dash" — (shift + option + minus)

image


- I'm also working on getting you some article images for now... and then trying to figure out how to deal with those things in the future so it's not a pain in the ass.

- you are awesome for hanging with me on these details! Thank you!!!

**Comment by alisonjoseph** [comment]
ok, I think we are almost there! http://carbon-website-random-impressive-mongoose.stage1.mybluemix.net/

@jeanservaas

**Comment by jeanservaas** [comment]
Nice, looking really tight... Now I'm kind of starting to QA the breakpoints:

- Just want to match the size / ratio of the "start designing" "started dev'ing" cards to the other resources cards... which are now perfect.

image

## Breakpoint behavior 
Sketch file: https://ibm.box.com/s/589knwzwuxkuj850ev137f2fka0p7taf

_I just updated my sketch file to include breakpoints, cause I kind of left you hanging without those and basically all my other comments have to do with breakpoints_

- IDL and our site are breaking differently; this is probably because the IDL is using Fluid type. Since this experience isn't product, we would ideally use the the fluid type here too. _(see 1056 and tablet designs in my file... our headline would stay at two columns until tablet)._

image


- Also, large top type does go full screen at tablet, but you will get the margin bottom after the "Inclusive, flexible and consistent" too so there will be separation.


image

## Line lengths at breakpoints
- Our line lengths get too long when the site goes full screen... we need to figure out how to systematize these line lengths at diff. breakpoints so we're matching IDL and our guidance. _See line lengths at breakpoints in my designs._

—
Ours 1056ish:
image

IDL 1056ish:
image


<br>

## Margins at breakpoints

- We want 16px margins at tablet

overview 672 copy

- But at mobile we want our our card component (and any hanging images) to go full bleed)

overview_mobile

<br>

## Article component at breakpoints

- Articles break to two columns at tablet and stack at mobile

- Can article image go to 1:2 aspect ratio at mobile, so they are smaller? Hate to break a rule, but they don't need to big so big

- Also, ideally, we keep the big margin bottom padding for the articles so that there's good separation between articles in mobile. 

image

<br>

## Smaller things (that might be site-wide glitches)

- Can we just make sure the period at the end of this sentence is also the same color as the link?

image

- Just want to double check on the arrow asset that we're pulling, is it the same as IDL? Ours looks thicker

image


- Also, Mike is mentioning that he's seeing Helvetica instead of Plex coming in in certain areas like the contribute section in Chrome... not sure why that's happening.

image

- Still looks like we're using the extra light for some reason instead of the light; not quite sure why that's happening tho but you can see when you compare sites in chrome
image

**Comment by alisonjoseph** [comment]
For any of the headings that need to use fluid type can you just let me know which token to use? I'm pulling directly from Carbon elements.

**Comment by alisonjoseph** [comment]
@jeanservaas I think I got most of these updates made, with some comments below with questions highlighted **bold**.

http://carbon-website-random-impressive-mongoose.stage1.mybluemix.net

### Updates made

- Updated arrow icon to pull from carbon-elements `icons-react` package, its using `ArrowRight24` now
- Updated responsive styles for featured tile
- Updated font weight to be 400 on top/bottom paragraphs on the homepage **(the responsive tokens seemed too large for this, but if they should be using one of them let me know)**
- Updated aspect ratio on feature tiles (sorry missed this one before!)
- Tiles should now all be full bleed at small breakpoint (across entire site)
- Unsure about the best way to swap article images at a break point to get the different aspect ratios. Leaving this for now, we can make an enhancement issue to update the component to support multiple images if needed or look in to another solution. 
- I'm not seeing Helvetica anywhere. weird, wonder if its an issue w/ google fonts for some reason. We can open a separate bug issue for that if others are seeing it. 
- updated column width for paragraphs on medium breakpoint so they don't span full width. (currently 6 col, but 5 might work also) this is across the site
- Updated grid container margins (actually padding) to be 16px at medium breakpoint, **but wondering is this specific just to our website or should this be updated in the core grid code?** cc @joshblack

**Comment by jeanservaas** [comment]
Man, you're turning things around faster than I can comment!!! Badass!!!!

- here's the fluid type token: $expressive-heading-04

_that should automate everything and I'm hoping... deal with that font weight issue... we were right to be using the (300) weight for the headline type (it goes from 400 to 300 at the sizes above 24px) but it just looked like it was coming in at Extra Light before... now it looks like we've gone back to Regular weight (400) which isn't right either... I think it's just some kind of glitch... maybe tokenizing will help_

image


- Also, you've totally matched the arrows for Start Developing and Start Designing... can we match now for this guy too?

image

- Margins at breakpoints are getting a lot tighter... here's one thing I noticed... at tablet, ALL type should still have 32px margin so that it aligns with the type in the containers (cards); ALL images and hanging containers should have a 16px margin:

image

these guys too:
image

image

- One other thing I noticed about using the fluid type... in digital and in IDL, their vertical spacing (i.e. margin tops and bottoms also seem to be fluid... they are getting smaller at each breakpoint as the browser scales). 

image

- It would be great to figure that out eventually, but if we can't, let's just make sure that all the distances are equal at every breakpoint; there's especially a lot of space after "Inclusive, flexible and consistent" and "Wondering how to contribute" 

image

- IMAGES FOR ARTICLES COMING... I want to get this back to you asap so I'll send them separately!

**Comment by jeanservaas** [comment]
## Homepage images:

https://ibm.box.com/s/s8uangx03r6rxp4e6m5cjqa6lmcbpa1s

- also remade that gradient image for "Start Designing" -- there were some weird black separations in the one I made before

- please let me know if you want me to remake these; I'm sure they're not named right either... I just saved them out quick as svgs and pngs... they're 16x9 aspect ratio but they might be too big. lmk. thanks!

**Pull request merged**
