### PR TITLE
docs: 1187-update-pictograms-contribution-page

### LINKED ISSUE #1187: Update Carbon Pictograms Contribution page
**Background/Problem:** The process for design/approving UI-Icons and Pictograms is changing. We need to request a change on the page

**Copy**

- [x] Producing an icon

•	Create a 32 x 32 px artboard for each pictogram.
•	32 px pictograms should have 1 px padding.
•	Set your workspace up from the start to snap to grid.
•	Be aware of automatic alignments which can place vectors on uneven or half pixels.
•	The pictogram should be on the top-most layer in your artboard. Strokes should be grouped appropriately.
•	Make sure to properly name layers and artboards (these names will also be exported into the code).

- [ ] Production-ready

•	To be considered production-ready, all pictogram submissions must be delivered in Adobe Illustrator format at 32 x 32 px with strokes kept intact.
•	Each artboard and the artwork within it must be aligned to the pixel grid wherever possible.
•	All strokes should be kept as is and not converted to shapes.
•	Group strokes logically whenever possible.

- [ ] Contribution process

Does your pictogram have potential for other materials at IBM? If so, please consider contributing to the design system. IBM welcomes pictogram contributions in the form of a pull request to our pictogram repository (coming soon). For now, to make a pull request, please submit an issue in the repo [bolded text should be a link to here: https://github.ibm.com/brand/Pictograms/issues/new/choose] with the pictogram attached.
Please note that Carbon contribution is **not required** in order to introduce a new pictogram into your materials. If your pictogram is determined to be broadly useful in Carbon and passes IBM Brand design reviews, then it may also be integrated into the design system.
If your submission is accepted, the team will notify you. If changes are needed, you’ll need to create a new contribution issue after reworking it based on feedback from the Design System and Brand teams.

@conradennis Is the above the final copy from Lori?

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #1187 

**Please Note:**

- This PR and issue is attached to an IDL issue and PR that can be found below: 

    - Issue: https://github.com/carbon-design-system/design-language-website/issues/528
    - PR: https://github.com/carbon-design-system/design-language-website/pull/551

### CODE REVIEW

**Comment by janchild** [comment]
Hi @andreancardona, can you double-check the anchor links and the H2s on the page. I'm not able to edit on the Files changed tab. Thanks!

**Comment by janchild** [comment]
@andreancardona A couple of things here:

1. I spoke with @mjabbink and he agreed that this page could move to the "How to contribute" section on the Carbon website. It would sit underneath Patterns in the IA. (We will also need to move the Icons contribute tab from the Icon section. I can open an issue for that.)

2. The anchor links currently don't match the H2 headings below. 
Should be: 
- Producing a pictogram
- Producing an icon
- Exporting SVGs
- Contribution process

3. Also a copy tweak for one of the anchorlinks. Should be "Producing a pictogram".

4. In **Export SVGs from Sketch**, step 3 needs a period. 

4. In **Export SVGs from Adobe Illustrator**, step 12 needs a period.

**Comment by andreancardona** [comment]
@andreancardona A couple of things here:

1.
- [x] Move Pictogram "contribute" page
- [x] Move Icons "contribute" page

2. The anchor links currently don't match the H2 headings below.
Should be:

- Producing a pictogram
- Producing an icon
- Exporting SVGs
- Contribution process

- [ ] Check any other pages linking to the contribution site

3. Also a copy tweak for one of the anchorlinks. Should be "Producing a pictogram".

4. In Export SVGs from Sketch, step 3 needs a period.

5. In Export SVGs from Adobe Illustrator, step 12 needs a period.

**Comment by andreancardona** [comment]
Closing this issue - the issues in this PR are fixed here: https://github.com/carbon-design-system/carbon-website/pull/1229

**Pull request closed without merging**
