### PR TITLE
fix(community-index): 1800-avt1-community-index-downshift-label

### LINKED ISSUE #1800: audit-avt1-community-insight-component-index: id downshift label
## Environment:

> Operating system: Mac
> Browser: Chrome 
> AVT :one:
> Page: [Community insight - Component index](https://www.carbondesignsystem.com/community/component-index)

## Detailed Description: 

The 'id' "downshift-5-label" specified for the WAI-ARIA property 'aria-labelledby' value is not valid

Screen Shot 2020-09-22 at 11 04 50 AM

## Why is this important? 
Any element that uses a WAI-ARIA property must reference a valid id attribute. This enables assistive technologies to precisely identify the referenced element.

## What to do: 
Update the WAI-ARIA property value with the unique id value of a valid visible element.

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #1800 

- Fixes `Downshift` accessibility violation by adding a `textTitle` prop to the `Dropdown` component in Component Index.

## TESTING: 

- [ ] Run `Accessibility Checker` and make sure the above violation (as seen in #1800) does not appear.
- Preview link: https://carbondesignsy-git-fork-andreancardona-1800-avt1-communi-340aec.carbon-design-system.now.sh/community/component-index

### CODE REVIEW

**Review by aagonzales — COMMENTED** [review]
It looks good! But can we had a hover background to the closed state? Color: `$hover-ui`

image

**Review by tay1orjones — APPROVED** [review]
This may fall out of the bounds of the implementation here and be more of a question for the component implementation itself, but should clicking the label also close the dropdown once it's open?

It currently has a bit of an odd focus movement - the dropdown opens, and then when the label is clicked the focus flashes, moving from the input to the listbox


https://user-images.githubusercontent.com/3360588/106655561-24491580-655f-11eb-8d24-3b16303bdade.mov

**Comment by andreancardona** [comment]
> It looks good! But can we had a hover background to the closed state? Color: `$hover-ui`
> 
> image

updated the hover! @aagonzales

**Review by aagonzales — APPROVED** [review]
Looks good!

**Review by dakahn — APPROVED** [review]

**Pull request merged**
