### PR TITLE
Update/add tokens and values

### PR DESCRIPTION
**Pull request by shixiedesign**
Closes https://github.com/carbon-design-system/carbon-website/issues/295
Closes https://github.com/carbon-design-system/carbon-website/issues/319
Closes https://github.com/carbon-design-system/carbon-website/issues/320

Update website documentation following palette change. 

#### Changelog

**New**

`$danger`, `$text-05`

**Changed**
1. Changed token color assignment:
`$text-02` `$text-03` `$support-01` `$inverse-support-04`

2. Changed token color hex values:
It appears these hex values are detached from our color repo. So I manually updated all the color's hex to the new hex values.

### CODE REVIEW

**Comment by aagonzales** [comment]
Should we just add in the new tokens and not the v2 palette changes? The rest of the token set doesn't have the new v2 values yet.

**Comment by shixiedesign** [comment]
I updated the hex in rest of the token set too. Lemme mention that in the description. @aagonzales

**Comment by aagonzales** [comment]
Should we wait to merge this then until then end of the release? So the color changes role out all the once in all the assets?

**Comment by shixiedesign** [comment]
Okay! 👍

**Comment by aagonzales** [comment]
Cool! 

Also normally we write out hex codes all in lowercase but it looks like their all consistently upper case on this page so maybe it ok.

**Comment by shixiedesign** [comment]
@alisonjoseph I changed everything to uppercase. I can change all to lower case too but if consistency is the matter, all uppercase should be okay too? Lemme know. I don't mind doing it if it's needed.

**Comment by alisonjoseph** [comment]
I think if you run `yarn format` if you have this locally prettier will automatically update to lowercase.

**Pull request merged**
