### PR TITLE
docs: v11 size token updates for pagination component

### PR DESCRIPTION
**Pull request by thyhmdo**
This PR updates the size tokens on the Style tab for the pagination component.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by vpicone — COMMENTED** [review]
Sorry, I haven't been in the size prop loop, but we only have one size right? Is there a reason we're calling it "Large" and not "Normal" What is "Large" relative to?

**Review by dakahn — APPROVED** [review]

**Comment by aagonzales** [comment]
You're not out of the loop @vpicone we're just trying to figure these things out on the fly. I agree though, if a component only has one size then it doesn't need a size section. `height` should just be indicated in the structure table and image.

**Comment by aagonzales** [comment]
So I think we can actually just close/delete this PR since no changes are actually needed?

**Review by jillianhowarth — APPROVED** [review]

**Comment by aagonzales** [comment]
Closing this PR, no changes needed sense it doesn't have size variations.

**Pull request closed without merging**
